import { ApiError } from "../utils/errors.js";
import type { CapabilityPreviewBody } from "../preview/types.js";
import { extractCandidateProfileInput, generateJobProfileInput, cvScoreInput, cvJobMatchInput, cvImproveInput, candidateShortlistScoreInput } from "../schemas/recruitmentInputs.js";

const ALIASES: Record<string, string> = { js: "JavaScript", javascript: "JavaScript", "react.js": "React", react: "React", powerbi: "Microsoft Power BI", "power bi": "Microsoft Power BI", "ms sql": "Microsoft SQL Server", sfdc: "Salesforce", salesforce: "Salesforce", "dynamics 365": "Microsoft Dynamics 365", "oracle ebs r12": "Oracle ERP" };
const PROTECTED = /\b(race|ethnicity|religion|nationality|gender|sex|sexual orientation|pregnan|marital|age|date of birth|disab|medical|political|union|photo|photograph)\b/i;
const clean = (s: string) => s.replace(/\s+/g, " ").trim();
const canonical = (s: string) => ALIASES[clean(s).toLowerCase()] ?? clean(s);
const lines = (s: string) => s.split(/\r?\n/).map(clean).filter(Boolean);
const section = (s: string, names: string[]) => { const ls = lines(s); const start = ls.findIndex(x => names.some(n => x.toLowerCase() === n || x.toLowerCase().startsWith(`${n} `))); if (start < 0) return []; const headers = ["experience", "employment", "education", "skills", "certifications", "languages", "projects", "summary", "profile", "الخبرة", "التعليم", "اللغات", "المشاريع", "الملخص"]; const end = ls.slice(start + 1).findIndex(x => headers.includes(x.toLowerCase())); const body = end < 0 ? ls.slice(start + 1, start + 9) : ls.slice(start + 1, start + 1 + end); return body.filter(x => !/^[A-Z][A-Z &/]+$/.test(x)); };
const evidence = (value: string, source: string) => ({ value, evidence: [source.slice(0, 240)] });
function textFrom(input: { cv_text?: string; candidate_profile?: unknown }) { if (input.cv_text) return input.cv_text; return JSON.stringify(input.candidate_profile); }
function skillsFrom(s: string) { const found = new Map<string, string>(); for (const term of Object.keys(ALIASES).concat(["TypeScript", "Python", "Java", "AWS", "Azure", "Kubernetes", "SQL", "Excel", "SAP", "Tableau", "Node.js", "Docker", "Linux", "C#", "Go"])) { if (new RegExp(`(?<![A-Za-z])${term.replace(/[.+]/g, "\\$&")}(?![A-Za-z])`, "i").test(s)) found.set(canonical(term), term); } return [...found].map(([name, source]) => ({ name, category: "Professional", confidence: 0.9, evidence: [source] })); }
function years(s: string) { const matches = [...s.matchAll(/(19|20)\d{2}/g)].map(m => Number(m[0])).filter(n => n > 1950 && n <= new Date().getUTCFullYear()); if (matches.length < 2) return null; return Math.min(50, Math.round(((Math.max(...matches) - Math.min(...matches)) + 1) * 10) / 10); }
function profileFrom(s: string) { const ls = lines(s); const skills = skillsFrom(s); const experience = section(s, ["experience", "employment", "الخبرة"]).map(x => ({ job_title: x, company: "", start_date: "", end_date: "", duration_months: null, employment_type: null, responsibilities: [], achievements: [], technologies: skills.filter(k => x.toLowerCase().includes(k.name.toLowerCase())).map(k => k.name) })); const education = section(s, ["education", "التعليم"]).map(x => ({ qualification: x, institution: "", year: null, evidence: [x] })); const protectedLines = ls.filter(x => PROTECTED.test(x)); const missing = [experience.length ? "" : "experience", education.length ? "" : "education", skills.length ? "" : "skills"].filter(Boolean); return { candidate: { name: null, headline: ls[0] ?? null, professional_summary: section(s, ["summary", "profile", "الملخص"])[0] ?? null, location: null }, experience, education, skills, certifications: section(s, ["certifications", "الشهادات"]).map(x => evidence(x, x)), languages: section(s, ["languages", "اللغات"]), projects: section(s, ["projects", "المشاريع"]), industries: [], management_experience: /\b(manager|director|lead|مدير|قيادة)\b/i.test(s) ? true : null, total_experience_years: years(s), recent_role: experience[0]?.job_title ?? null, seniority_estimate: /\b(director|principal|senior|lead|مدير|خبير)\b/i.test(s) ? "senior" : experience.length > 2 ? "mid" : experience.length ? "junior" : null, career_progression: [], candidate_keywords: skills.map(k => k.name), evidence_quality: { score: Math.max(0, 100 - missing.length * 20 - (protectedLines.length ? 5 : 0)), missing_information: missing, ambiguities: protectedLines.length ? ["Protected personal attributes were ignored for scoring."] : [] } }; }
export async function extractCandidateProfile(raw: unknown) { const input = extractCandidateProfileInput.parse(raw); if (input.document_url) throw new ApiError(415, "UNSUPPORTED_DOCUMENT", "Document URL extraction is not enabled for this capability deployment; provide extracted cv_text."); return profileFrom(input.cv_text!); }
function jobFrom(s: string, title?: string) { const ls = lines(s); const skillTerms = skillsFrom(s).map(x => x.name); const required = skillTerms.filter(k => new RegExp(`(required|must|essential|mandatory)[^\\n]{0,100}${k}`, "i").test(s) || /required|must|essential|mandatory/i.test(s)); const req = [...new Set(required.length ? required : skillTerms.slice(0, Math.max(1, Math.ceil(skillTerms.length / 2))))]; const preferred = skillTerms.filter(k => !req.includes(k)); return { job_title: title ?? ls[0] ?? "", role_family: "", seniority: /senior|lead|director|manager/i.test(s) ? "senior" : "mid", industry: [], required_skills: req.map(skill => ({ skill, importance: "required", weight: Math.round(70 / Math.max(1, req.length)) })), preferred_skills: preferred.map(skill => ({ skill, importance: "preferred", weight: Math.round(30 / Math.max(1, preferred.length)) })), required_experience_years: (s.match(/(\d+)\+?\s+years?/i)?.[1] ? Number(s.match(/(\d+)\+?\s+years?/i)![1]) : null), preferred_experience_years: null, required_education: section(s, ["education", "degree"]), certifications: section(s, ["certification"]), responsibilities: section(s, ["responsibilities", "المسؤوليات"]), domain_experience: [], technical_requirements: [], leadership_requirements: [], language_requirements: [], location_requirements: null, employment_type: null, keywords: skillTerms, scoring_model: { skills_weight: 40, experience_weight: 25, education_weight: 10, domain_weight: 10, responsibilities_weight: 15 } }; }
export async function generateJobProfile(raw: unknown) { const input = generateJobProfileInput.parse(raw); return jobFrom(input.job_description, input.job_title); }
function scoreCv(s: string) { const p = profileFrom(s); const dimensions = { completeness: Math.min(100, 40 + p.experience.length * 15 + p.education.length * 10 + (p.skills.length ? 15 : 0)), clarity: s.length > 500 ? 80 : 55, experience: p.experience.length ? 75 : 20, achievements: /\b(increased|reduced|saved|grew|delivered|improved|٪|%|\$|revenue)\b/i.test(s) ? 85 : 45, skills: p.skills.length ? 80 : 25, ats_readability: /[\u0600-\u06ff]/.test(s) && /[A-Za-z]/.test(s) ? 80 : 75 }; const score = Math.round(Object.values(dimensions).reduce((a, b) => a + b, 0) / Object.values(dimensions).length); return { score, dimensions, strengths: [p.experience.length ? "Work history is present." : "", p.skills.length ? "Skills are explicitly listed." : ""].filter(Boolean), weaknesses: [p.experience.length ? "" : "Add a structured experience section.", /quantified|increased|reduced|saved|%/i.test(s) ? "" : "Add measurable outcomes where known."].filter(Boolean), missing_sections: p.evidence_quality.missing_information, high_priority_improvements: ["Use evidence-backed achievement bullets.", "Keep dates and role titles consistent."], warnings: p.evidence_quality.ambiguities, confidence: Math.min(0.98, 0.55 + Math.min(0.4, s.length / 5000)) }; }
export async function cvScore(raw: unknown) { const input = cvScoreInput.parse(raw); return scoreCv(textFrom(input)); }
function match(candidate: any, job: any) { const skills = new Set((candidate.skills ?? []).map((x: any) => canonical(typeof x === "string" ? x : x.name ?? x.skill ?? "")).map((x: string) => x.toLowerCase())); const required = (job.required_skills ?? []).map((x: any) => typeof x === "string" ? x : x.skill).filter(Boolean); const skillMatch = required.map((r: string) => { const c = canonical(r); const ok = skills.has(c.toLowerCase()); return { requirement: r, status: ok ? "matched" : "missing", candidate_evidence: ok ? c : null, confidence: ok ? 0.9 : 0.95 }; }); const skillScore = required.length ? Math.round(skillMatch.reduce((a: number, x: any) => a + (x.status === "matched" ? 100 : 0), 0) / required.length) : 50; const exp = candidate.total_experience_years == null || job.required_experience_years == null ? 50 : Math.min(100, Math.round(candidate.total_experience_years / job.required_experience_years * 100)); const score = Math.round(skillScore * 0.5 + exp * 0.3 + 50 * 0.2); return { match_score: score, decision_support: { strong_match: skillMatch.filter((x: any) => x.status === "matched").map((x: any) => x.requirement), partial_match: [], missing_required: skillMatch.filter((x: any) => x.status === "missing").map((x: any) => x.requirement), missing_preferred: [] }, category_scores: { required_skills: skillScore, experience: exp, domain: 50, responsibilities: 50, education: 50, certifications: 50 }, skill_match: skillMatch, experience_analysis: { candidate_years: candidate.total_experience_years ?? null, required_years: job.required_experience_years ?? null }, transferable_skills: [], gaps: skillMatch.filter((x: any) => x.status === "missing").map((x: any) => x.requirement), risk_flags: [], confidence: candidate.evidence_quality?.score ? Math.min(0.98, candidate.evidence_quality.score / 100) : 0.7, explanation: "Score is based on normalized job-relevant skills and supplied experience evidence only." }; }
export async function cvJobMatch(raw: unknown) { const input = cvJobMatchInput.parse(raw); const c = input.candidate_profile ?? profileFrom(input.cv_text!); const j = input.job_profile ?? jobFrom(input.job_description!); return match(c, j); }
export async function cvImprove(raw: unknown) { const input = cvImproveInput.parse(raw); const text = textFrom(input); const scored = scoreCv(text); return { current_score: scored.score, priority_actions: scored.high_priority_improvements, summary_recommendations: ["Lead with a concise role-relevant summary backed by evidence."], experience_recommendations: ["Rewrite bullets as action, context, result; add numbers only when known."], skill_recommendations: ["Group skills by category and use canonical names."], ats_recommendations: ["Use standard section headings and consistent dates."], job_specific_recommendations: input.target_job_description ? ["Map each job requirement to a truthful CV bullet or mark it as a gap."] : [], rewrite_examples: [], keywords_to_consider: input.target_job_description ? skillsFrom(input.target_job_description).map(x => x.name) : [], warnings: ["Recommendations never invent experience, achievements, technologies, certifications or metrics."] }; }
export async function candidateShortlistScore(raw: unknown) { const input = candidateShortlistScoreInput.parse(raw); const candidates = input.candidates.slice(0, input.max_candidates).map(c => ({ candidate_id: c.candidate_id, ...match(c.candidate_profile, input.job_profile) })); return { job: input.job_profile, candidates, scoring_methodology: { weights: { required_skills: 50, experience: 30, evidence: 20 }, skill_match: { exact: 100, equivalent: 90, related: 70, partial: 40, missing: 0 }, protected_attributes: "Ignored; never used for scoring or ranking.", decision_boundary: "Decision support only; no hire, reject or interview recommendation." } }; }

export async function previewRecruitment(raw: unknown, capability: string): Promise<CapabilityPreviewBody> { if (capability === "cv_score") { const result = await cvScore(raw); return { status: "limited", inputRecognized: true, preview: { coverageScore: result.score, availableSections: ["score", "strengths", "improvements"], signals: { strengthCount: result.strengths.length, improvementCount: result.high_priority_improvements.length } }, capability }; } if (capability === "extract_candidate_profile") { const result = await extractCandidateProfile(raw); return { status: "limited", inputRecognized: true, preview: { availableSections: ["candidate", "experience", "skills", "evidence_quality"], signals: { skillCount: result.skills.length, experienceCount: result.experience.length, evidenceQuality: result.evidence_quality.score } }, capability }; } const input = capability === "generate_job_profile" ? generateJobProfileInput.parse(raw) : raw; return { status: "available", inputRecognized: Boolean(input), preview: { availableSections: ["normalized_requirements", "scoring_model"] }, capability }; }
