import assert from "node:assert/strict";
import { test } from "node:test";
import { randomUUID } from "node:crypto";
import { once } from "node:events";
import { execFileSync } from "node:child_process";
import { CustomerStore } from "../src/db/store.js";
import { createApp } from "../src/api/app.js";
import { loadConfig } from "../src/config/env.js";
const url = process.env.TEST_DATABASE_URL;
test("PostgreSQL customer integration (dedicated test database required)", { skip: !url }, async t => {
  const store = new CustomerStore(url!);
  const second = new CustomerStore(url!);
  t.after(async () => { await store.close(); await second.close(); });
  await Promise.all([store.migrate(),second.migrate()]);
  await store.ready();
  const create = (rpm=100,quota=1000) => store.createCustomer({ name: "Integration "+randomUUID(), requestsPerMinute: rpm, monthlyQuota: quota });
  await t.test("operator CLI migration, customer creation, key issue and revocation", async () => {
    const cli = (...args: string[]) => JSON.parse(execFileSync(process.execPath,["--import","tsx","src/admin.ts",...args], { env:{...process.env,DATABASE_URL:url},encoding:"utf8",windowsHide:true }));
    assert.equal(cli("migrate").migrated,true);
    const customer = cli("customer:create","CLI Test","30","100");
    const key = cli("key:issue",customer.id,"primary");
    assert.equal((await store.authenticate(key.key)).customerId,customer.id);
    assert.deepEqual(cli("usage",customer.id),[]);
    assert.equal(cli("key:revoke",customer.id,key.keyId).revoked,true);
    await assert.rejects(store.authenticate(key.key),{code:"UNAUTHORIZED"});
  });
  await t.test("only key digests persist; tenant-scoped revocation and usage", async () => {
    const a = await create(), b = await create();
    const ka = await store.issueKey(a.id,"primary"), kb = await store.issueKey(b.id,"primary");
    const p = await store.authenticate(ka.key);
    assert.equal(p.customerId,a.id);
    const row = (await store.pool.query("SELECT * FROM rafid_keys WHERE id=$1",[ka.keyId])).rows[0];
    assert.equal(row.digest.length,64); assert.ok(!JSON.stringify(row).includes(ka.key));
    await assert.rejects(store.revokeKey(b.id,ka.keyId));
    const id = randomUUID();
    await store.admit(p,id,"analyze_property"); await store.complete(p,id,200,12);
    await store.complete(await store.authenticate(kb.key),id,500,99);
    assert.equal((await store.usage(a.id))[0].status,200);
    assert.deepEqual(await store.usage(b.id),[]);
    await store.revokeKey(a.id,ka.keyId);
    await assert.rejects(second.authenticate(ka.key),{ code:"UNAUTHORIZED" });
    await assert.rejects(store.admit(p,randomUUID(),"analyze_property"),{ code:"UNAUTHORIZED" });
    await store.setActive(b.id,false);
    await assert.rejects(store.authenticate(kb.key),{ code:"UNAUTHORIZED" });
    await store.setActive(b.id,true); assert.equal((await store.authenticate(kb.key)).customerId,b.id);
  });
  await t.test("atomic monthly quotas shared across keys and separate pools; tenant isolation", async () => {
    const a = await create(100,3), b = await create();
    const k1 = await store.issueKey(a.id,"one"), k2 = await store.issueKey(a.id,"two");
    const p1 = await store.authenticate(k1.key), p2 = await second.authenticate(k2.key);
    const results = await Promise.allSettled(Array.from({ length: 12 },(_,i) => (i%2 ? second : store).admit(i%2 ? p2 : p1,randomUUID(),"analyze_property")));
    assert.equal(results.filter(r=>r.status==="fulfilled").length,3);
    assert.equal(results.filter(r=>r.status==="rejected" && r.reason.code==="QUOTA_EXCEEDED").length,9);
    const key = await store.issueKey(b.id,"other");
    await store.admit(await store.authenticate(key.key),randomUUID(),"compare_properties");
    assert.equal((await store.usage(a.id)).length,12);
    assert.equal((await store.usage(b.id)).length,1);
  });
  await t.test("minute rate limit and UTC minute/month reset", async () => {
    const c = await create(1,2), k = await store.issueKey(c.id,"rate");
    const p = await store.authenticate(k.key);
    await store.admit(p,randomUUID(),"analyze_property");
    await assert.rejects(store.admit(p,randomUUID(),"analyze_property"),{ code:"RATE_LIMITED" });
    await store.pool.query("UPDATE rafid_counters SET minute_start=minute_start-interval '2 minutes' WHERE customer_id=$1",[c.id]);
    await store.admit(p,randomUUID(),"analyze_property");
    await assert.rejects(store.admit(p,randomUUID(),"analyze_property"),{ code:"QUOTA_EXCEEDED" });
    await store.pool.query("UPDATE rafid_counters SET minute_start=minute_start-interval '2 minutes',month_start=month_start-interval '1 month' WHERE customer_id=$1",[c.id]);
    await store.admit(p,randomUUID(),"analyze_property");
  });
  await t.test("HTTP stores final status/duration, invalid requests count, no property data, aliases share quota", async () => {
    const customer = await create(100,2), key = await store.issueKey(customer.id,"http");
    const config = loadConfig({ AUTH_MODE:"postgres",DATABASE_URL:url,LOG_LEVEL:"silent" });
    const server = createApp(config,{store}).listen(0,"127.0.0.1");
    t.after(() => { server.closeAllConnections(); server.close(); });
    await once(server,"listening");
    const a = server.address(); assert.ok(a && typeof a!=="string");
    const post = (body:unknown,path="/api/v1/property/analyze",token=key.key) => fetch(`http://127.0.0.1:${a.port}${path}`,{method:"POST",headers:{"X-API-Key":token,"Content-Type":"application/json"},body:JSON.stringify(body)});
    assert.equal((await post({},"/api/v1/property/analyze","wrong")).status,401);
    assert.equal((await post({ propertyValue:0,annualRent:7200 })).status,400);
    assert.equal((await post({ propertyValue:85000,annualRent:7200 },"/v1/property/analyze")).status,200);
    const denied = await post({ propertyValue:85000,annualRent:7200 });
    assert.equal(denied.status,429); assert.equal((await denied.json()).error.code,"QUOTA_EXCEEDED");
    const rows = await store.usage(customer.id);
    assert.deepEqual(rows.map(r=>r.status).sort(),[200,400,429]);
    assert.ok(rows.every(r=>Number.isInteger(r.duration_ms)));
    assert.ok(!JSON.stringify(rows).includes("85000")); assert.ok(!JSON.stringify(rows).includes(key.key));
    assert.equal(rows.filter(r=>r.admitted).length,2);
  });
  await t.test("database failures never fall back to configured keys", async () => {
    const failed = new CustomerStore(url!); await failed.close();
    const config = loadConfig({AUTH_MODE:"postgres",DATABASE_URL:url,RAFID_API_KEYS:"test-only-fallback-123456789",LOG_LEVEL:"silent"});
    const server = createApp(config,{store:failed}).listen(0,"127.0.0.1");
    t.after(() => { server.closeAllConnections(); server.close(); }); await once(server,"listening");
    const a = server.address(); assert.ok(a && typeof a!=="string");
    const response = await fetch(`http://127.0.0.1:${a.port}/api/v1/property/analyze`,{method:"POST",headers:{"X-API-Key":"test-only-fallback-123456789"}});
    assert.equal(response.status,503);
    assert.equal((await response.json()).error.code,"SERVICE_UNAVAILABLE");
  });
});
test("PostgreSQL config is explicit and required in production", () => {
  assert.throws(()=>loadConfig({AUTH_MODE:"postgres"}));
  assert.throws(()=>loadConfig({NODE_ENV:"production",RAFID_API_KEYS:"test-only-key-long-enough-123"}));
  assert.equal(loadConfig({NODE_ENV:"production",AUTH_MODE:"postgres",DATABASE_URL:"postgresql://localhost/rafid"}).authMode,"postgres");
});
