import { safeFeedFetch, FeedFetchError } from "../domain/oman/safeFeedFetch.js";
import { FeedUrlRejectedError, type HostResolver } from "../domain/oman/feedSecurity.js";
import { websiteAuditInput, type WebsiteAuditInput } from "../schemas/websiteAuditInputs.js";
import { websiteAuditOutput, type WebsiteAuditOutput } from "../schemas/websiteAuditOutputs.js";
import type { CapabilityPreviewBody } from "../preview/types.js";

type AuditCategory = WebsiteAuditOutput["scores"] extends infer _T ? "performance" | "seo" | "accessibility" | "security" | "ux" | "technical" : never;
type Issue = WebsiteAuditOutput["seoIssues"][number];
export interface WebsiteAuditFetchOptions { fetchImpl?: typeof fetch; resolver?: HostResolver; timeoutMs?: number; maxResponseBytes?: number; }
const categories: AuditCategory[] = ["performance", "seo", "accessibility", "security", "ux", "technical"];
const issue = (category: AuditCategory, severity: Issue["severity"], text: string, evidence: string, url: string, action: string, effort: Issue["estimatedFixEffort"]): Issue => ({ category, severity, issue: text, evidence, affectedUrl: url, recommendedAction: action, estimatedFixEffort: effort });
const clamp = (n: number) => Math.max(0, Math.min(100, Math.round(n)));
const attr = (html: string, tag: string, name: string) => new RegExp(`<${tag}\\b[^>]*\\b${name}\\s*=\\s*["']([^"']*)`, "i").exec(html)?.[1] ?? null;
const count = (html: string, tag: string) => (html.match(new RegExp(`<${tag}\\b`, "gi")) ?? []).length;
const text = (html: string) => html.replace(/<script[\s\S]*?<\/script>/gi, " ").replace(/<style[\s\S]*?<\/style>/gi, " ").replace(/<[^>]+>/g, " ").replace(/\s+/g, " ").trim();
const absolute = (href: string, base: URL) => { try { const u = new URL(href, base); return u.protocol === "https:" && u.origin === base.origin ? u.toString().split("#")[0]! : null; } catch { return null; } };

function inspectPage(url: string, status: number, html: string, headers: Headers, selected: readonly AuditCategory[]) {
  const u = new URL(url); const found: Issue[] = [];
  const title = attr(html, "title", "") ?? (/<title\b[^>]*>([\s\S]*?)<\/title>/i.exec(html)?.[1]?.trim() ?? null);
  const metaDescription = /<meta\b[^>]*name\s*=\s*["']description["'][^>]*>/i.test(html);
  const canonical = /<link\b[^>]*rel\s*=\s*["'][^"']*canonical/i.test(html);
  const h1 = count(html, "h1");
  const images = [...html.matchAll(/<img\b[^>]*>/gi)].map(m => m[0]);
  const links = [...html.matchAll(/<a\b[^>]*href\s*=\s*["']([^"']+)/gi)].map(m => m[1]!).map(h => absolute(h, u)).filter((x): x is string => Boolean(x));
  const add = (i: Issue) => { if (selected.includes(i.category)) found.push(i); };
  if (selected.includes("seo")) { if (!title) add(issue("seo", "high", "Missing page title", "No <title> element was found.", url, "Add a unique, descriptive title for the page.", "low")); if (!metaDescription) add(issue("seo", "medium", "Missing meta description", "No meta name=description element was found.", url, "Add a concise, unique meta description.", "low")); if (!canonical) add(issue("seo", "low", "Missing canonical link", "No canonical link element was found.", url, "Add a canonical URL when this page has a preferred indexable URL.", "low")); if (h1 === 0) add(issue("seo", "medium", "Missing H1 heading", "No H1 element was found.", url, "Add one descriptive H1 heading.", "low")); if (h1 > 1) add(issue("seo", "low", "Multiple H1 headings", `Found ${h1} H1 elements.`, url, "Review heading hierarchy and keep one primary page heading where appropriate.", "low")); if (!/<meta\b[^>]*property\s*=\s*["']og:title/i.test(html)) add(issue("seo", "low", "Missing Open Graph title", "No og:title metadata was found.", url, "Add Open Graph metadata for share previews.", "low")); }
  if (selected.includes("accessibility")) { if (!attr(html, "html", "lang")) add(issue("accessibility", "high", "Missing document language", "The html element has no lang attribute.", url, "Set the document language on <html>.", "low")); const missingAlt = images.filter(img => !/\balt\s*=/.test(img)).length; if (missingAlt) add(issue("accessibility", "high", "Images missing alternative text", `${missingAlt} image element(s) have no alt attribute.`, url, "Provide meaningful alt text or an empty alt for decorative images.", "medium")); const forms = count(html, "form"); const labels = count(html, "label"); if (forms > labels) add(issue("accessibility", "medium", "Forms may have unlabeled controls", `Found ${forms} form(s) and ${labels} label element(s); this is an automated indicator, not a WCAG determination.`, url, "Associate every form control with a visible label.", "medium")); }
  if (selected.includes("performance")) { const scripts = count(html, "script"); const styles = count(html, "link"); if (html.length > 500_000) add(issue("performance", "high", "Large HTML response", `Homepage HTML is ${html.length} bytes.`, url, "Reduce document size and defer non-critical content.", "medium")); if (scripts > 20) add(issue("performance", "medium", "Many script elements", `Found ${scripts} script element(s).`, url, "Remove unused scripts and defer non-critical JavaScript.", "medium")); if (styles > 15) add(issue("performance", "low", "Many linked resources", `Found ${styles} link element(s).`, url, "Consolidate or remove unused stylesheets and resource hints.", "low")); if (images.length && images.some(img => !/\bloading\s*=/.test(img))) add(issue("performance", "low", "Images without explicit lazy-loading hints", "At least one image lacks a loading attribute; not every image should be lazy-loaded.", url, "Lazy-load below-the-fold images after measuring impact.", "low")); }
  if (selected.includes("security")) { if (u.protocol !== "https:") add(issue("security", "critical", "Website is not HTTPS", "The audited URL uses a non-HTTPS scheme.", url, "Serve the site over HTTPS and redirect HTTP to HTTPS.", "high")); const required: [string, string, Issue["severity"]][] = [["content-security-policy", "Missing Content-Security-Policy header", "medium"], ["strict-transport-security", "Missing HSTS header", "medium"], ["x-content-type-options", "Missing X-Content-Type-Options header", "low"], ["referrer-policy", "Missing Referrer-Policy header", "low"], ["permissions-policy", "Missing Permissions-Policy header", "low"]]; for (const [header, name, severity] of required) if (!headers.get(header)) add(issue("security", severity, name, `Response did not include ${header}.`, url, `Configure ${header} with a policy appropriate for the application.`, severity === "medium" ? "medium" : "low")); if (/<img\b[^>]*src\s*=\s*["']http:/i.test(html) || /<script\b[^>]*src\s*=\s*["']http:/i.test(html)) add(issue("security", "high", "Mixed-content references", "An HTTP image or script reference was found in the HTML.", url, "Load all active resources over HTTPS.", "medium")); }
  if (selected.includes("technical")) { if (!/<meta\b[^>]*charset\s*=|<meta\b[^>]*http-equiv\s*=\s*["']content-type/i.test(html)) add(issue("technical", "low", "Missing explicit charset metadata", "No HTML charset declaration was detected.", url, "Declare UTF-8 in the document head.", "low")); if (!/<meta\b[^>]*name\s*=\s*["']viewport/i.test(html)) add(issue("technical", "medium", "Missing mobile viewport", "No viewport meta element was detected.", url, "Add a responsive viewport declaration.", "low")); if (!/<html\b/i.test(html)) add(issue("technical", "medium", "Malformed HTML document", "No html element was detected in the fetched response.", url, "Return a valid HTML document structure.", "medium")); }
  if (selected.includes("ux") && text(html).length < 120) add(issue("ux", "low", "Very little visible text", `Only ${text(html).length} non-markup characters were detected; automated inspection cannot assess human UX.`, url, "Review the page content and navigation with a human usability check.", "unknown"));
  return { title, links, found };
}

export async function auditWebsite(raw: unknown, options: WebsiteAuditFetchOptions = {}): Promise<WebsiteAuditOutput> {
  const input = websiteAuditInput.parse(raw) as WebsiteAuditInput; const root = new URL(input.url); const selected = input.auditTypes as readonly AuditCategory[];
  const opts = { timeoutMs: options.timeoutMs ?? 8000, maxResponseBytes: options.maxResponseBytes ?? 1_500_000, fetchImpl: options.fetchImpl, resolver: options.resolver };
  const queue = [root.toString()]; const seen = new Set<string>(); const all: Issue[] = []; const pages: WebsiteAuditOutput["pagesAudited"] = []; const limitations: string[] = ["Automated passive inspection is not a complete WCAG, penetration, Lighthouse or human UX assessment.", "Core Web Vitals, real-user metrics and resource waterfall timings are unavailable from this bounded HTML inspection."];
  while (queue.length && seen.size < input.maxPages) { const url = queue.shift()!; if (seen.has(url)) continue; seen.add(url); try { const fetched = await safeFeedFetch(url, { ...opts, maxRedirects: 3 }); const html = fetched.body; const inspected = inspectPage(fetched.finalUrl, fetched.status, html, fetched.headers, selected); all.push(...inspected.found); pages.push({ url: fetched.finalUrl, status: fetched.status, title: inspected.title, sizeBytes: Buffer.byteLength(html), internalLinksFound: inspected.links.length, issues: inspected.found.length }); if (seen.size < input.maxPages) for (const link of inspected.links) if (!queue.includes(link) && !seen.has(link)) queue.push(link); } catch (error) { const message = error instanceof FeedUrlRejectedError ? `URL rejected by SSRF protection (${error.reason}).` : error instanceof FeedFetchError ? `Fetch unavailable (${error.kind}).` : "Fetch unavailable."; limitations.push(`${url}: ${message}`); pages.push({ url, status: null, title: null, sizeBytes: null, internalLinksFound: 0, issues: 0 }); } }
  if (!pages.length) throw new Error("Website audit could not fetch a page");
  if (selected.includes("seo") || selected.includes("technical")) {
    for (const [path, label] of [["/robots.txt", "robots.txt"], ["/sitemap.xml", "sitemap.xml"]] as const) {
      try {
        const auxiliary = await safeFeedFetch(new URL(path, root).toString(), { ...opts, maxRedirects: 3 });
        if (auxiliary.status >= 400) all.push(issue("technical", "low", `${label} was not found`, `${label} returned HTTP ${auxiliary.status}.`, root.toString(), `Publish a valid ${label} when the site needs crawl guidance.`, "low"));
      } catch (error) {
        limitations.push(`${path}: ${error instanceof FeedUrlRejectedError ? `URL rejected by SSRF protection (${error.reason}).` : "resource unavailable"}`);
      }
    }
  }
  const byCategory = Object.fromEntries(categories.map(c => [c, all.filter(i => i.category === c)])) as Record<AuditCategory, Issue[]>;
  const scores = Object.fromEntries(categories.map(c => { const deductions = byCategory[c].reduce((n, i) => n + ({ critical: 30, high: 18, medium: 9, low: 3, info: 0 }[i.severity]), 0); return [c, clamp(100 - deductions)]; })) as WebsiteAuditOutput["scores"];
  const priority = (s: Issue["severity"]) => all.filter(i => i.severity === s);
  const output = { overallScore: clamp(categories.reduce((n, c) => n + scores[c], 0) / categories.length), scores, criticalIssues: priority("critical"), highPriorityIssues: priority("high"), mediumPriorityIssues: priority("medium"), lowPriorityIssues: priority("low"), quickWins: all.filter(i => i.estimatedFixEffort === "low").slice(0, 10), seoIssues: byCategory.seo, performanceIssues: byCategory.performance, accessibilityIssues: byCategory.accessibility, securityFindings: byCategory.security, technicalIssues: byCategory.technical, uxIssues: byCategory.ux, pagesAudited: pages, estimatedFixHours: { min: Math.ceil(all.length * 0.5), max: Math.ceil(all.length * 2.5) }, confidenceScore: pages.some(p => p.status === 200) ? (pages.length > 1 ? 0.84 : 0.78) : 0.35, limitations };
  return websiteAuditOutput.parse(output);
}

export async function websiteAudit(raw: unknown) { return auditWebsite(raw); }
export async function previewWebsiteAudit(raw: unknown): Promise<CapabilityPreviewBody> { const input = websiteAuditInput.parse(raw); return { capability: "website_audit", status: "available", inputRecognized: true, preview: { availableSections: ["overallScore", "scores", "issueCounts", "topFindings"], dataCoverage: "medium", signals: { requestedCategories: input.auditTypes.length, maxPages: input.maxPages, passiveInspection: true, completeAuditWithheld: true } } }; }
