import { strategyPerformanceAnalysisInput, tradeRiskScoreInput, portfolioExposureCheckInput, tradeLogAnalysisInput, tradeRecord, positionRecord, type StrategyPerformanceAnalysisInput, type TradeRiskScoreInput, type PortfolioExposureCheckInput, type TradeLogAnalysisInput } from "../schemas/tradingAnalysisInputs.js";
import { strategyPerformanceAnalysisOutput, tradeRiskScoreOutput, portfolioExposureCheckOutput, tradeLogAnalysisOutput } from "../schemas/tradingAnalysisOutputs.js";

type Trade = ReturnType<typeof tradeRecord.parse>;
type Position = ReturnType<typeof positionRecord.parse>;
const round = (n: number, d = 4) => Number(n.toFixed(d));
const avg = (xs: number[]) => xs.length ? xs.reduce((a, b) => a + b, 0) / xs.length : null;
const pct = (n: number | null, d: number) => n === null || d === 0 ? null : round(n / d, 6);
const timestampNumber = (v: string | number | undefined) => v === undefined ? null : typeof v === "number" ? v : Date.parse(v) / 1000;
const dayKey = (v: string | number | undefined) => { const t = timestampNumber(v); return t === null || !Number.isFinite(t) ? null : new Date(t * 1000).toISOString().slice(0, 10); };
const provenance = {
  strategyPerformance: "MERGED" as const,
  tradeRisk: "MERGED" as const,
  portfolioExposure: "GROK" as const,
  tradeLog: "MERGED" as const,
  notes: [
    "GROK supplies fee-aware realized P&L, exposure limits, open-risk and ledger conventions.",
    "SIGNALFLOW supplies R-multiple outcomes, direction-aware stop/target rules, confidence/timeframe grouping and safe-leverage bands.",
    "NEW supplies deterministic aggregation, validation, anomaly detection and the 0-100 risk score orchestration."
  ]
};
function safeLeverageFor(stopDistancePct: number | null, timeframe?: string) {
  if (stopDistancePct === null || stopDistancePct <= 0) return null;
  const cap = timeframe && ["1m", "3m", "5m"].includes(timeframe) ? 0.015 : timeframe && ["15m", "30m", "1h"].includes(timeframe) ? 0.03 : timeframe && ["4h", "6h", "8h", "12h"].includes(timeframe) ? 0.06 : timeframe && ["1d", "daily", "1w"].includes(timeframe) ? 0.10 : null;
  if (cap !== null && stopDistancePct > cap) return 1;
  if (stopDistancePct <= 0.01) return 20;
  if (stopDistancePct <= 0.025) return 10;
  if (stopDistancePct <= 0.05) return 5;
  return 1;
}
function directionValid(direction: "long" | "short", entry: number, stop?: number, targets: number[] = []) {
  if (stop !== undefined && ((direction === "long" && stop >= entry) || (direction === "short" && stop <= entry))) return false;
  return targets.every(target => direction === "long" ? target > entry : target < entry);
}

function derivePnl(t: Trade): number | null {
  if (t.realizedPnl !== undefined) return t.realizedPnl - (t.fees ?? 0);
  if (t.entryPrice === undefined || t.exitPrice === undefined || t.quantity === undefined) return null;
  const sign = t.direction === "short" ? -1 : 1;
  return (t.exitPrice - t.entryPrice) * t.quantity * sign - (t.fees ?? 0);
}
function deriveGross(t: Trade): number | null {
  if (t.realizedPnl !== undefined) return t.realizedPnl;
  const pnl = derivePnl(t); return pnl === null ? null : pnl + (t.fees ?? 0);
}
function normalizeTrade(raw: unknown): Trade | null { const p = tradeRecord.safeParse(raw); return p.success ? p.data : null; }
function streaks(pnls: number[]) { let win = 0, loss = 0, maxWin = 0, maxLoss = 0; for (const p of pnls) { if (p > 0) { win++; loss = 0; maxWin = Math.max(maxWin, win); } else if (p < 0) { loss++; win = 0; maxLoss = Math.max(maxLoss, loss); } else { win = 0; loss = 0; } } return { maxWin, maxLoss }; }

export function analyzeStrategyPerformance(input: unknown) {
  const parsed: StrategyPerformanceAnalysisInput = strategyPerformanceAnalysisInput.parse(input);
  const trades = parsed.trades.filter(t => t.status !== "cancelled" && t.status !== "rejected");
  const pnls = trades.map(derivePnl).filter((x): x is number => x !== null);
  const gross = trades.map(deriveGross).filter((x): x is number => x !== null);
  const rMultiples = trades.map((t, i) => t.rMultiple ?? (parsed.riskPerTrade && pnls[i] !== undefined ? pnls[i]! / parsed.riskPerTrade : null));
  const outcomeValues = trades.map((t, i) => t.rMultiple ?? pnls[i] ?? null).filter((x): x is number => x !== null);
  const winners = outcomeValues.filter(x => x > 0), losers = outcomeValues.filter(x => x < 0), breakeven = outcomeValues.filter(x => x === 0);
  const net = pnls.length ? pnls.reduce((a, b) => a + b, 0) : null;
  const grossProfit = gross.filter(x => x > 0).reduce((a, b) => a + b, 0);
  const grossLoss = Math.abs(gross.filter(x => x < 0).reduce((a, b) => a + b, 0));
  const curve: number[] = []; let running = parsed.initialEquity ?? 0, peak = running, maxDd = 0;
  for (const p of pnls) { running += p; peak = Math.max(peak, running); maxDd = Math.max(maxDd, peak - running); curve.push(running); }
  const currentDd = curve.length ? Math.max(0, Math.max(...curve) - curve[curve.length - 1]!) : 0;
  const returns = parsed.initialEquity && parsed.initialEquity > 0 ? pnls.map(p => p / parsed.initialEquity!) : [];
  const mean = avg(returns); const variance = returns.length > 1 ? avg(returns.map(x => (x - mean!) ** 2))! : null; const vol = variance === null ? null : Math.sqrt(variance);
  const downside = returns.filter(x => x < 0); const downsideDev = downside.length ? Math.sqrt(avg(downside.map(x => x ** 2))!) : null;
  const assumption = ["Net P&L follows grok-trading-desk: price P&L less fees; supplied realizedPnl is treated as gross before fees."];
  if (pnls.length !== trades.length) assumption.push("Trades without both sides of a price or realizedPnl are excluded from numeric P&L metrics.");
  if (!parsed.initialEquity) assumption.push("Cumulative return, volatility, Sharpe, and Sortino require positive initialEquity and are null without it.");
  const byDay = new Map<string, number>(); for (const [i, t] of trades.entries()) { const d = dayKey(t.exitTime ?? t.entryTime); if (d && pnls[i] !== undefined) byDay.set(d, (byDay.get(d) ?? 0) + pnls[i]!); }
  const daily = [...byDay.entries()]; const best = daily.length ? daily.reduce((a, b) => b[1] > a[1] ? b : a) : null; const worst = daily.length ? daily.reduce((a, b) => b[1] < a[1] ? b : a) : null;
  const holds = trades.map(t => { const a = timestampNumber(t.entryTime), b = timestampNumber(t.exitTime); return a !== null && b !== null && b >= a ? b - a : null; }).filter((x): x is number => x !== null);
  const rValues = rMultiples.filter((x): x is number => x !== null); const rCurve: number[] = []; let rRunning = 0, rPeak = 0, maxDdR = 0; for (const r of rValues) { rRunning += r; rPeak = Math.max(rPeak, rRunning); maxDdR = Math.max(maxDdR, rPeak - rRunning); rCurve.push(rRunning); }
  const ss = streaks(outcomeValues); const dataQuality = { completeTradeCount: outcomeValues.length, incompleteTradeCount: trades.length - outcomeValues.length, warnings: trades.length !== pnls.length ? ["Some trades lack sufficient price/P&L fields; R-multiple records remain usable when supplied."] : [] };
  const metrics = { totalTrades: trades.length, winningTrades: winners.length, losingTrades: losers.length, breakevenTrades: breakeven.length, winRate: pct(winners.length, outcomeValues.length), lossRate: pct(losers.length, outcomeValues.length), grossProfit: pnls.length ? round(grossProfit) : null, grossLoss: pnls.length ? round(grossLoss) : null, netPnl: net === null ? null : round(net), averageWinningTrade: avg(pnls.filter(x => x > 0)), averageLosingTrade: avg(pnls.filter(x => x < 0)), largestWinner: pnls.length ? Math.max(...pnls) : null, largestLoser: pnls.length ? Math.min(...pnls) : null, profitFactor: grossLoss === 0 ? (grossProfit > 0 ? null : 0) : round(grossProfit / grossLoss), expectancyPerTrade: avg(pnls), averageRMultiple: avg(rValues), totalR: rValues.length ? round(rValues.reduce((a, b) => a + b, 0)) : null, maximumDrawdownR: rValues.length ? round(maxDdR) : null, cumulativeReturn: parsed.initialEquity && net !== null ? round(net / parsed.initialEquity) : null, maximumDrawdown: pnls.length ? round(maxDd) : null, currentDrawdown: pnls.length ? round(currentDd) : null, recoveryFactor: maxDd > 0 && net !== null ? round(net / maxDd) : null, sharpeRatio: vol && mean !== null && vol > 0 ? round(mean / vol * Math.sqrt(252)) : null, sortinoRatio: downsideDev && mean !== null && downsideDev > 0 ? round(mean / downsideDev * Math.sqrt(252)) : null, volatility: vol, averageHoldingPeriodSeconds: avg(holds), bestTradingDay: best?.[0] ?? null, worstTradingDay: worst?.[0] ?? null, maxConsecutiveWins: ss.maxWin, maxConsecutiveLosses: ss.maxLoss };
  return strategyPerformanceAnalysisOutput.parse({ metrics, performanceSummary: outcomeValues.length === 0 ? "No reliable closed-trade P&L or R-multiple outcome is available." : `${winners.length}/${outcomeValues.length} outcome records won; ${net === null ? `total R was ${rValues.length ? round(rValues.reduce((a, b) => a + b, 0)) : "not available"}` : `net P&L was ${round(net)}`}.`, strengths: [winners.length > losers.length && "Win rate exceeded loss rate.", grossLoss > 0 && grossProfit / grossLoss > 1.5 && "Profit factor exceeded 1.5."].filter(Boolean), weaknesses: [ss.maxLoss >= 3 && `Maximum losing streak was ${ss.maxLoss}.`, maxDd > 0 && net !== null && maxDd > Math.abs(net) && "Drawdown exceeded net P&L."].filter(Boolean), riskFlags: [grossLoss === 0 && winners.length > 0 && "Profit factor is undefined because no gross loss was recorded.", trades.length - pnls.length > 0 && "Some records were excluded from dollar P&L because prices/realizedPnl were missing."].filter(Boolean), dataQuality, calculationAssumptions: [...assumption, "When rMultiple is supplied, SignalFlow-style R outcomes determine win/loss counts and streaks; dollar metrics remain fee-aware GROK-style metrics."], methodology: ["R-multiple is authoritative for outcome classification when present; otherwise realized/derived P&L is used.", "Dollar P&L is gross price P&L less fees, matching GROK execution semantics.", "Maximum drawdown is calculated independently in dollars and R units from trade order."], sourceTraceability: provenance });
}

export function scoreTradeRisk(input: unknown) {
  const p: TradeRiskScoreInput = tradeRiskScoreInput.parse(input); const t = p.trade; const a = p.account ?? {}; const equity = a.accountEquity ?? a.accountBalance ?? null;
  const targets = t.takeProfits ?? (t.takeProfit === undefined ? [] : [t.takeProfit]); const stopDistance = t.stopLoss === undefined ? null : Math.abs(t.entryPrice - t.stopLoss); const validGeometry = directionValid(t.direction, t.entryPrice, t.stopLoss, targets); const targetDistance = targets.length ? Math.max(...targets.map(x => Math.abs(x - t.entryPrice))) : null; const riskAmount = stopDistance === null ? null : stopDistance * t.quantity; const rr = validGeometry && riskAmount && targetDistance !== null ? targetDistance * t.quantity / riskAmount : null; const exposure = t.entryPrice * t.quantity; const riskPct = equity && riskAmount !== null ? riskAmount / equity : null; const exposurePct = equity ? exposure / equity : null; const leverage = t.leverage ?? (a.accountBalance && a.accountBalance > 0 ? exposure / a.accountBalance : null); const stopDistancePct = stopDistance === null ? null : stopDistance / t.entryPrice; const safeLeverage = safeLeverageFor(stopDistancePct, t.timeframe);
  const components: Record<string, number> = {}; const riskFactors: string[] = [], positiveFactors: string[] = [], warnings: string[] = [], assumptions: string[] = []; let score = 0;
  if (riskPct === null) { score += 25; warnings.push("Account equity/balance is missing; account risk cannot be verified."); } else { components.accountRisk = Math.min(40, riskPct / 0.06 * 40); score += components.accountRisk; if (riskPct > 0.06) riskFactors.push("Account risk exceeds the grok-trading-desk 6% daily-loss threshold."); else positiveFactors.push("Account risk is within the 6% threshold."); }
  if (exposurePct !== null) { components.positionExposure = Math.min(25, exposurePct / (a.maxPositionPct ?? 0.30) * 25); score += components.positionExposure; if (exposurePct > (a.maxPositionPct ?? 0.30)) riskFactors.push("Position exposure exceeds the 30% default maximum position limit."); }
  if (rr === null) { score += 15; warnings.push(!validGeometry && targets.length ? "Stop-loss or take-profit is on the wrong side of entry for the trade direction." : "Stop-loss or take-profit is missing; risk/reward cannot be verified."); } else if (rr < 1) { score += 15; riskFactors.push("Risk/reward ratio is below 1:1."); } else { positiveFactors.push("Risk/reward ratio is at least 1:1."); }
  if (leverage !== null) { components.leverage = Math.min(15, Math.max(0, leverage - 1) / 4 * 15); score += components.leverage; if (safeLeverage !== null && leverage > safeLeverage) riskFactors.push(`Leverage exceeds the SignalFlow safe band of ${safeLeverage}x for this stop distance/timeframe.`); else if (leverage > 4) riskFactors.push("Leverage is high."); }
  if (t.volatilityPct !== undefined && stopDistance !== null && t.volatilityPct > 0 && stopDistance / t.entryPrice < t.volatilityPct) { score += 10; riskFactors.push("Stop distance is smaller than the supplied volatility indicator."); }
  if (t.liquidityScore !== undefined && t.liquidityScore < 0.4) { score += 10; riskFactors.push("Liquidity score indicates possible slippage."); }
  const concentration = p.existingPositions?.filter(x => x.symbol === (t.symbol ?? "")).reduce((s, x) => s + x.entryPrice * x.quantity, 0) ?? 0; if (equity && (concentration + exposure) / equity > 0.30) { score += 10; riskFactors.push("Symbol concentration exceeds 30% of equity."); }
  if (p.historicalRisk?.maxDrawdownPct !== undefined && p.historicalRisk.maxDrawdownPct < -0.20) { score += 5; riskFactors.push("Historical strategy drawdown exceeded 20%."); }
  if (equity === 0) { score = 100; warnings.push("Account equity is zero; trade cannot be risk-sized safely."); } if (t.stopLoss === undefined) assumptions.push("No stop-loss supplied; stop risk is not estimated.");
  const riskScore = Math.max(0, Math.min(100, Math.round(score))); const riskLevel = riskScore >= 75 ? "critical" : riskScore >= 50 ? "high" : riskScore >= 25 ? "moderate" : "low";
  return tradeRiskScoreOutput.parse({ riskScore, riskLevel, riskAmount, accountRiskPct: riskPct, riskRewardRatio: rr, positionExposurePct: exposurePct, leverage, safeLeverage, riskFactors, positiveFactors, warnings, calculationBreakdown: { components, thresholds: { maxPositionPct: a.maxPositionPct ?? 0.30, maxPortfolioRiskPct: a.maxPortfolioRiskPct ?? 0.50, maxDailyLossPct: a.maxDailyLossPct ?? 0.06, signalflowRiskPerTradePct: 0.01, signalflowSafeLeverage: safeLeverage ?? 0 }, assumptions: [...assumptions, "SignalFlow uses a 1% risk-per-trade sizing convention and direction-aware stop/target geometry."] }, sourceTraceability: provenance });
}

function exposureFor(p: Position) { return p.marketValue ?? p.entryPrice * p.quantity; }
export function checkPortfolioExposure(input: unknown) {
  const p: PortfolioExposureCheckInput = portfolioExposureCheckInput.parse(input); const all = p.proposedPosition ? [...p.positions, p.proposedPosition] : p.positions; const equity = p.account?.accountEquity ?? p.account?.accountBalance ?? null; const longExposure = all.filter(x => x.direction === "long").reduce((s, x) => s + exposureFor(x), 0); const shortExposure = all.filter(x => x.direction === "short").reduce((s, x) => s + exposureFor(x), 0); const gross = longExposure + shortExposure; const bySymbol = new Map<string, number>(); for (const x of all) bySymbol.set(x.symbol, (bySymbol.get(x.symbol) ?? 0) + exposureFor(x)); const openRisk = all.reduce((s, x) => s + (x.stopLoss === undefined ? 0 : Math.abs(x.entryPrice - x.stopLoss) * x.quantity), 0); const positions = all.map(x => ({ symbol: x.symbol, direction: x.direction, exposure: round(exposureFor(x)), concentrationPct: equity ? round(exposureFor(x) / equity) : null, openRisk: x.stopLoss === undefined ? null : round(Math.abs(x.entryPrice - x.stopLoss) * x.quantity) })); const largest = equity ? Math.max(...[...bySymbol.values(), 0]) / equity : null; const flags: string[] = [], riskFlags: string[] = []; if (equity === 0) riskFlags.push("Account equity is zero; exposure ratios are unavailable."); else if (equity === null) riskFlags.push("Account equity/balance is missing; exposure ratios are unavailable."); if (largest !== null && largest > 0.30) flags.push("A symbol exceeds 30% concentration."); if (equity && gross / equity > (p.account?.maxPortfolioRiskPct ?? 0.50)) flags.push("Gross exposure exceeds the 50% default portfolio cap."); if (longExposure > 0 && shortExposure === 0) riskFlags.push("Portfolio is fully long."); if (shortExposure > 0 && longExposure === 0) riskFlags.push("Portfolio is fully short."); if (all.some(x => x.stopLoss === undefined)) riskFlags.push("One or more positions lack a stop-loss, so open risk is understated."); const marginUsed = p.account?.marginUsed ?? all.reduce((s, x) => s + (x.margin ?? (x.leverage && x.leverage > 0 ? exposureFor(x) / x.leverage : 0)), 0); return portfolioExposureCheckOutput.parse({ grossExposure: round(gross), netExposure: round(longExposure - shortExposure), longExposure: round(longExposure), shortExposure: round(shortExposure), exposurePctOfEquity: equity ? round(gross / equity) : null, largestConcentrationPct: largest === null ? null : round(largest), leverage: equity && equity > 0 ? round(gross / equity) : null, positions, concentrationFlags: flags, riskFlags, summary: `Portfolio has ${all.length} position(s), gross exposure ${round(gross)} and net exposure ${round(longExposure - shortExposure)}.`, accountEquity: equity, openRisk: round(openRisk), marginUsage: equity ? round(marginUsed / equity) : null, availableFreeMargin: p.account?.availableMargin ?? (equity === null ? null : round(Math.max(0, equity - marginUsed)) ), sourceTraceability: provenance });
}

function groupTrades(trades: Trade[], key: (t: Trade) => string) { const m = new Map<string, Trade[]>(); for (const t of trades) { const k = key(t); (m.get(k) ?? (m.set(k, []), m.get(k)!)).push(t); } return [...m.entries()].sort((a, b) => a[0].localeCompare(b[0])).map(([key, xs]) => { const ps = xs.map(derivePnl).filter((x): x is number => x !== null); const outcomes = xs.map((x, i) => x.rMultiple ?? ps[i] ?? null).filter((x): x is number => x !== null); const fees = xs.reduce((s, x) => s + (x.fees ?? 0), 0); return { key, trades: xs.length, wins: outcomes.filter(x => x > 0).length, losses: outcomes.filter(x => x < 0).length, netPnl: ps.length ? round(ps.reduce((a, b) => a + b, 0)) : null, fees: round(fees), winRate: pct(outcomes.filter(x => x > 0).length, outcomes.length) }; }); }
export function analyzeTradeLog(input: unknown) {
  const p: TradeLogAnalysisInput = tradeLogAnalysisInput.parse(input); const valid: Trade[] = [], malformed = [], ids = new Map<string, number>(); let previous: number | null = null, outOfOrder = 0, missingPrices = 0;
  for (const raw of p.records) { const t = normalizeTrade(raw); if (!t) { malformed.push(raw); continue; } valid.push(t); if (t.tradeId) ids.set(t.tradeId, (ids.get(t.tradeId) ?? 0) + 1); const ts = timestampNumber(t.entryTime); if (ts !== null && previous !== null && ts < previous) outOfOrder++; if (ts !== null) previous = ts; if (t.entryPrice === undefined || (t.status === "closed" && t.exitPrice === undefined && t.realizedPnl === undefined)) missingPrices++; }
  const closed = valid.filter(t => t.status === "closed" || t.exitTime !== undefined || t.realizedPnl !== undefined); const open = valid.filter(t => !closed.includes(t)); const pnls = closed.map(derivePnl).filter((x): x is number => x !== null); const outcomes = closed.map((t, i) => t.rMultiple ?? pnls[i] ?? null).filter((x): x is number => x !== null); const ss = streaks(outcomes); const holds = closed.map(t => { const a = timestampNumber(t.entryTime), b = timestampNumber(t.exitTime); return a !== null && b !== null && b >= a ? b - a : null; }).filter((x): x is number => x !== null); const dup = [...ids.entries()].filter(([, n]) => n > 1).map(([id]) => id); const dataQuality = { completeTradeCount: valid.length - missingPrices, incompleteTradeCount: malformed.length + missingPrices, warnings: [...(malformed.length ? ["Malformed records were excluded."] : []), ...(outOfOrder ? ["Timestamps were out of order."] : [])] }; const repeatedLosses = outcomes.filter(x => x < 0).length >= 3 ? ["Repeated losses are present."] : []; const excessiveFees = p.records.length && closed.reduce((s, t) => s + (t.fees ?? 0), 0) > Math.abs(pnls.reduce((s, x) => s + x, 0)) * 0.2 ? ["Fees exceed 20% of absolute net P&L."] : []; return tradeLogAnalysisOutput.parse({ summary: { totalTrades: valid.length, closedTrades: closed.length, openTrades: open.length, wins: outcomes.filter(x => x > 0).length, losses: outcomes.filter(x => x < 0).length, netPnl: pnls.length ? round(pnls.reduce((a, b) => a + b, 0)) : null, fees: round(valid.reduce((s, t) => s + (t.fees ?? 0), 0)), maxWinningStreak: ss.maxWin, maxLosingStreak: ss.maxLoss, averageHoldingDurationSeconds: avg(holds) }, performanceBySymbol: groupTrades(closed, t => t.symbol), performanceByStrategy: groupTrades(closed, t => t.strategy ?? "unknown"), performanceBySession: groupTrades(closed, t => t.session ?? "unknown"), executionMetrics: { completeRecords: valid.length, malformedRecords: malformed.length, duplicateTradeIds: dup, outOfOrderTimestamps: outOfOrder, missingPrices }, behavioralPatterns: [...repeatedLosses, ...(valid.length > 20 && pnls.length / valid.length > 0.8 ? ["High trading frequency detected; review for overtrading."] : [])], anomalies: [...(dup.length ? ["Duplicate trade IDs detected."] : []), ...excessiveFees, ...(outOfOrder ? ["Out-of-order timestamps detected."] : [])], riskFlags: [...(closed.some(t => t.stopLoss === undefined) ? ["Some closed trades have no stop-loss field."] : []), ...(open.length ? ["Open and closed trades are mixed in this log."] : [])], dataQuality, sourceTraceability: provenance });
}
