import { safeFeedFetch, validateFeedUrl, FeedFetchError, FeedUrlRejectedError, type HostResolver } from "./security.js";
import { buildAnalysis } from "./extraction.js";

export const SCHEMA_VERSION = "1.0";
export type AnalyzerInput = { websiteUrl: string; maxPages?: number; maxDepth?: number; includeBusinessAnalysis?: boolean; includeTechnology?: boolean; includeSEO?: boolean; includeSalesIntelligence?: boolean; includeContacts?: boolean; includeSocialProfiles?: boolean; includePricing?: boolean; includeOpportunities?: boolean; sameDomainOnly?: boolean; language?: "auto" | "en" | "ar" | "other" };
export type Page = { url: string; depth: number; html: string; status: number; headers: Headers; title: string | null; text: string; links: string[] };
type Evidence = { url: string; text: string };
type Finding = { value: string; confidence: number; evidence: Evidence[] };
export type AnalyzerErrorCode = "INVALID_URL" | "PRIVATE_NETWORK_URL" | "DNS_ERROR" | "CONNECTION_FAILED" | "TIMEOUT" | "ROBOTS_BLOCKED" | "UNSUPPORTED_CONTENT" | "NO_USEFUL_CONTENT" | "CRAWL_FAILED";
export class AnalyzerError extends Error { constructor(readonly code: AnalyzerErrorCode, message: string) { super(message); this.name = "AnalyzerError"; } }
export type AnalyzerOptions = { fetchImpl?: typeof fetch; resolver?: HostResolver; timeoutMs?: number; maxResponseBytes?: number; now?: () => string };

const defaults = { maxPages: 15, maxDepth: 2, includeBusinessAnalysis: true, includeTechnology: true, includeSEO: true, includeSalesIntelligence: true, includeContacts: true, includeSocialProfiles: true, includePricing: true, includeOpportunities: true, sameDomainOnly: true, language: "auto" as const };
const blocked = /\b(?:login|logout|sign[-_ ]?in|sign[-_ ]?up|account|cart|checkout|privacy|terms|cookie|wp-admin|feed|comments)\b/i;
const businessPaths = ["/", "/about", "/about-us", "/company", "/services", "/products", "/solutions", "/pricing", "/plans", "/contact", "/customers", "/clients", "/industries", "/features", "/partners", "/case-studies", "/blog"];
const clean = (v: string) => v.replace(/\s+/g, " ").trim();
const decode = (v: string) => clean(v.replace(/&amp;/g, "&").replace(/&quot;/g, '"').replace(/&#39;/g, "'").replace(/<[^>]+>/g, " "));
const attr = (html: string, tag: string, name: string) => new RegExp(`<${tag}\\b[^>]*\\b${name}\\s*=\\s*["']([^"']*)`, "i").exec(html)?.[1] ?? null;
const attrAll = (html: string, tag: string, name: string) => [...html.matchAll(new RegExp(`<${tag}\\b[^>]*\\b${name}\\s*=\\s*["']([^"']*)`, "gi"))].map(m => decode(m[1]!));
const visible = (html: string) => decode(html.replace(/<script[\s\S]*?<\/script>/gi, " ").replace(/<style[\s\S]*?<\/style>/gi, " ").replace(/<noscript[\s\S]*?<\/noscript>/gi, " ").replace(/<[^>]+>/g, " ")).slice(0, 12000);
const snippet = (text: string, term?: RegExp) => { const s = term ? text.match(new RegExp(`.{0,70}${term.source}.{0,100}`, term.flags.replace("g", "i")))?.[0] : text.slice(0, 180); return clean(s ?? text.slice(0, 180)).slice(0, 220); };
const uniq = <T>(items: T[], key: (x: T) => string = x => String(x)) => [...new Map(items.map(x => [key(x).toLowerCase(), x])).values()];
const finding = (value: string, page: Page, confidence = 0.8, term?: RegExp): Finding => ({ value, confidence, evidence: [{ url: page.url, text: snippet(page.text, term) }] });

export function normalizeInput(raw: unknown): Required<AnalyzerInput> {
  if (!raw || typeof raw !== "object" || Array.isArray(raw)) throw new AnalyzerError("INVALID_URL", "Input must be an object.");
  const r = raw as Record<string, unknown>; if (typeof r.websiteUrl !== "string" || !r.websiteUrl.trim()) throw new AnalyzerError("INVALID_URL", "websiteUrl is required.");
  const rawUrl = r.websiteUrl.trim(); if (/^[a-z][a-z\d+.-]*:/i.test(rawUrl) && !/^https?:\/\//i.test(rawUrl)) throw new AnalyzerError("INVALID_URL", "Only public http(s) URLs are supported.");
  let u: URL; try { u = new URL(rawUrl.match(/^https?:\/\//i) ? rawUrl : `https://${rawUrl}`); } catch { throw new AnalyzerError("INVALID_URL", "websiteUrl must be a valid public http(s) URL."); }
  if (!['http:', 'https:'].includes(u.protocol) || u.username || u.password) throw new AnalyzerError("INVALID_URL", "Only public http(s) URLs without credentials are supported.");
  u.hash = ""; u.search = "";
  const n = { ...defaults, ...r, websiteUrl: u.toString() } as Required<AnalyzerInput>;
  if (!Number.isInteger(n.maxPages) || n.maxPages < 1 || n.maxPages > 50 || !Number.isInteger(n.maxDepth) || n.maxDepth < 0 || n.maxDepth > 5) throw new AnalyzerError("INVALID_URL", "maxPages must be 1–50 and maxDepth must be 0–5.");
  return n;
}

function canonical(raw: string, base: URL, sameDomain: boolean): string | null { try { const u = new URL(raw, base); if (!['http:', 'https:'].includes(u.protocol) || u.username || u.password) return null; if (sameDomain && u.hostname.toLowerCase() !== base.hostname.toLowerCase()) return null; u.hash = ""; for (const k of [...u.searchParams.keys()]) if (/^(utm_|fbclid|gclid|ref|source)/i.test(k)) u.searchParams.delete(k); if ([...u.searchParams].length) return null; if (/\.(?:pdf|zip|png|jpe?g|gif|svg|webp|mp4|mp3|docx?|xlsx?|pptx?)$/i.test(u.pathname)) return null; return u.toString(); } catch { return null; } }
function priority(url: string, depth: number, root: URL) { const path = new URL(url).pathname.toLowerCase(); const i = businessPaths.indexOf(path); return (i >= 0 ? 100 - i : 25) - depth * 12 - (blocked.test(path) ? 200 : 0) + (new URL(url).hostname === root.hostname ? 10 : 0); }
export function prioritizeUrls(urls: string[], root: URL, depth = 0) { return [...urls].sort((a, b) => priority(b, depth, root) - priority(a, depth, root)); }

function extractLinks(html: string, pageUrl: string, root: URL, sameDomain: boolean) { return uniq(attrAll(html, "a", "href").map(h => canonical(h, new URL(pageUrl), sameDomain)).filter((x): x is string => Boolean(x) && !blocked.test(x!)), x => x); }
function pagesText(pages: Page[]) { return pages.map(p => p.text).join(" "); }
function allEvidence(pages: Page[], regex: RegExp, limit = 5) { const out: Evidence[] = []; for (const p of pages) { if (regex.test(p.text)) out.push({ url: p.url, text: snippet(p.text, regex) }); if (out.length >= limit) break; } return out; }
function detectList(pages: Page[], regex: RegExp) { return uniq(pages.flatMap(p => p.text.match(regex)?.slice(0, 12) ?? []).map(clean).filter(x => x.length > 2 && x.length < 120)); }
function confidence(count: number, corroboration = 0) { return Math.min(0.98, 0.55 + Math.min(0.3, count * 0.08) + Math.min(0.12, corroboration * 0.04)); }

function analyzePages(input: Required<AnalyzerInput>, pages: Page[], root: URL) {
  const text = pagesText(pages); const home = pages[0]; const title = home ? decode(/<title\b[^>]*>([\s\S]*?)<\/title>/i.exec(home.html)?.[1] ?? "") || null : null;
  const description = home ? /<meta\b[^>]*name=["']description["'][^>]*content=["']([^"']*)/i.exec(home.html)?.[1] ?? /<meta\b[^>]*content=["']([^"']*)["'][^>]*name=["']description["']/i.exec(home.html)?.[1] ?? null : null;
  const jsonLd = pages.flatMap(p => [...p.html.matchAll(/<script[^>]+type=["']application\/ld\+json["'][^>]*>([\s\S]*?)<\/script>/gi)].map(m => { try { return JSON.parse(m[1]!); } catch { return null; } })).filter(Boolean) as Record<string, unknown>[];
  const org = jsonLd.find(x => ["Organization", "Corporation", "LocalBusiness"].includes(String(x["@type"]))) ?? {};
  const orgPage = pages.find(p => /about|company|contact/i.test(p.url)) ?? home;
  const companyName = typeof org.name === "string" ? finding(org.name, orgPage!, 0.95, /company|organization/i) : title ? finding(title.split(/[|–—-]/)[0]!.trim(), home!, 0.7) : { value: null, confidence: 0, evidence: [] };
  const desc = typeof org.description === "string" ? finding(org.description, orgPage!, 0.9) : description ? finding(decode(description), home!, 0.85) : text ? finding(snippet(text), home!, 0.45) : { value: null, confidence: 0, evidence: [] };
  const products = uniq(pages.flatMap(p => [...p.html.matchAll(/<(?:h2|h3)[^>]*>([\s\S]*?)<\/(?:h2|h3)>/gi)].map(m => ({ name: decode(m[1]!), url: p.url })).filter(x => x.name.length > 2 && x.name.length < 100 && /product|solution|platform|software|service|offer/i.test(`${p.url} ${x.name}`))), x => x.name).slice(0, 30).map(x => ({ ...x, description: null, category: null, pricingDetected: /\$|€|£|pricing|plan/i.test(pages.find(p => p.url === x.url)?.text ?? "") }));
  const services = detectList(pages, /(?:consulting|implementation|support|training|design|development|marketing|managed services|advisory)[^.!?]{0,70}/gi).slice(0, 20);
  const hrefs = attrAll(pages.map(p => p.html).join(" "), "a", "href");
  const emails = uniq([...text.matchAll(/[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,}/gi)].map(m => m[0].toLowerCase()).concat(hrefs.filter(x => /^mailto:/i.test(x)).map(x => x.replace(/^mailto:/i, "").split(/[?#]/)[0]!.toLowerCase())).filter(x => !/example\.|\.png|\.jpg/.test(x)));
  const phones = uniq([...text.matchAll(/(?:\+?\d[\d ()\-.]{7,}\d)/g)].map(m => clean(m[0])).filter(x => x.replace(/\D/g, "").length >= 8 && x.replace(/\D/g, "").length <= 15));
  const addresses = uniq(pages.flatMap(p => [...p.html.matchAll(/<address[^>]*>([\s\S]*?)<\/address>/gi)].map(m => decode(m[1]!)))).slice(0, 10);
  const socials: Record<string, string[]> = {}; for (const href of hrefs) { const match = href.match(/https?:\/\/[^/]*(linkedin\.com|twitter\.com|x\.com|facebook\.com|instagram\.com|youtube\.com|tiktok\.com|github\.com)[^\s"']*/i); if (match) { const key = match[1]!.split('.')[0] === 'twitter' ? 'x' : match[1]!.split('.')[0]!; (socials[key] ??= []).push(href.split(/[?#]/)[0]!); } } for (const k of Object.keys(socials)) socials[k] = uniq(socials[k]!);
  const priceText = /(?:pricing|plans?|per month|monthly|annual|free trial|contact (?:us )?for pricing|enterprise)/i; const pricingPage = pages.find(p => /pricing|plans/i.test(p.url)); const prices = detectList(pages, /(?:[$€£]\s?\d[\d,.]*|\d[\d,.]*\s?(?:USD|EUR|GBP|OMR|AED))/gi).slice(0, 20);
  const ctaRe = /(?:contact us|book (?:a )?demo|request (?:a )?demo|start (?:a )?trial|sign up|get started|buy now|get (?:a )?quote|call us|whatsapp|subscribe)/gi; const ctas = detectList(pages, ctaRe).slice(0, 20); const conversion = { primaryCTA: ctas[0] ?? null, ctas, contactForm: pages.some(p => /<form\b/i.test(p.html)), demoAvailable: /demo/i.test(text), signupAvailable: /sign[ -]?up|create account/i.test(text), freeTrialAvailable: /free trial/i.test(text), liveChatDetected: /intercom|drift|zendesk|tawk\.to|livechat/i.test(text), whatsappDetected: /wa\.me|whatsapp/i.test(text) };
  const tech: Record<string, { name: string; evidence: Evidence[]; confidence: number }[]> = {}; const techRules: [string, string, RegExp][] = [["CMS", "WordPress", /wp-content|wordpress/i], ["E-commerce", "Shopify", /cdn\.shopify|shopify\.com/i], ["Frontend framework", "Next.js", /__next|_next\/static/i], ["Frontend framework", "React", /react(?:\.production)?\.min|data-reactroot/i], ["Frontend framework", "Vue", /vue(?:\.runtime)?\.min|data-v-[a-f0-9]/i], ["Analytics", "Google Analytics", /google-analytics|gtag\(|googletagmanager/i], ["Tag manager", "Google Tag Manager", /googletagmanager/i], ["CRM/marketing", "HubSpot", /js\.hs-scripts\.com|hubspot/i], ["CRM/marketing", "Salesforce", /salesforce/i], ["Payments", "Stripe", /js\.stripe\.com|stripe/i], ["CDN/hosting", "Cloudflare", /cloudflare/i], ["Chat/support", "Intercom", /intercom/i]]; for (const [category, name, re] of techRules) if (re.test(pages.map(p => `${p.html} ${[...p.headers].map(x => x.join(':')).join(' ')}`).join(' '))) (tech[category] ??= []).push({ name, evidence: allEvidence(pages, re, 2), confidence: 0.88 });
  const seo = { titlePresent: pages.some(p => Boolean(attr(p.html, "title", "") || /<title[ >]/i.test(p.html))), metaDescriptionPresent: pages.some(p => /<meta[^>]+name=["']description/i.test(p.html)), canonicalPresent: pages.some(p => /<link[^>]+rel=["'][^"']*canonical/i.test(p.html)), structuredDataDetected: jsonLd.length > 0, sitemapDetected: false, robotsTxtDetected: false, h1Present: pages.some(p => /<h1\b/i.test(p.html)), mobileFriendlySignals: pages.some(p => /<meta[^>]+name=["']viewport/i.test(p.html)), issues: [] as string[] }; if (!seo.titlePresent) seo.issues.push("Missing title"); if (!seo.metaDescriptionPresent) seo.issues.push("Missing meta description"); if (!seo.h1Present) seo.issues.push("Missing H1"); if (!seo.canonicalPresent) seo.issues.push("Missing canonical"); if (!seo.structuredDataDetected) seo.issues.push("No structured data detected");
  const businessModel = { type: [] as string[], customerType: [] as string[], revenueModel: [] as string[], targetCustomers: detectList(pages, /(?:for|serving|helping) [^.!?]{3,70}/gi).slice(0, 12), targetIndustries: [] as string[], geographicMarkets: detectList(pages, /(?:serving|available in|locations? in|based in) [^.!?]{2,60}/gi).slice(0, 12) }; if (/shop|cart|add to cart|buy now/i.test(text)) businessModel.type.push("E-commerce"); if (/software|platform|saas|api/i.test(text)) businessModel.type.push("SaaS"); if (/consulting|agency|services|advisory/i.test(text)) businessModel.type.push("Professional Services"); if (/enterprise|businesses|organizations|b2b/i.test(text)) businessModel.customerType.push("B2B"); if (/consumer|for families|for individuals|b2c/i.test(text)) businessModel.customerType.push("B2C"); if (/subscription|per month|annual plan/i.test(text)) businessModel.revenueModel.push("Subscription"); if (/free trial|freemium/i.test(text)) businessModel.revenueModel.push("Freemium"); if (/contact (?:us )?for pricing|request a quote/i.test(text)) businessModel.revenueModel.push("Direct Sales");
  const signals = { pricingVisible: priceText.test(text), freeTrial: /free trial/i.test(text), demoAvailable: conversion.demoAvailable, enterpriseOffering: /enterprise/i.test(text), customerLogosDetected: /customer logos?|trusted by|our clients/i.test(text), caseStudiesDetected: /case stud(?:y|ies)/i.test(text), testimonialsDetected: /testimonial|what our clients say/i.test(text), blogDetected: pages.some(p => /\/blog(?:\/|$)/i.test(p.url)), careersDetected: /career|jobs|join our team/i.test(text), multipleLanguagesDetected: /hreflang|العربية|english|français|español/i.test(text) };
  const deductions = { seo: 0, conversion: 0, quality: 0, clarity: 0, maturity: 0 }; deductions.seo = (seo.titlePresent?0:20)+(seo.metaDescriptionPresent?0:15)+(seo.canonicalPresent?0:10)+(seo.structuredDataDetected?0:15)+(seo.h1Present?0:10)+(seo.mobileFriendlySignals?0:10)+(seo.robotsTxtDetected?0:10)+(seo.sitemapDetected?0:10); deductions.conversion = Math.max(0, 100 - (ctas.length?35:0) - (conversion.contactForm?20:0) - (conversion.demoAvailable?15:0) - (conversion.signupAvailable?15:0) - (conversion.whatsappDetected?5:0)); deductions.quality = Math.max(0, 100 - Math.min(80, (seo.issues.length * 10) + (text.length < 250 ? 25 : 0))); deductions.clarity = Math.max(0, 100 - (companyName.value ? 0 : 40) - (desc.value ? 0 : 35) - (businessModel.type.length ? 0 : 25)); deductions.maturity = Math.max(0, 100 - (signals.customerLogosDetected?0:15) - (signals.caseStudiesDetected?0:15) - (signals.pricingVisible?0:15) - (signals.blogDetected?0:10) - (signals.careersDetected?0:10) - (Object.keys(tech).length?0:20));
  const scores = { websiteQuality: Math.round(deductions.quality), businessClarity: Math.round(deductions.clarity), conversionReadiness: Math.round(deductions.conversion), seoReadiness: Math.round(100 - deductions.seo), digitalMaturity: Math.round(deductions.maturity) };
  const opportunities: { type: string; priority: "high"|"medium"|"low"; finding: string; recommendation: string; evidence: Evidence[] }[] = []; const addOpp = (type: string, priority: "high"|"medium"|"low", findingText: string, recommendation: string, re: RegExp) => opportunities.push({ type, priority, finding: findingText, recommendation, evidence: allEvidence(pages, re, 2) }); if (!ctas.length) addOpp("conversion", "high", "No clear primary CTA detected", "Add a prominent, specific contact, demo, quote, or signup path.", /./); if (!conversion.contactForm && !conversion.signupAvailable) addOpp("conversion", "medium", "No contact form or self-service signup detected", "Consider a low-friction lead capture or signup flow.", /./); if (!seo.metaDescriptionPresent || !seo.structuredDataDetected) addOpp("seo", "medium", "Basic SEO metadata is incomplete", "Add missing metadata and relevant Organization/Product structured data.", /./); if (!signals.multipleLanguagesDetected) addOpp("marketing", "low", "No multilingual signal detected", "Assess whether localized pages would support target markets.", /./); if (!Object.keys(tech).some(k => /CRM/.test(k))) addOpp("automation", "low", "No detectable CRM or marketing automation signal", "Review lead routing and CRM integration opportunities; detection is not proof of absence.", /./);
  const sales = { potentialNeeds: opportunities.map(o => o.finding), salesAngles: opportunities.filter(o => o.type === "conversion" || o.type === "automation").map(o => o.recommendation), technologyOpportunities: !Object.keys(tech).length ? ["Technology stack is not detectable from public HTML; qualify integration needs."] : [], marketingOpportunities: opportunities.filter(o => o.type === "seo" || o.type === "marketing").map(o => o.recommendation), automationOpportunities: opportunities.filter(o => o.type === "automation").map(o => o.recommendation) };
  return { company: { name: companyName, domain: root.hostname, description: desc, industry: null, subIndustry: null, country: null, city: null, founded: null }, businessModel, products, services, pricing: { pricingPageDetected: Boolean(pricingPage), pricingUrl: pricingPage?.url ?? null, freeTrial: conversion.freeTrialAvailable, freemium: /freemium/i.test(text), contactForPricing: /contact (?:us )?for pricing|request a quote/i.test(text), plans: prices }, contacts: { emails, phones, addresses, contactPage: pages.find(p => /contact/i.test(p.url))?.url ?? null }, socialProfiles: socials, technology: tech, seo, conversion, businessSignals: signals, scores, opportunities: input.includeOpportunities ? opportunities : [], salesIntelligence: sales, crawl: { pagesAnalyzed: pages.length, urls: pages.map(p => p.url) }, confidence: confidence(pages.length, [companyName.value, desc.value].filter(Boolean).length), generatedAt: (input as any)._now ?? new Date().toISOString() };
}

export async function analyzeWebsite(raw: unknown, options: AnalyzerOptions = {}) {
  const input = normalizeInput(raw); const resolver = options.resolver; const root = new URL(input.websiteUrl); let rootValidated: URL; try { rootValidated = await validateFeedUrl(root.toString(), { resolver }); } catch (e) { const code = e instanceof FeedUrlRejectedError ? "PRIVATE_NETWORK_URL" : "DNS_ERROR"; throw new AnalyzerError(code, e instanceof Error ? e.message : "Website URL could not be validated."); }
  const queue: { url: string; depth: number; discovered: boolean }[] = [{ url: rootValidated.toString(), depth: 0, discovered: true }]; const queued = new Set(queue.map(x => x.url)); const pages: Page[] = []; const failures: { url: string; code: AnalyzerErrorCode; message: string }[] = [];
  while (queue.length && pages.length < input.maxPages) { queue.sort((a,b) => Number(b.discovered) - Number(a.discovered) || priority(b.url,b.depth,root)-priority(a.url,a.depth,root)); const item = queue.shift()!; try { const fetched = await safeFeedFetch(item.url, { timeoutMs: options.timeoutMs ?? 8000, maxResponseBytes: options.maxResponseBytes ?? 1_500_000, maxRedirects: 3, fetchImpl: options.fetchImpl, resolver, truncateAtLimit: true }); if (!(fetched.contentType ?? "").toLowerCase().includes("text/html") && !/<html\b/i.test(fetched.body)) throw new AnalyzerError("UNSUPPORTED_CONTENT", "Response is not HTML."); const final = canonical(fetched.finalUrl, root, input.sameDomainOnly); if (!final) throw new AnalyzerError("PRIVATE_NETWORK_URL", "Redirected outside the allowed domain."); const p: Page = { url: final, depth: item.depth, html: fetched.body, status: fetched.status, headers: fetched.headers, title: null, text: visible(fetched.body), links: [] }; p.links = extractLinks(p.html, p.url, root, input.sameDomainOnly); pages.push(p); if (item.depth < input.maxDepth) { for (const url of p.links) if (!queued.has(url)) { queued.add(url); queue.push({ url, depth: item.depth + 1, discovered: true }); } if (item.depth === 0) for (const path of businessPaths.slice(1)) { const url = canonical(path, root, input.sameDomainOnly); if (url && !queued.has(url)) { queued.add(url); queue.push({ url, depth: 1, discovered: false }); } } } } catch (e) { const code = e instanceof AnalyzerError ? e.code : e instanceof FeedUrlRejectedError ? "PRIVATE_NETWORK_URL" : e instanceof FeedFetchError ? (e.kind === "timeout" ? "TIMEOUT" : "CONNECTION_FAILED") : "CRAWL_FAILED"; failures.push({ url: item.url, code, message: e instanceof Error ? e.message : String(e) }); } }
  if (!pages.length) { const first = failures[0]; throw new AnalyzerError(first?.code ?? "NO_USEFUL_CONTENT", first?.message ?? "No useful HTML content was found."); }
  const output = buildAnalysis(input, pages, root);
  for (const [path, key] of [["/robots.txt", "robotsTxtDetected"], ["/sitemap.xml", "sitemapDetected"]] as const) { try { const aux = await safeFeedFetch(new URL(path, root).toString(), { timeoutMs: options.timeoutMs ?? 8000, maxResponseBytes: 100_000, maxRedirects: 2, fetchImpl: options.fetchImpl, resolver }); output.seo[key] = aux.status >= 200 && aux.status < 400; } catch { output.seo[key] = false; } }
  output.scores.seoReadiness = Math.min(95, Math.max(0, 100 - (output.seo.titlePresent ? 0 : 20) - (output.seo.metaDescriptionPresent ? 0 : 15) - (output.seo.canonicalPresent ? 0 : 10) - (output.seo.structuredDataDetected ? 0 : 15) - (output.seo.h1Present ? 0 : 10) - (output.seo.mobileFriendlySignals ? 0 : 10) - (output.seo.robotsTxtDetected ? 0 : 10) - (output.seo.sitemapDetected ? 0 : 10)));
  output.scores.scoreDiagnostics.seoReadiness.score = output.scores.seoReadiness;
  if (!input.includeTechnology) output.technology = {};
  if (!input.includeContacts) output.contacts = { emails: [], phones: [], addresses: [], contactPage: null };
  if (!input.includeSocialProfiles) output.socialProfiles = {};
  if (!input.includePricing) output.pricing = { pricingPageDetected: false, pricingUrl: null, freeTrial: false, freemium: false, contactForPricing: false, plans: [] };
  if (!input.includeSalesIntelligence) output.salesIntelligence = { potentialNeeds: [], salesAngles: [], technologyOpportunities: [], marketingOpportunities: [], automationOpportunities: [], technologyDetectionState: { CRM: "UNKNOWN", ERP: "UNKNOWN", marketingAutomation: "UNKNOWN", analytics: "UNKNOWN" } };
  if (!input.includeBusinessAnalysis) { output.businessModel = { type: [], primaryBusinessModel: [], secondaryBusinessModels: [], customerType: [], revenueModel: [], targetCustomers: [], targetIndustries: [], geographicMarkets: [], supportingServices: [] }; output.products = []; output.services = []; }
  if (!input.includeSEO) output.seo = { titlePresent: false, metaDescriptionPresent: false, canonicalPresent: false, structuredDataDetected: false, sitemapDetected: false, robotsTxtDetected: false, h1Present: false, mobileFriendlySignals: false, issues: [] };
  return { schemaVersion: SCHEMA_VERSION, success: true, input: { websiteUrl: input.websiteUrl, maxPages: input.maxPages, maxDepth: input.maxDepth }, ...output, crawl: { ...output.crawl, failures } };
}
