export type ExtractionPage = { url: string; html: string; text: string; headers: Headers };
type Evidence = { url: string; text: string };
type Finding = { value: string | null; confidence: number; evidence: Evidence[] };
const clean = (v: string) => v.replace(/[\u0000-\u001f\u007f]/g, " ").replace(/\s+/g, " ").trim();
export const decodeHtml = (v: string) => clean(v.replace(/&(?:amp|#38);/gi, "&").replace(/&nbsp;/gi, " ").replace(/&quot;/gi, '"').replace(/&#39;|&apos;|&#x27;/gi, "'").replace(/&lt;/gi, "<").replace(/&gt;/gi, ">").replace(/&#x([0-9a-f]+);/gi, (_, x) => String.fromCodePoint(Number.parseInt(x, 16))).replace(/&#(\d+);/g, (_, x) => String.fromCodePoint(Number(x))));
const attrAll = (html: string, tag: string, name: string) => [...html.matchAll(new RegExp(`<${tag}\\b[^>]*\\b${name}\\s*=\\s*["']([^"']*)`, "gi"))].map(m => decodeHtml(m[1]!));
const evidence = (page: ExtractionPage, text: string, confidence = 0.8): Evidence & { confidence: number } => ({ url: page.url, text: clean(text).slice(0, 220), confidence });
const uniq = <T>(items: T[], key: (x: T) => string) => [...new Map(items.map(x => [key(x).toLowerCase(), x])).values()];
const norm = (v: string) => v.toLowerCase().replace(/&[^;]+;/g, " ").replace(/[^a-z0-9\u0600-\u06ff]+/g, " ").replace(/\b(the|a|an|our|your|for|and|with)\b/g, " ").replace(/\s+/g, " ").trim();
const generic = /^(?:faq|faqs|frequently asked questions|about(?: us)?|products?|solutions?|developers?|pricing|guide me|support|contact(?: us)?|contact sales|careers?|jobs?|documentation|docs?|resources?|blog|news|login|sign ?in|sign ?up|see what'?s ahead|learn more|get started|talk to sales|flexible solutions?|solutions? for every business model|what do you offer|do you offer|how does|why stripe)$/i;
const sentenceLike = (v: string) => v.length > 90 || /[?!.]/.test(v) || /\b(?:the|we|you|your|our)\b.*\b(?:is|are|can|will|with|for)\b/i.test(v);
const rejectedHeading = (v: string) => generic.test(v) || generic.test(v.replace(/[.!?…]+$/, "")) || /see what.{0,3}s ahead|product roadmap|features? available|tools to optimize|optimizations? to|to optimize|boost revenue/i.test(v) || sentenceLike(v) || /^(?:start|choose|build|read|learn|accept|enable|embed|manage|connect|use|make|reduce|scale|improve|create|implement|offer|safeguard|automate|access|monetize|launch|see|grow|protect)\b/i.test(v);
function headings(page: ExtractionPage) { return [...page.html.matchAll(/<(h1|h2|h3|h4|li)\b[^>]*>([\s\S]*?)<\/\1>/gi)].map(m => decodeHtml(m[2]!.replace(/<[^>]+>/g, " "))).filter(x => x.length >= 3 && x.length <= 90 && !rejectedHeading(x)); }
function headingLinks(page: ExtractionPage) { return [...page.html.matchAll(/<(?:h1|h2|h3|h4)[^>]*>[\s\S]*?<a\b[^>]*href=["']([^"']+)["'][^>]*>([\s\S]*?)<\/a>[\s\S]*?<\/h[1-4]>/gi)].map(m => ({ name: decodeHtml(m[2]!.replace(/<[^>]+>/g, " ")), href: m[1]! })).filter(x => !rejectedHeading(x.name)); }
function productSignals(pages: ExtractionPage[], root: URL) {
  const out: { name: string; description: string | null; category: string | null; url: string; pricingDetected: boolean; productConfidence: number; evidence: Evidence[] }[] = [];
  for (const page of pages) {
    const path = new URL(page.url).pathname.toLowerCase(); const productPage = /(?:^|\/)(?:products?|solutions?|platform|features?)(?:\/|$)/.test(path);
    for (const name of headings(page)) {
      const explicit = productPage || /product|solution|platform|feature|payment|billing|checkout|connect|terminal|radar|atlas/i.test(name);
      if (!explicit || rejectedHeading(name) || /\b(?:faq|question|support|documentation|resource|blog|news)\b/i.test(name) || name.split(" ").length > 8) continue;
      const e = evidence(page, name, productPage ? 0.86 : 0.68); out.push({ name, description: null, category: null, url: page.url, pricingDetected: false, productConfidence: e.confidence, evidence: [e] });
    }
    for (const link of headingLinks(page)) { const target = new URL(link.href, page.url); if (target.hostname !== root.hostname || !/(?:product|solution|platform|feature|payment|billing|checkout)/i.test(target.pathname)) continue; const e = evidence(page, link.name, 0.9); out.push({ name: link.name, description: null, category: null, url: target.toString(), pricingDetected: false, productConfidence: e.confidence, evidence: [e] }); }
    for (const ld of [...page.html.matchAll(/<script[^>]+type=["']application\/ld\+json["'][^>]*>([\s\S]*?)<\/script>/gi)]) { try { const value = JSON.parse(ld[1]!); const nodes = Array.isArray(value) ? value : [value]; for (const node of nodes) if (node && node["@type"] === "Product" && typeof node.name === "string") out.push({ name: decodeHtml(node.name), description: typeof node.description === "string" ? decodeHtml(node.description) : null, category: typeof node.category === "string" ? node.category : null, url: typeof node.url === "string" ? node.url : page.url, pricingDetected: Boolean(node.offers), productConfidence: 0.96, evidence: [evidence(page, `${node.name}${node.description ? ` — ${node.description}` : ""}`, 0.96)] }); } catch { /* malformed JSON-LD is ignored */ } }
  }
  return uniq(out.filter(x => !rejectedHeading(x.name)), x => norm(x.name)).slice(0, 30);
}
function serviceSignals(pages: ExtractionPage[]) { const out: { name: string; description: string | null; url: string; confidence: number; evidence: Evidence[] }[] = []; for (const page of pages) { const servicePage = /(?:^|\/)(?:services?|consulting|advisory|implementation|managed-services?)(?:\/|$)/i.test(new URL(page.url).pathname); for (const name of headings(page)) { if (!servicePage && !/consulting|implementation|managed|advisory|professional services|integration|training/i.test(name)) continue; if (rejectedHeading(name) || name.split(" ").length < 2 || name.split(" ").length > 6 || /^\d/.test(name)) continue; const e = evidence(page, name, servicePage ? 0.84 : 0.66); out.push({ name, description: null, url: page.url, confidence: e.confidence, evidence: [e] }); } } return uniq(out.filter(x => x.name.length >= 5), x => norm(x.name)).slice(0, 20); }
function jsonLdPages(pages: ExtractionPage[]) { return pages.flatMap(page => [...page.html.matchAll(/<script[^>]+type=["']application\/ld\+json["'][^>]*>([\s\S]*?)<\/script>/gi)].flatMap(m => { try { const v = JSON.parse(m[1]!); return Array.isArray(v) ? v : [v]; } catch { return []; } }).map(value => ({ page, value }))); }
function pricingSignals(pages: ExtractionPage[]) { const out: { name: string | null; price: number | null; currency: string | null; billingPeriod: string | null; unit: string | null; description: string | null; url: string | null; confidence: number; evidence: Evidence[] }[] = []; for (const page of pages) { const pathPricing = /(?:^|\/)(?:pricing|plans?|rates|fees)(?:\/|$)/i.test(new URL(page.url).pathname); const chunks = page.text.split(/(?<=[.!?])\s+|\n+/).map(clean).filter(Boolean); for (const chunk of chunks) { const amountPattern = /(?:([$€£])\s?([0-9][0-9,]*(?:\.\d{1,2})?)|([0-9][0-9,]*(?:\.\d{1,2})?)\s?(USD|EUR|GBP|OMR|AED|\$|€|£))/gi; for (const match of chunk.matchAll(amountPattern)) { const amount = Number((match[2] ?? match[3])!.replace(/,/g, "")); const at = match.index ?? 0; const suffix = chunk.slice(at + match[0].length, at + match[0].length + 4); if (!Number.isFinite(amount) || amount > 10000000 || /^\s*[KMBT%]/i.test(suffix)) continue; const window = chunk.slice(Math.max(0, at - 60), Math.min(chunk.length, at + match[0].length + 60)); const strong = /(?:pricing|plan|tier|package|starting at|per (?:month|year|transaction|payment|item)|monthly|subscription|usage fee|processing fee|free trial|price)/i.test(window); if (!strong) continue; const currency = match[1] ?? match[4] ?? null; const periodMatch = /per\s+(month|year|transaction|payment|item)|monthly/i.exec(window); const period = periodMatch?.[1] ?? (periodMatch ? "month" : null); const before = window.slice(0, Math.max(0, window.indexOf(match[0]))).trim(); const name = before.split(/[,:;|]/).pop()?.trim() || null; const confidence = pathPricing ? 0.88 : 0.78; out.push({ name: name && name.length <= 70 && !/^\d/.test(name) && !/[$€£]/.test(name) ? name : null, price: amount, currency, billingPeriod: period, unit: /transaction|payment/i.test(window) ? "transaction" : /item/i.test(window) ? "item" : null, description: window.slice(0, 220), url: page.url, confidence, evidence: [evidence(page, window, confidence)] }); } } } return uniq(out.filter(x => x.confidence >= 0.75), x => `${x.name ?? ""}|${x.price}|${x.currency}|${x.billingPeriod}`).slice(0, 30); }
function phones(pages: ExtractionPage[]) { const out: string[] = []; for (const page of pages) { for (const href of attrAll(page.html, "a", "href").filter(x => /^tel:/i.test(x))) { const raw = decodeHtml(href.replace(/^tel:/i, "").split(/[?#]/)[0]!); const digits = raw.replace(/\D/g, ""); if (digits.length >= 7 && digits.length <= 15) out.push(raw); } for (const match of page.text.matchAll(/(?:phone|tel\.?|call us|contact)\s*[:\-]?\s*(\+?[0-9][0-9 ()\-.]{6,18}[0-9])/gi)) { const raw = clean(match[1]!); if (/\d[.,]\d/.test(raw) || /\b20\d{2}\b/.test(raw)) continue; const digits = raw.replace(/\D/g, ""); if (digits.length >= 7 && digits.length <= 15) out.push(raw); } } return uniq(out, x => x.replace(/\D/g, "")).slice(0, 20); }
const customerMap: [RegExp, string][] = [[/startup|start-up/i, "Startups"], [/enterprise|large organizations?/i, "Enterprises"], [/saas/i, "SaaS companies"], [/e-?commerce|online retailers?/i, "E-commerce businesses"], [/marketplace/i, "Marketplaces"], [/platforms?/i, "Platforms"], [/financial institutions?|banks?|fintech/i, "Financial institutions"], [/developers?|engineering teams?/i, "Developers"], [/small businesses?|smb/i, "Small businesses"]];
function customers(pages: ExtractionPage[]) { const text = pages.map(x => x.text).join(" "); return customerMap.flatMap(([re, value]) => re.test(text) ? [{ value, evidence: pages.filter(p => re.test(p.text)).slice(0, 2).map(p => evidence(p, p.text.match(re)?.[0] ?? value, 0.78)), confidence: 0.78 }] : []); }
function industry(pages: ExtractionPage[], org: Record<string, unknown>) { const text = pages.map(x => x.text).join(" "); const terms: [RegExp, string, string][] = [[/payments?|payment processing|financial technology|fintech/i, "Financial Services", "FinTech"], [/software|platform|api|saas/i, "Software", "Enterprise Software"], [/e-?commerce|online store/i, "E-commerce", "E-commerce"], [/real estate|property/i, "Real Estate", "Property Technology"], [/healthcare|clinical|medical/i, "Healthcare", "Health Technology"], [/marketing|advertising/i, "Marketing", "Marketing Technology"], [/cybersecurity|security platform/i, "Cybersecurity", "Security Software"], [/logistics|shipping|freight/i, "Logistics", "Logistics Technology"], [/education|learning platform/i, "Education", "Education Technology"], [/consulting|professional services/i, "Professional Services", "Consulting"]]; const explicit = typeof org.industry === "string" ? org.industry : null; const found = terms.find(([re]) => re.test(text)); return { industry: explicit ?? found?.[1] ?? null, subIndustry: explicit ? null : found?.[2] ?? null, confidence: explicit ? 0.92 : found ? 0.7 : 0, evidence: found ? pages.filter(p => found[0].test(p.text)).slice(0, 2).map(p => evidence(p, found[0].source, 0.7)) : [] }; }
function location(pages: ExtractionPage[], nodes: { page: ExtractionPage; value: any }[]) { for (const { page, value } of nodes) { const address = value?.address; if (address && typeof address === "object") return { country: typeof address.addressCountry === "string" ? address.addressCountry : null, city: typeof address.addressLocality === "string" ? address.addressLocality : null, evidence: [evidence(page, JSON.stringify(address), 0.93)] }; } return { country: null, city: null, evidence: [] as Evidence[] }; }
export function buildAnalysis(input: { includeOpportunities: boolean; includeBusinessAnalysis: boolean; includeTechnology: boolean; includeContacts: boolean; includeSocialProfiles: boolean; includePricing: boolean; includeSalesIntelligence: boolean; includeSEO: boolean }, pages: ExtractionPage[], root: URL) {
  const text = pages.map(p => p.text).join(" "); const home = pages[0]!; const title = decodeHtml(/<title\b[^>]*>([\s\S]*?)<\/title>/i.exec(home.html)?.[1] ?? "") || null; const description = decodeHtml(/<meta\b[^>]*name=["']description["'][^>]*content=["']([^"']*)/i.exec(home.html)?.[1] ?? "") || null; const nodes = jsonLdPages(pages); const orgNode = nodes.find(x => /Organization|Corporation|LocalBusiness/.test(String(x.value?.["@type"])))?.value ?? {}; const orgPage = nodes.find(x => x.value === orgNode)?.page ?? home; const companyName: Finding = typeof orgNode.name === "string" ? { value: decodeHtml(orgNode.name), confidence: 0.95, evidence: [evidence(orgPage, String(orgNode.name), 0.95)] } : title ? { value: title.split(/[|–—-]/)[0]!.trim(), confidence: 0.65, evidence: [evidence(home, title, 0.65)] } : { value: null, confidence: 0, evidence: [] }; const companyDescription: Finding = typeof orgNode.description === "string" ? { value: decodeHtml(orgNode.description), confidence: 0.9, evidence: [evidence(orgPage, String(orgNode.description), 0.9)] } : description ? { value: description, confidence: 0.82, evidence: [evidence(home, description, 0.82)] } : { value: null, confidence: 0, evidence: [] }; const loc = location(pages, nodes); const ind = industry(pages, orgNode); const products = productSignals(pages, root); const services = serviceSignals(pages); const plans = pricingSignals(pages); const hrefs = attrAll(pages.map(p => p.html).join(" "), "a", "href"); const emails = uniq([...hrefs.filter(x => /^mailto:/i.test(x)).map(x => x.replace(/^mailto:/i, "").split(/[?#]/)[0]!.toLowerCase()), ...pages.filter(p => /contact|footer/i.test(p.url)).flatMap(p => [...p.text.matchAll(/[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,}/gi)].map(m => m[0].toLowerCase()))].filter(x => !/example\.|sample|yourname|test@/i.test(x)), x => x).slice(0, 20); const phoneValues = phones(pages); const addresses = uniq(nodes.flatMap(({ value }) => value?.address && typeof value.address === "object" ? [decodeHtml(JSON.stringify(value.address))] : []), x => x).slice(0, 10); const socials: Record<string, string[]> = {}; for (const href of hrefs) { const m = href.match(/https?:\/\/[^/]*(linkedin\.com|twitter\.com|x\.com|facebook\.com|instagram\.com|youtube\.com|tiktok\.com|github\.com)[^\s"']*/i); if (m) { const k = m[1]!.split('.')[0] === "twitter" ? "x" : m[1]!.split('.')[0]!; (socials[k] ??= []).push(href.split(/[?#]/)[0]!); } } for (const k of Object.keys(socials)) socials[k] = uniq(socials[k]!, x => x);
  const tech: Record<string, { name: string; evidence: Evidence[]; confidence: number }[]> = {}; const techRules: [string, string, RegExp][] = [["CMS", "WordPress", /wp-content|wp-includes/i], ["E-commerce", "Shopify", /cdn\.shopify|shopify\.com/i], ["Frontend framework", "Next.js", /__next|_next\/static/i], ["Frontend framework", "React", /react(?:\.production)?\.min|data-reactroot/i], ["Frontend framework", "Vue", /vue(?:\.runtime)?\.min|data-v-[a-f0-9]/i], ["Analytics", "Google Analytics", /google-analytics|gtag\(|googletagmanager/i], ["Tag manager", "Google Tag Manager", /googletagmanager/i], ["CRM/marketing", "HubSpot", /js\.hs-scripts\.com|hsforms\.com/i], ["CRM/marketing", "Salesforce", /\.salesforce\.com|force\.com/i], ["Payments", "Stripe", /js\.stripe\.com|checkout\.stripe\.com/i], ["CDN/hosting", "Cloudflare", /server:\s*cloudflare|cf-ray/i], ["Chat/support", "Intercom", /widget\.intercom\.io|intercomcdn/i]]; for (const [category, name, re] of techRules) { const matched = pages.filter(p => re.test(`${p.html} ${[...p.headers].map(x => x.join(":")).join(" ")}`)); if (matched.length) tech[category] = [{ name, evidence: matched.slice(0, 2).map(p => evidence(p, `${name} detected in HTML or response headers`, 0.9)), confidence: 0.9 }]; }
  const seo = { titlePresent: pages.some(p => /<title\b/i.test(p.html)), metaDescriptionPresent: pages.some(p => /<meta[^>]+name=["']description/i.test(p.html)), canonicalPresent: pages.some(p => /<link[^>]+rel=["'][^"']*canonical/i.test(p.html)), structuredDataDetected: nodes.length > 0, sitemapDetected: false, robotsTxtDetected: false, h1Present: pages.some(p => /<h1\b/i.test(p.html)), mobileFriendlySignals: pages.some(p => /<meta[^>]+name=["']viewport/i.test(p.html)), issues: [] as string[] }; if (!seo.titlePresent) seo.issues.push("Missing title"); if (!seo.metaDescriptionPresent) seo.issues.push("Missing meta description"); if (!seo.h1Present) seo.issues.push("Missing H1"); if (!seo.canonicalPresent) seo.issues.push("Missing canonical"); if (!seo.structuredDataDetected) seo.issues.push("No structured data detected");
  const customerSegments = customers(pages); const primary = /payment|payments|fintech|financial technology/i.test(text) ? ["Payments Infrastructure", "Financial Technology"] : /e-?commerce|shop|cart/i.test(text) ? ["E-commerce"] : /saas|software platform|api/i.test(text) ? ["Software"] : ind.industry ? [ind.industry] : []; const secondary = [plans.length ? "Usage Based" : null, /subscription|per month|annual/i.test(text) ? "Subscription" : null, /enterprise/i.test(text) ? "Enterprise Software" : null].filter((x): x is string => Boolean(x)); const businessModel = { type: uniq([...primary, ...secondary], x => x), primaryBusinessModel: primary, secondaryBusinessModels: secondary, customerType: [customerSegments.some(x => /Enterprise|SaaS|Developers|Financial|business/i.test(x.value)) ? "B2B" : null].filter((x): x is string => Boolean(x)), revenueModel: secondary, targetCustomers: customerSegments.map(x => x.value), targetIndustries: ind.industry ? [ind.industry] : [], geographicMarkets: [] as string[], supportingServices: services.map(x => x.name) };
  const conversion = { primaryCTA: null as string | null, ctas: [], contactForm: pages.some(p => /<form\b/i.test(p.html)), demoAvailable: /\b(?:book|request)\s+(?:a\s+)?demo\b/i.test(text), signupAvailable: /sign[ -]?up|create account/i.test(text), freeTrialAvailable: /free trial/i.test(text), liveChatDetected: /widget\.intercom|intercomcdn|tawk\.to|livechat/i.test(pages.map(p => p.html).join(" ")), whatsappDetected: /wa\.me|whatsapp/i.test(hrefs.join(" ")) };
  const signals = { pricingVisible: plans.length > 0, freeTrial: conversion.freeTrialAvailable, demoAvailable: conversion.demoAvailable, enterpriseOffering: /\benterprise\b/i.test(text), customerLogosDetected: /customer logos?|trusted by|our clients/i.test(text), caseStudiesDetected: /case stud(?:y|ies)/i.test(text), testimonialsDetected: /testimonial|what our clients say/i.test(text), blogDetected: pages.some(p => /\/blog(?:\/|$)/i.test(p.url)), careersDetected: /career|jobs|join our team/i.test(text), multipleLanguagesDetected: /hreflang|العربية|français|español/i.test(text) };
  const unknown = 5 + (ind.industry ? 0 : 1) + (loc.country ? 0 : 1) + (plans.length ? 0 : 1); const score = (base: number, measured: number, unknownSignals: number) => ({ score: Math.max(0, Math.min(95, Math.round(base))), measuredSignals: measured, unknownSignals }); const seoScore = 100 - (seo.titlePresent ? 0 : 15) - (seo.metaDescriptionPresent ? 0 : 15) - (seo.canonicalPresent ? 0 : 10) - (seo.structuredDataDetected ? 0 : 15) - (seo.h1Present ? 0 : 10) - (seo.mobileFriendlySignals ? 0 : 10) - (seo.robotsTxtDetected ? 0 : 5) - (seo.sitemapDetected ? 0 : 5); const scoreDiagnostics = { websiteQuality: score(100 - Math.min(55, seo.issues.length * 10 + (pages.length < 2 ? 10 : 0)), 8 - seo.issues.length, unknown), businessClarity: score((companyName.value ? 35 : 0) + (companyDescription.value ? 30 : 0) + (primary.length ? 25 : 0), 3, unknown), conversionReadiness: score((conversion.contactForm ? 30 : 0) + (conversion.demoAvailable ? 20 : 0) + (conversion.signupAvailable ? 20 : 0) + (conversion.whatsappDetected ? 10 : 0) + (conversion.primaryCTA ? 20 : 0), 5, 1), seoReadiness: score(seoScore, 8, 2), digitalMaturity: score((Object.keys(tech).length ? 30 : 0) + (signals.customerLogosDetected ? 20 : 0) + (signals.caseStudiesDetected ? 15 : 0) + (plans.length ? 15 : 0) + (signals.blogDetected ? 10 : 0), 5, 3) }; const scores = { websiteQuality: scoreDiagnostics.websiteQuality.score, businessClarity: scoreDiagnostics.businessClarity.score, conversionReadiness: scoreDiagnostics.conversionReadiness.score, seoReadiness: scoreDiagnostics.seoReadiness.score, digitalMaturity: scoreDiagnostics.digitalMaturity.score, scoreDiagnostics };
  const opportunities: any[] = []; const add = (type: string, priority: "high"|"medium"|"low", finding: string, recommendation: string, pagesForEvidence: ExtractionPage[]) => opportunities.push({ type, priority, finding, recommendation, confidence: 0.78, evidence: pagesForEvidence.slice(0, 3).map(p => evidence(p, finding, 0.78)), reasoningBasis: "Observed public-page signal; absence of a signal is not treated as proof of absence." }); if (!seo.metaDescriptionPresent) add("seo", "medium", "No meta description detected on analyzed pages", "Add unique meta descriptions to important landing pages.", pages); if (!seo.h1Present) add("seo", "medium", "No H1 heading detected on analyzed pages", "Add a descriptive primary heading to key pages.", pages); if (!conversion.contactForm && !conversion.signupAvailable && !conversion.demoAvailable) add("conversion", "medium", "No public lead or signup mechanism detected", "Consider adding a clear, low-friction conversion path.", pages); const sales = { potentialNeeds: opportunities.map(o => o.finding), salesAngles: opportunities.filter(o => o.type === "conversion").map(o => o.recommendation), technologyOpportunities: [], marketingOpportunities: opportunities.filter(o => o.type === "seo").map(o => o.recommendation), automationOpportunities: [], technologyDetectionState: { CRM: "UNKNOWN", ERP: "UNKNOWN", marketingAutomation: "UNKNOWN", analytics: Object.keys(tech).some(k => k === "Analytics") ? "DETECTED" : "UNKNOWN" } };
  const extractionConfidence = Math.min(0.9, Math.max(0.25, (companyName.confidence + companyDescription.confidence + (products.length ? 0.75 : 0.35) + (services.length ? 0.75 : 0.45) + (plans.length ? 0.8 : 0.5)) / 5));
  return { company: { name: companyName, domain: root.hostname, description: companyDescription, industry: ind.industry ? { value: ind.industry, confidence: ind.confidence, evidence: ind.evidence } : null, subIndustry: ind.subIndustry ? { value: ind.subIndustry, confidence: ind.confidence, evidence: ind.evidence } : null, country: loc.country ? { value: loc.country, confidence: 0.9, evidence: loc.evidence } : null, city: loc.city ? { value: loc.city, confidence: 0.9, evidence: loc.evidence } : null, founded: null }, businessModel, products, services, pricing: { pricingPageDetected: pages.some(p => /(?:^|\/)(?:pricing|plans?|rates|fees)(?:\/|$)/i.test(new URL(p.url).pathname)), pricingUrl: pages.find(p => /(?:^|\/)(?:pricing|plans?|rates|fees)(?:\/|$)/i.test(new URL(p.url).pathname))?.url ?? null, freeTrial: conversion.freeTrialAvailable, freemium: /freemium/i.test(text), contactForPricing: /contact (?:us )?for pricing/i.test(text), plans }, contacts: { emails, phones: phoneValues, addresses, contactPage: pages.find(p => /contact/i.test(p.url))?.url ?? null }, socialProfiles: socials, technology: tech, seo, conversion, businessSignals: signals, scores, opportunities: input.includeOpportunities ? opportunities : [], salesIntelligence: input.includeSalesIntelligence ? sales : { potentialNeeds: [], salesAngles: [], technologyOpportunities: [], marketingOpportunities: [], automationOpportunities: [], technologyDetectionState: sales.technologyDetectionState }, crawl: { pagesAnalyzed: pages.length, urls: pages.map(p => p.url) }, confidence: { crawlConfidence: Math.min(0.95, 0.55 + pages.length * 0.03), extractionConfidence, overallConfidence: Math.round(((Math.min(0.95, 0.55 + pages.length * 0.03) + extractionConfidence) / 2) * 100) / 100 }, generatedAt: new Date().toISOString() };
}
