import { promises as dns } from "node:dns";

export type FeedUrlRejectionReason = "invalid_url" | "unsupported_scheme" | "blocked_hostname" | "private_ip_literal" | "private_ip_resolved";
export class FeedUrlRejectedError extends Error { constructor(readonly reason: FeedUrlRejectionReason, message: string) { super(message); this.name = "FeedUrlRejectedError"; } }
export interface HostResolver { resolve(hostname: string): Promise<readonly string[]>; }
class DnsHostResolver implements HostResolver { async resolve(hostname: string) { return (await dns.lookup(hostname, { all: true })).map(x => x.address); } }
const isPrivate = (ip: string) => { const h = ip.toLowerCase().replace(/^\[|\]$/g, ""); if (h.includes(":")) return h === "::1" || h === "::" || /^fe[89ab]/.test(h) || /^f[cd]/.test(h) || /^::ffff:(10\.|127\.|169\.254\.|192\.168\.)/.test(h); const p = h.split(".").map(Number); if (p.length !== 4 || p.some(x => !Number.isInteger(x) || x < 0 || x > 255)) return true; const [a,b,c] = p; return a === 0 || a === 10 || a === 127 || (a === 169 && b === 254) || (a === 172 && b >= 16 && b <= 31) || (a === 192 && b === 168) || (a === 100 && b >= 64 && b <= 127) || a >= 224 || (a === 192 && b === 0 && c === 2) || (a === 198 && b === 51 && c === 100) || (a === 203 && b === 0 && c === 113); };
export async function validateFeedUrl(raw: string, options: { resolver?: HostResolver; allowInsecureHttp?: boolean } = {}) { let url: URL; try { url = new URL(raw); } catch { throw new FeedUrlRejectedError("invalid_url", "URL is invalid."); } if (url.protocol !== "https:" && !(url.protocol === "http:" && options.allowInsecureHttp)) throw new FeedUrlRejectedError("unsupported_scheme", "Only https URLs are allowed."); if (url.username || url.password) throw new FeedUrlRejectedError("invalid_url", "URL credentials are not allowed."); const host = url.hostname.toLowerCase(); if (["localhost", "0.0.0.0", "127.0.0.1", "::1"].includes(host) || host.endsWith(".localhost")) throw new FeedUrlRejectedError("blocked_hostname", "Localhost/loopback private address is not allowed."); if (/^\d{1,3}(\.\d{1,3}){3}$/.test(host)) { if (isPrivate(host)) throw new FeedUrlRejectedError("private_ip_literal", "Private or reserved IP is not allowed."); return url; } for (const ip of await (options.resolver ?? new DnsHostResolver()).resolve(host)) if (isPrivate(ip)) throw new FeedUrlRejectedError("private_ip_resolved", "Hostname resolves to a private or reserved IP."); return url; }
export type FeedFetchErrorKind = "timeout" | "network" | "too_large" | "too_many_redirects" | "bad_redirect";
export class FeedFetchError extends Error { constructor(readonly kind: FeedFetchErrorKind, message: string) { super(message); this.name = "FeedFetchError"; } }
const redirects = new Set([301, 302, 303, 307, 308]);
export async function safeFeedFetch(raw: string, options: { timeoutMs: number; maxResponseBytes: number; maxRedirects?: number; fetchImpl?: typeof fetch; resolver?: HostResolver; truncateAtLimit?: boolean }): Promise<{ status: number; contentType: string | null; body: string; finalUrl: string; headers: Headers }> { const fetchImpl = options.fetchImpl ?? fetch; let current = await validateFeedUrl(raw, { resolver: options.resolver }); for (let i = 0; ; i++) { const controller = new AbortController(); const timer = setTimeout(() => controller.abort(), options.timeoutMs); let response: Response; try { response = await fetchImpl(current.toString(), { method: "GET", redirect: "manual", signal: controller.signal, headers: { "user-agent": "Rafid-Website-Business-Analyzer/1.0" } }); } catch (e) { clearTimeout(timer); throw new FeedFetchError(e instanceof Error && e.name === "AbortError" ? "timeout" : "network", e instanceof Error ? e.message : String(e)); } clearTimeout(timer); if (redirects.has(response.status)) { const location = response.headers.get("location"); if (!location) throw new FeedFetchError("bad_redirect", "Redirect has no Location header."); if (i >= (options.maxRedirects ?? 3)) throw new FeedFetchError("too_many_redirects", "Too many redirects."); current = await validateFeedUrl(new URL(location, current).toString(), { resolver: options.resolver }); continue; } const reader = response.body?.getReader(); const chunks: Uint8Array[] = []; let total = 0; if (reader) { for (;;) { const part = await reader.read(); if (part.done) break; const remaining = options.maxResponseBytes - total; if (part.value.byteLength > remaining) { if (!options.truncateAtLimit) throw new FeedFetchError("too_large", "Response exceeded size limit."); chunks.push(part.value.subarray(0, Math.max(0, remaining))); await reader.cancel().catch(() => {}); break; } chunks.push(part.value); total += part.value.byteLength; } reader.releaseLock?.(); } return { status: response.status, contentType: response.headers.get("content-type"), body: Buffer.concat(chunks.map(x => Buffer.from(x))).toString("utf8"), finalUrl: current.toString(), headers: response.headers }; } }
