/** Prefixed to the documented example's `assumptions`: the example is generated from explicitly
 *  synthetic fixture listings (src/vehicle-value/examples/fixtures.ts), not from live market data. */
export const VEHICLE_SYNTHETIC_EXAMPLE_NOTICE = "SYNTHETIC EXAMPLE: generated by the real valuation engine from fictional fixture listings (sources \"synthetic-…\", reserved .example URLs). It illustrates the response shape and method only; it is not a valuation of any real vehicle or market.";
