import assert from "node:assert/strict";
import test from "node:test";
import { analyzeWebsite, normalizeInput, prioritizeUrls } from "../src/analyzer.js";
import { run } from "../src/main.js";

const resolver = { async resolve() { return ["93.184.216.34"]; } };
const html = `<!doctype html><html lang="en"><head><title>Acme Cloud | Software</title><meta name="description" content="Acme Cloud helps retailers automate operations."><meta name="viewport" content="width=device-width"><link rel="canonical" href="https://example.test/"><script type="application/ld+json">{"@type":"Organization","name":"Acme Cloud","description":"Retail operations software"}</script></head><body><h1>Retail operations software</h1><p>We help retailers and enterprise teams automate inventory. Plans from $49/month. Start a free trial.</p><a href="/about">About</a><a href="/pricing">Pricing</a><a href="mailto:sales@acme.test">Email</a><a href="https://linkedin.com/company/acme">LinkedIn</a><form><input></form></body></html>`;
const fetchImpl: typeof fetch = async (request) => { const path = new URL(String(request)).pathname; if (path === "/about") return new Response("<html><head><title>About Acme</title></head><body><h1>About</h1><p>Acme Cloud is based in Dubai and serves businesses.</p></body></html>", { headers: { "content-type": "text/html" } }); if (path === "/pricing") return new Response("<html><body><h1>Pricing</h1><p>Starter $49/month, Enterprise contact us for pricing.</p></body></html>", { headers: { "content-type": "text/html" } }); return new Response(html, { headers: { "content-type": "text/html" } }); };

test("normalizes URLs and rejects credentials/unsupported values", () => { assert.equal(normalizeInput({ websiteUrl: "example.test" }).websiteUrl, "https://example.test/"); assert.throws(() => normalizeInput({ websiteUrl: "file:///etc/passwd" }), /public http/); assert.throws(() => normalizeInput({ websiteUrl: "https://u:p@example.test" }), /credentials/); });
test("prioritizes commercial paths and deduplicates links in the analyzer", async () => { const result = await analyzeWebsite({ websiteUrl: "https://example.test", maxPages: 15, maxDepth: 1 }, { resolver, fetchImpl }); assert.equal(result.success, true); assert.equal(result.crawl.pagesAnalyzed, 15); assert.equal(result.company.name.value, "Acme Cloud"); assert.equal(result.pricing.plans.length, 2); assert.ok(result.contacts.emails.includes("sales@acme.test")); assert.equal(result.socialProfiles.linkedin.length, 1); assert.equal(result.technology["Frontend framework"], undefined); assert.ok(result.scores.seoReadiness <= 95); assert.equal(result.scores.scoreDiagnostics.seoReadiness.score, result.scores.seoReadiness); });

test("accuracy gates reject generic headings, statistics, fragments, and absent-CRM opportunities", async () => {
  const fixture = `<!doctype html><html><head><title>Precision Payments</title><meta name="description" content="Payments infrastructure for developers and enterprises."></head><body><h1>Payments infrastructure</h1><h2>Frequently asked questions</h2><h2>Do you offer any discounts?</h2><h2>See what&#x27;s ahead</h2><p>Revenue $5,839,417.15 in 2025 99.999. Contact: +971 4 123 4567.</p><a href="/products">Products</a><a href="/pricing">Pricing</a><a href="mailto:team@precision.test">Email</a></body></html>`;
  const fixtureFetch: typeof fetch = async request => { const path = new URL(String(request)).pathname; if (path === "/products") return new Response("<html><body><h1>Products</h1><h2>Payment Links</h2><h2>Frequently asked questions</h2></body></html>", { headers: { "content-type": "text/html" } }); if (path === "/pricing") return new Response("<html><body><h1>Pricing</h1><h2>Starter</h2><p>Starter plan $29 per month.</p><p>Revenue $5,839,417.15.</p></body></html>", { headers: { "content-type": "text/html" } }); return new Response(fixture, { headers: { "content-type": "text/html" } }); };
  const result = await analyzeWebsite({ websiteUrl: "https://precision.test", maxPages: 3, maxDepth: 1 }, { resolver, fetchImpl: fixtureFetch });
  assert.ok(result.products.some(p => p.name === "Payment Links"), JSON.stringify({ urls: result.crawl.urls, products: result.products })); assert.ok(result.products.every(p => !/faq|discount|ahead|question/i.test(p.name))); assert.ok(result.pricing.plans.every(p => p.price !== 5839417.15)); assert.ok(result.contacts.phones.every(p => !/2025|99\.999/.test(p))); assert.ok(result.contacts.emails.includes("team@precision.test")); assert.ok(result.businessModel.targetCustomers.every(x => !/[.!?]/.test(x))); assert.ok(!result.opportunities.some(o => /CRM/i.test(o.finding))); assert.ok(result.salesIntelligence.technologyDetectionState.CRM === "UNKNOWN"); assert.ok(!JSON.stringify(result).includes("&#x27;"));
});
test("SSRF and redirect protection produce structured predictable errors", async () => { await assert.rejects(() => analyzeWebsite({ websiteUrl: "https://127.0.0.1" }, { resolver, fetchImpl }), /private|loopback|reserved/i); const redirectFetch: typeof fetch = async () => new Response("", { status: 302, headers: { location: "https://127.0.0.1/private" } }); const pushed: unknown[] = []; const partial = await run({ websiteUrl: "https://example.test", maxPages: 1 }, { pushData: async x => { pushed.push(x); }, setValue: async () => {}, options: { resolver, fetchImpl: redirectFetch } }); assert.equal((partial as any).success, false); assert.equal((partial as any).error.code, "PRIVATE_NETWORK_URL"); });
test("scores are deterministic and main returns partial-safe failure records", async () => { const a = await analyzeWebsite({ websiteUrl: "https://example.test", maxPages: 2, maxDepth: 0 }, { resolver, fetchImpl, now: () => "2026-01-01T00:00:00.000Z" }); const b = await analyzeWebsite({ websiteUrl: "https://example.test", maxPages: 2, maxDepth: 0 }, { resolver, fetchImpl, now: () => "2026-01-01T00:00:00.000Z" }); assert.deepEqual({ scores: a.scores, products: a.products, crawl: a.crawl }, { scores: b.scores, products: b.products, crawl: b.crawl }); const pushed: unknown[] = []; const out = await run({ websiteUrl: "https://127.0.0.1" }, { pushData: async x => { pushed.push(x); }, setValue: async () => {}, options: { resolver, fetchImpl } }); assert.equal((out as any).success, false); assert.equal((out as any).error.code, "PRIVATE_NETWORK_URL"); assert.equal(pushed.length, 1); });
