import { z } from "zod";
const anyObject = z.record(z.string(), z.unknown());
const evidenceQuality = z.strictObject({ score: z.number().min(0).max(100), missing_information: z.array(z.string()), ambiguities: z.array(z.string()) });
export const candidateProfileOutput = z.strictObject({ candidate: anyObject, experience: z.array(anyObject), education: z.array(anyObject), skills: z.array(anyObject), certifications: z.array(anyObject), languages: z.array(anyObject), projects: z.array(anyObject), industries: z.array(z.string()), management_experience: z.boolean().nullable(), total_experience_years: z.number().nullable(), recent_role: z.string().nullable(), seniority_estimate: z.string().nullable(), career_progression: z.array(z.string()), candidate_keywords: z.array(z.string()), evidence_quality: evidenceQuality });
export const jobProfileOutput = z.strictObject({ job_title: z.string(), role_family: z.string(), seniority: z.string(), industry: z.array(z.string()), required_skills: z.array(anyObject), preferred_skills: z.array(anyObject), required_experience_years: z.number().nullable(), preferred_experience_years: z.number().nullable(), required_education: z.array(z.string()), certifications: z.array(z.string()), responsibilities: z.array(z.string()), domain_experience: z.array(z.string()), technical_requirements: z.array(z.string()), leadership_requirements: z.array(z.string()), language_requirements: z.array(z.string()), location_requirements: z.string().nullable(), employment_type: z.string().nullable(), keywords: z.array(z.string()), scoring_model: anyObject });
export const cvScoreOutput = z.strictObject({ score: z.number().min(0).max(100), dimensions: anyObject, strengths: z.array(z.string()), weaknesses: z.array(z.string()), missing_sections: z.array(z.string()), high_priority_improvements: z.array(z.string()), warnings: z.array(z.string()), confidence: z.number().min(0).max(1) });
export const cvJobMatchOutput = z.strictObject({ match_score: z.number().min(0).max(100), decision_support: anyObject, category_scores: anyObject, skill_match: z.array(anyObject), experience_analysis: anyObject, transferable_skills: z.array(z.string()), gaps: z.array(z.string()), risk_flags: z.array(z.string()), confidence: z.number().min(0).max(1), explanation: z.string() });
export const cvImproveOutput = z.strictObject({ current_score: z.number().min(0).max(100), priority_actions: z.array(z.string()), summary_recommendations: z.array(z.string()), experience_recommendations: z.array(z.string()), skill_recommendations: z.array(z.string()), ats_recommendations: z.array(z.string()), job_specific_recommendations: z.array(z.string()), rewrite_examples: z.array(anyObject), keywords_to_consider: z.array(z.string()), warnings: z.array(z.string()) });
export const shortlistOutput = z.strictObject({ job: anyObject, candidates: z.array(anyObject), scoring_methodology: anyObject });
