import { z } from "zod";

const nullableNumber = z.number().nullable();
const dataQuality = z.strictObject({ completeTradeCount: z.number().int().nonnegative(), incompleteTradeCount: z.number().int().nonnegative(), warnings: z.array(z.string()) });
const metric = z.strictObject({ totalTrades: z.number().int().nonnegative(), winningTrades: z.number().int().nonnegative(), losingTrades: z.number().int().nonnegative(), breakevenTrades: z.number().int().nonnegative(), winRate: nullableNumber, lossRate: nullableNumber, grossProfit: nullableNumber, grossLoss: nullableNumber, netPnl: nullableNumber, averageWinningTrade: nullableNumber, averageLosingTrade: nullableNumber, largestWinner: nullableNumber, largestLoser: nullableNumber, profitFactor: nullableNumber, expectancyPerTrade: nullableNumber, averageRMultiple: nullableNumber, totalR: nullableNumber.optional(), maximumDrawdownR: nullableNumber.optional(), cumulativeReturn: nullableNumber, maximumDrawdown: nullableNumber, currentDrawdown: nullableNumber, recoveryFactor: nullableNumber, sharpeRatio: nullableNumber, sortinoRatio: nullableNumber, volatility: nullableNumber, averageHoldingPeriodSeconds: nullableNumber, bestTradingDay: z.string().nullable(), worstTradingDay: z.string().nullable(), maxConsecutiveWins: z.number().int().nonnegative(), maxConsecutiveLosses: z.number().int().nonnegative() });

const provenance = z.strictObject({ strategyPerformance: z.enum(["GROK", "SIGNALFLOW", "MERGED", "NEW"]), tradeRisk: z.enum(["GROK", "SIGNALFLOW", "MERGED", "NEW"]), portfolioExposure: z.enum(["GROK", "SIGNALFLOW", "MERGED", "NEW"]), tradeLog: z.enum(["GROK", "SIGNALFLOW", "MERGED", "NEW"]), notes: z.array(z.string()) });
export const strategyPerformanceAnalysisOutput = z.strictObject({ metrics: metric, performanceSummary: z.string(), strengths: z.array(z.string()), weaknesses: z.array(z.string()), riskFlags: z.array(z.string()), dataQuality, calculationAssumptions: z.array(z.string()), methodology: z.array(z.string()).optional(), sourceTraceability: provenance.optional() });
export const tradeRiskScoreOutput = z.strictObject({ riskScore: z.number().int().min(0).max(100), riskLevel: z.enum(["low", "moderate", "high", "critical"]), riskAmount: nullableNumber, accountRiskPct: nullableNumber, riskRewardRatio: nullableNumber, positionExposurePct: nullableNumber, leverage: nullableNumber, safeLeverage: nullableNumber.optional(), riskFactors: z.array(z.string()), positiveFactors: z.array(z.string()), warnings: z.array(z.string()), calculationBreakdown: z.strictObject({ components: z.record(z.string(), z.number()), thresholds: z.record(z.string(), z.number()), assumptions: z.array(z.string()) }), sourceTraceability: provenance.optional() });
const exposurePosition = z.strictObject({ symbol: z.string(), direction: z.enum(["long", "short"]), exposure: z.number().nonnegative(), concentrationPct: nullableNumber, openRisk: nullableNumber });
export const portfolioExposureCheckOutput = z.strictObject({ grossExposure: z.number().nonnegative(), netExposure: z.number(), longExposure: z.number().nonnegative(), shortExposure: z.number().nonnegative(), exposurePctOfEquity: nullableNumber, largestConcentrationPct: nullableNumber, leverage: nullableNumber, positions: z.array(exposurePosition), concentrationFlags: z.array(z.string()), riskFlags: z.array(z.string()), summary: z.string(), accountEquity: nullableNumber, openRisk: nullableNumber, marginUsage: nullableNumber, availableFreeMargin: nullableNumber, sourceTraceability: provenance.optional() });
const grouped = z.array(z.strictObject({ key: z.string(), trades: z.number().int().nonnegative(), wins: z.number().int().nonnegative(), losses: z.number().int().nonnegative(), netPnl: nullableNumber, fees: nullableNumber, winRate: nullableNumber }));
export const tradeLogAnalysisOutput = z.strictObject({ summary: z.strictObject({ totalTrades: z.number().int().nonnegative(), closedTrades: z.number().int().nonnegative(), openTrades: z.number().int().nonnegative(), wins: z.number().int().nonnegative(), losses: z.number().int().nonnegative(), netPnl: nullableNumber, fees: nullableNumber, maxWinningStreak: z.number().int().nonnegative(), maxLosingStreak: z.number().int().nonnegative(), averageHoldingDurationSeconds: nullableNumber }), performanceBySymbol: grouped, performanceByStrategy: grouped, performanceBySession: grouped, executionMetrics: z.strictObject({ completeRecords: z.number().int().nonnegative(), malformedRecords: z.number().int().nonnegative(), duplicateTradeIds: z.array(z.string()), outOfOrderTimestamps: z.number().int().nonnegative(), missingPrices: z.number().int().nonnegative() }), behavioralPatterns: z.array(z.string()), anomalies: z.array(z.string()), riskFlags: z.array(z.string()), dataQuality, sourceTraceability: provenance.optional() });

export type StrategyPerformanceAnalysisOutput = z.infer<typeof strategyPerformanceAnalysisOutput>;
export type TradeRiskScoreOutput = z.infer<typeof tradeRiskScoreOutput>;
export type PortfolioExposureCheckOutput = z.infer<typeof portfolioExposureCheckOutput>;
export type TradeLogAnalysisOutput = z.infer<typeof tradeLogAnalysisOutput>;
