/** Documentation-only example. Unknown provider facts are represented as unavailable/null. */
export const COMPANY_DUE_DILIGENCE_EXAMPLE_OUTPUT = {
  success: true,
  company: { name: "Example Trading Ltd", domain: "example.com", country: "GB", registrationNumber: null },
  purpose: "supplier_onboarding",
  depth: "standard",
  checks: { registry: true, sanctions: true, adverseMedia: true, reputation: true, businessRisk: true },
  entityResolution: { status: "unresolved", confidence: 0, matchedIdentifiers: [], candidateCount: 0 },
  registrationCheck: { success: true, data: { status: "unknown", legalName: null, registrationNumber: null, jurisdiction: null, incorporationDate: null, source: null } },
  sanctionsCheck: { success: true, data: { status: "not_checked", matches: [], listsChecked: [], listsUnavailable: [] } },
  adverseMediaCheck: { success: true, data: { articlesChecked: 0, negativeArticles: 0, materialFindings: [], riskScore: 0, riskLevel: "low", confidence: 0 } },
  reputationCheck: { success: false, error: { code: "NOT_CHECKED", message: "Reputation check disabled by request." } },
  businessRiskCheck: { success: true, data: {} },
  entityMatch: { status: "unverified", confidence: 0, matchedOn: [] },
  registration: { status: "not_verified", incorporatedAt: null, source: null },
  websiteSignals: { domainAgeYears: null, ssl: null, businessIdentityMatch: null, confidence: 0 },
  management: [],
  sanctions: { status: "not_checked", matches: [], listsChecked: [], listsUnavailable: [] },
  legalSignals: [],
  negativeNews: { materialCount: 0, items: [] },
  financialSignals: { status: "unavailable", signals: [] },
  reputation: { score: null, risk: null },
  riskScore: null,
  riskLevel: null,
  confidence: 0,
  riskBreakdown: { identity: null, registration: null, sanctions: null, legal: null, negativeNews: null, financial: null, reputation: null },
  redFlags: [],
  recommendation: "insufficient_data",
  reasonCodes: ["INSUFFICIENT_DATA"],
  sources: [],
  decision: { action: "insufficient_data", requiresHumanReview: false },
  evidence: [],
  coverage: { registration: "not_checked", website: "not_checked", sanctions: "not_checked", negativeNews: "not_checked", financial: "unavailable" },
  providers: [],
  generatedAt: "2026-01-01T00:00:00.000Z"
} as const;
