/**
 * GENERATED by scripts/generateCompanyReputationExample.ts — do not edit by hand.
 *
 * Documented example output for company_reputation_check. EXPLICITLY SYNTHETIC: a fictional company
 * ("Example Technologies Ltd"), fictional publishers on reserved .example domains and a made-up LEI,
 * run through the real scoring pipeline. It illustrates the response shape and reasoning; it is not
 * an assessment of any real entity.
 */
export const COMPANY_REPUTATION_CHECK_EXAMPLE_OUTPUT = {
  "company": {
    "requestedName": "Example Technologies Ltd",
    "resolvedName": "EXAMPLE TECHNOLOGIES LIMITED",
    "country": "GB",
    "countryName": "United Kingdom",
    "website": "https://example.com",
    "domain": "example.com",
    "registrationNumber": "01234567",
    "lei": "984500EXAMPLE0TECH47",
    "city": "Manchester",
    "industry": null
  },
  "resolution": {
    "status": "resolved",
    "confidence": 99,
    "methods": [
      "registry_registration_number_match",
      "registry_name_match",
      "registry_country_match",
      "website_mentions_company_name",
      "domain_consistent_with_name",
      "same_entity_in_multiple_registries"
    ],
    "conflicts": [],
    "candidates": [
      {
        "legalName": "EXAMPLE TECHNOLOGIES LIMITED",
        "country": "GB",
        "city": "Manchester",
        "registrationNumber": "01234567",
        "lei": null,
        "status": "active",
        "registry": "UK Companies House",
        "matchScore": 0.95,
        "matchedOn": [
          "registration_number",
          "name",
          "country"
        ],
        "conflicts": [],
        "evidenceId": "ev_5affca7d022322a5"
      },
      {
        "legalName": "EXAMPLE TECHNOLOGIES LIMITED",
        "country": "GB",
        "city": "Manchester",
        "registrationNumber": "01234567",
        "lei": "984500EXAMPLE0TECH47",
        "status": "active",
        "registry": "GLEIF Global LEI Index",
        "matchScore": 0.95,
        "matchedOn": [
          "registration_number",
          "name",
          "country"
        ],
        "conflicts": [],
        "evidenceId": "ev_a11006affa832d28"
      }
    ]
  },
  "reputationScore": 64,
  "confidenceScore": 90,
  "trustLevel": "some_concerns",
  "scores": {
    "identity": 90,
    "legalRegulatory": 42,
    "adverseMedia": 59,
    "customerReputation": 53,
    "onlinePresence": 59,
    "businessStability": 82,
    "cyberDomain": 71,
    "transparency": 70
  },
  "scoreBreakdown": [
    {
      "dimension": "identity",
      "weight": 0.2,
      "score": 90,
      "rawScore": 90,
      "coverage": 100,
      "positiveSignals": 4,
      "negativeSignals": 0
    },
    {
      "dimension": "legalRegulatory",
      "weight": 0.2,
      "score": 42,
      "rawScore": 41,
      "coverage": 87,
      "positiveSignals": 0,
      "negativeSignals": 1
    },
    {
      "dimension": "adverseMedia",
      "weight": 0.15,
      "score": 59,
      "rawScore": 68,
      "coverage": 52,
      "positiveSignals": 0,
      "negativeSignals": 1
    },
    {
      "dimension": "customerReputation",
      "weight": 0.15,
      "score": 53,
      "rawScore": 58,
      "coverage": 36,
      "positiveSignals": 1,
      "negativeSignals": 1
    },
    {
      "dimension": "onlinePresence",
      "weight": 0.1,
      "score": 59,
      "rawScore": 59,
      "coverage": 100,
      "positiveSignals": 2,
      "negativeSignals": 0
    },
    {
      "dimension": "businessStability",
      "weight": 0.1,
      "score": 82,
      "rawScore": 82,
      "coverage": 100,
      "positiveSignals": 2,
      "negativeSignals": 0
    },
    {
      "dimension": "cyberDomain",
      "weight": 0.05,
      "score": 71,
      "rawScore": 71,
      "coverage": 100,
      "positiveSignals": 2,
      "negativeSignals": 0
    },
    {
      "dimension": "transparency",
      "weight": 0.05,
      "score": 70,
      "rawScore": 70,
      "coverage": 100,
      "positiveSignals": 5,
      "negativeSignals": 0
    }
  ],
  "confidenceBreakdown": {
    "resolution": 0.99,
    "dimensionCoverage": 0.81,
    "independentSources": 0.84,
    "authority": 0.7,
    "freshness": 1,
    "diversity": 1,
    "jurisdictionCoverage": 1,
    "capsApplied": []
  },
  "identity": {
    "status": "consistent",
    "signals": [
      {
        "code": "REGISTRY_IDENTIFIER_MATCH",
        "dimension": "identity",
        "polarity": "positive",
        "severity": "high",
        "message": "Supplied registration number matches an official registry record (UK Companies House: EXAMPLE TECHNOLOGIES LIMITED).",
        "evidenceIds": [
          "ev_5affca7d022322a5"
        ],
        "sourceAuthority": "official_or_regulatory",
        "strength": 1
      },
      {
        "code": "MULTIPLE_REGISTRIES_CONSISTENT",
        "dimension": "identity",
        "polarity": "positive",
        "severity": "medium",
        "message": "The same legal entity appears consistently in more than one registry (shared LEI/registration number).",
        "evidenceIds": [
          "ev_a11006affa832d28"
        ],
        "sourceAuthority": "official_or_regulatory",
        "strength": 1
      },
      {
        "code": "WEBSITE_NAMES_COMPANY",
        "dimension": "identity",
        "polarity": "positive",
        "severity": "low",
        "message": "The company's website names the company (self-published; weak corroboration).",
        "evidenceIds": [
          "ev_a92406ac6c061836"
        ],
        "sourceAuthority": "business_database_or_other_publisher",
        "strength": 0.5
      },
      {
        "code": "DOMAIN_CONSISTENT_WITH_NAME",
        "dimension": "identity",
        "polarity": "positive",
        "severity": "info",
        "message": "The domain example.com is consistent with the company name.",
        "evidenceIds": [],
        "sourceAuthority": "business_database_or_other_publisher",
        "strength": 0.3
      }
    ]
  },
  "sanctions": {
    "status": "no_match_found",
    "listsChecked": [
      "UN Security Council Consolidated List",
      "US Consolidated Screening List (includes OFAC SDN)"
    ],
    "listsUnavailable": [],
    "matches": [],
    "highestConfidence": null
  },
  "adverseMedia": {
    "status": "items_found",
    "items": [
      {
        "eventId": "grp_0ebfb6a81116",
        "title": "Example Technologies fined £40,000 by data regulator over unsolicited marketing emails - Business Wire Example",
        "category": "regulatory",
        "categories": [
          "regulatory"
        ],
        "legalStage": "regulatory_action",
        "stageDescription": "regulatory action reported",
        "established": true,
        "severity": "high",
        "dimension": "legalRegulatory",
        "publishedAt": "2026-03-10T09:00:00.000Z",
        "coverageCount": 3,
        "relevance": 1,
        "sources": [
          {
            "sourceName": "business-wire.example",
            "url": "https://business-wire.example/2026/03/example-technologies-fined",
            "authority": "business_database_or_other_publisher"
          },
          {
            "sourceName": "regional-news.example",
            "url": "https://regional-news.example/tech/example-technologies-fined-data-regulator",
            "authority": "business_database_or_other_publisher"
          },
          {
            "sourceName": "aggregator.example",
            "url": "https://aggregator.example/story/88231?utm_source=feed",
            "authority": "business_database_or_other_publisher"
          }
        ],
        "evidenceIds": [
          "ev_29a4dfbf8d81d7d6",
          "ev_9be03f39f4f07c34",
          "ev_ab70911ebcf36276"
        ]
      },
      {
        "eventId": "grp_eeeca7d3e3da",
        "title": "Former staff member alleges Example Technologies misled customers about uptime",
        "category": "customer_harm",
        "categories": [
          "customer_harm"
        ],
        "legalStage": "allegation",
        "stageDescription": "allegation reported (not established)",
        "established": false,
        "severity": "low",
        "dimension": "adverseMedia",
        "publishedAt": "2025-11-02T10:00:00.000Z",
        "coverageCount": 1,
        "relevance": 1,
        "sources": [
          {
            "sourceName": "tech-weekly.example",
            "url": "https://tech-weekly.example/opinion/example-technologies-customers",
            "authority": "business_database_or_other_publisher"
          }
        ],
        "evidenceIds": [
          "ev_aa1252fcee5ef7a7"
        ]
      }
    ],
    "neutralMentions": 1,
    "victimOrReporterMentions": 0,
    "excludedPossibleOtherEntity": 1,
    "duplicatesMerged": 2
  },
  "customerSentiment": {
    "status": "mostly_positive",
    "aggregateRatings": [
      {
        "platform": "reviews.example",
        "rating": 4.2,
        "scale": 5,
        "reviewCount": 312,
        "url": "https://reviews.example/review/example.com",
        "evidenceId": "ev_9fac691518d8b6d4"
      }
    ],
    "positiveSignals": [
      {
        "code": "FAVORABLE_AGGREGATE_RATING",
        "dimension": "customerReputation",
        "polarity": "positive",
        "severity": "medium",
        "message": "Aggregate rating 4.2/5 from 312 reviews on reviews.example (self-selected reviewers).",
        "evidenceIds": [
          "ev_9fac691518d8b6d4"
        ],
        "sourceAuthority": "business_database_or_other_publisher",
        "strength": 0.5
      }
    ],
    "negativeSignals": [
      {
        "code": "NEGATIVE_CUSTOMER_REPORT",
        "dimension": "customerReputation",
        "polarity": "negative",
        "severity": "low",
        "message": "Negative customer/user report (unverified, forum/social post): \"Anyone used Example Technologies? Still waiting on a refund\".",
        "evidenceIds": [
          "ev_501e75ec20a6d905"
        ],
        "sourceAuthority": "forum_social_or_user_generated",
        "strength": 0.2
      }
    ]
  },
  "onlinePresence": {
    "status": "established",
    "signals": [
      {
        "code": "WEBSITE_OPERATIONAL",
        "dimension": "onlinePresence",
        "polarity": "positive",
        "severity": "low",
        "message": "The company website is reachable over HTTPS with substantive content.",
        "evidenceIds": [
          "ev_a92406ac6c061836"
        ],
        "sourceAuthority": "business_database_or_other_publisher",
        "strength": 0.6
      },
      {
        "code": "INDEPENDENT_WEB_MENTIONS",
        "dimension": "onlinePresence",
        "polarity": "positive",
        "severity": "low",
        "message": "4 independent web sources mention the company.",
        "evidenceIds": [
          "ev_29a4dfbf8d81d7d6",
          "ev_9be03f39f4f07c34",
          "ev_9fac691518d8b6d4",
          "ev_aa1252fcee5ef7a7",
          "ev_ab70911ebcf36276",
          "ev_c4b7e5988ee08443"
        ],
        "sourceAuthority": "business_database_or_other_publisher",
        "strength": 0.4
      }
    ]
  },
  "legalRiskSignals": [
    {
      "code": "NO_SANCTIONS_MATCH_IN_CHECKED_LISTS",
      "dimension": "legalRegulatory",
      "polarity": "positive",
      "severity": "info",
      "message": "No sanctions-list name match above the 0.88 similarity threshold was found in: UN Security Council Consolidated List; US Consolidated Screening List (includes OFAC SDN). Lists not checked are not covered.",
      "evidenceIds": [],
      "sourceAuthority": "official_or_regulatory",
      "strength": 0
    },
    {
      "code": "ADVERSE_REGULATORY_ESTABLISHED",
      "dimension": "legalRegulatory",
      "polarity": "negative",
      "severity": "high",
      "message": "regulatory — regulatory action reported: \"Example Technologies fined £40,000 by data regulator over unsolicited marketing emails - Business Wire Example\" (3 publisher(s), 3 item(s) grouped as one event).",
      "evidenceIds": [
        "ev_29a4dfbf8d81d7d6",
        "ev_9be03f39f4f07c34",
        "ev_ab70911ebcf36276"
      ],
      "sourceAuthority": "business_database_or_other_publisher",
      "strength": 0.6
    }
  ],
  "businessStabilitySignals": [
    {
      "code": "REGISTRY_STATUS_ACTIVE",
      "dimension": "businessStability",
      "polarity": "positive",
      "severity": "medium",
      "message": "Official registry records show the entity as active.",
      "evidenceIds": [
        "ev_5affca7d022322a5",
        "ev_a11006affa832d28"
      ],
      "sourceAuthority": "official_or_regulatory",
      "strength": 1
    },
    {
      "code": "ESTABLISHED_10_PLUS_YEARS",
      "dimension": "businessStability",
      "polarity": "positive",
      "severity": "medium",
      "message": "Registered/created 2012-03-14 (14 years).",
      "evidenceIds": [
        "ev_5affca7d022322a5",
        "ev_a11006affa832d28"
      ],
      "sourceAuthority": "official_or_regulatory",
      "strength": 1
    }
  ],
  "cyberDomainSignals": [
    {
      "code": "DOMAIN_ESTABLISHED",
      "dimension": "cyberDomain",
      "polarity": "positive",
      "severity": "low",
      "message": "Domain registered 2011-05-02 (15 years ago).",
      "evidenceIds": [
        "ev_8829a4e919301c87"
      ],
      "sourceAuthority": "official_or_regulatory",
      "strength": 1
    },
    {
      "code": "WEBSITE_HTTPS",
      "dimension": "cyberDomain",
      "polarity": "positive",
      "severity": "info",
      "message": "The website is served over HTTPS.",
      "evidenceIds": [
        "ev_a92406ac6c061836"
      ],
      "sourceAuthority": "business_database_or_other_publisher",
      "strength": 0.6
    }
  ],
  "transparencySignals": [
    {
      "code": "PUBLICLY_REGISTERED_ENTITY",
      "dimension": "transparency",
      "polarity": "positive",
      "severity": "low",
      "message": "The entity has a public registry record.",
      "evidenceIds": [
        "ev_5affca7d022322a5"
      ],
      "sourceAuthority": "official_or_regulatory",
      "strength": 0.8
    },
    {
      "code": "WEBSITE_CONTACT_AND_ABOUT",
      "dimension": "transparency",
      "polarity": "positive",
      "severity": "low",
      "message": "The website links to contact and about/company pages.",
      "evidenceIds": [
        "ev_a92406ac6c061836"
      ],
      "sourceAuthority": "business_database_or_other_publisher",
      "strength": 0.5
    },
    {
      "code": "WEBSITE_LEGAL_PAGES",
      "dimension": "transparency",
      "polarity": "positive",
      "severity": "low",
      "message": "The website links to a privacy policy and/or terms.",
      "evidenceIds": [
        "ev_a92406ac6c061836"
      ],
      "sourceAuthority": "business_database_or_other_publisher",
      "strength": 0.5
    },
    {
      "code": "WEBSITE_PUBLISHES_REGISTRATION_DETAILS",
      "dimension": "transparency",
      "polarity": "positive",
      "severity": "low",
      "message": "The website publishes company registration/VAT/registered-office details.",
      "evidenceIds": [
        "ev_a92406ac6c061836"
      ],
      "sourceAuthority": "business_database_or_other_publisher",
      "strength": 0.6
    },
    {
      "code": "CORPORATE_EMAIL_ON_COMPANY_DOMAIN",
      "dimension": "transparency",
      "polarity": "positive",
      "severity": "info",
      "message": "Contact email addresses on the website use the company's own domain.",
      "evidenceIds": [
        "ev_a92406ac6c061836"
      ],
      "sourceAuthority": "business_database_or_other_publisher",
      "strength": 0.4
    }
  ],
  "positiveSignals": [
    {
      "code": "REGISTRY_IDENTIFIER_MATCH",
      "dimension": "identity",
      "polarity": "positive",
      "severity": "high",
      "message": "Supplied registration number matches an official registry record (UK Companies House: EXAMPLE TECHNOLOGIES LIMITED).",
      "evidenceIds": [
        "ev_5affca7d022322a5"
      ],
      "sourceAuthority": "official_or_regulatory",
      "strength": 1
    },
    {
      "code": "ESTABLISHED_10_PLUS_YEARS",
      "dimension": "businessStability",
      "polarity": "positive",
      "severity": "medium",
      "message": "Registered/created 2012-03-14 (14 years).",
      "evidenceIds": [
        "ev_5affca7d022322a5",
        "ev_a11006affa832d28"
      ],
      "sourceAuthority": "official_or_regulatory",
      "strength": 1
    },
    {
      "code": "MULTIPLE_REGISTRIES_CONSISTENT",
      "dimension": "identity",
      "polarity": "positive",
      "severity": "medium",
      "message": "The same legal entity appears consistently in more than one registry (shared LEI/registration number).",
      "evidenceIds": [
        "ev_a11006affa832d28"
      ],
      "sourceAuthority": "official_or_regulatory",
      "strength": 1
    },
    {
      "code": "REGISTRY_STATUS_ACTIVE",
      "dimension": "businessStability",
      "polarity": "positive",
      "severity": "medium",
      "message": "Official registry records show the entity as active.",
      "evidenceIds": [
        "ev_5affca7d022322a5",
        "ev_a11006affa832d28"
      ],
      "sourceAuthority": "official_or_regulatory",
      "strength": 1
    },
    {
      "code": "FAVORABLE_AGGREGATE_RATING",
      "dimension": "customerReputation",
      "polarity": "positive",
      "severity": "medium",
      "message": "Aggregate rating 4.2/5 from 312 reviews on reviews.example (self-selected reviewers).",
      "evidenceIds": [
        "ev_9fac691518d8b6d4"
      ],
      "sourceAuthority": "business_database_or_other_publisher",
      "strength": 0.5
    },
    {
      "code": "DOMAIN_ESTABLISHED",
      "dimension": "cyberDomain",
      "polarity": "positive",
      "severity": "low",
      "message": "Domain registered 2011-05-02 (15 years ago).",
      "evidenceIds": [
        "ev_8829a4e919301c87"
      ],
      "sourceAuthority": "official_or_regulatory",
      "strength": 1
    },
    {
      "code": "PUBLICLY_REGISTERED_ENTITY",
      "dimension": "transparency",
      "polarity": "positive",
      "severity": "low",
      "message": "The entity has a public registry record.",
      "evidenceIds": [
        "ev_5affca7d022322a5"
      ],
      "sourceAuthority": "official_or_regulatory",
      "strength": 0.8
    },
    {
      "code": "WEBSITE_OPERATIONAL",
      "dimension": "onlinePresence",
      "polarity": "positive",
      "severity": "low",
      "message": "The company website is reachable over HTTPS with substantive content.",
      "evidenceIds": [
        "ev_a92406ac6c061836"
      ],
      "sourceAuthority": "business_database_or_other_publisher",
      "strength": 0.6
    },
    {
      "code": "WEBSITE_PUBLISHES_REGISTRATION_DETAILS",
      "dimension": "transparency",
      "polarity": "positive",
      "severity": "low",
      "message": "The website publishes company registration/VAT/registered-office details.",
      "evidenceIds": [
        "ev_a92406ac6c061836"
      ],
      "sourceAuthority": "business_database_or_other_publisher",
      "strength": 0.6
    },
    {
      "code": "WEBSITE_CONTACT_AND_ABOUT",
      "dimension": "transparency",
      "polarity": "positive",
      "severity": "low",
      "message": "The website links to contact and about/company pages.",
      "evidenceIds": [
        "ev_a92406ac6c061836"
      ],
      "sourceAuthority": "business_database_or_other_publisher",
      "strength": 0.5
    },
    {
      "code": "WEBSITE_LEGAL_PAGES",
      "dimension": "transparency",
      "polarity": "positive",
      "severity": "low",
      "message": "The website links to a privacy policy and/or terms.",
      "evidenceIds": [
        "ev_a92406ac6c061836"
      ],
      "sourceAuthority": "business_database_or_other_publisher",
      "strength": 0.5
    },
    {
      "code": "WEBSITE_NAMES_COMPANY",
      "dimension": "identity",
      "polarity": "positive",
      "severity": "low",
      "message": "The company's website names the company (self-published; weak corroboration).",
      "evidenceIds": [
        "ev_a92406ac6c061836"
      ],
      "sourceAuthority": "business_database_or_other_publisher",
      "strength": 0.5
    },
    {
      "code": "INDEPENDENT_WEB_MENTIONS",
      "dimension": "onlinePresence",
      "polarity": "positive",
      "severity": "low",
      "message": "4 independent web sources mention the company.",
      "evidenceIds": [
        "ev_29a4dfbf8d81d7d6",
        "ev_9be03f39f4f07c34",
        "ev_9fac691518d8b6d4",
        "ev_aa1252fcee5ef7a7",
        "ev_ab70911ebcf36276",
        "ev_c4b7e5988ee08443"
      ],
      "sourceAuthority": "business_database_or_other_publisher",
      "strength": 0.4
    },
    {
      "code": "WEBSITE_HTTPS",
      "dimension": "cyberDomain",
      "polarity": "positive",
      "severity": "info",
      "message": "The website is served over HTTPS.",
      "evidenceIds": [
        "ev_a92406ac6c061836"
      ],
      "sourceAuthority": "business_database_or_other_publisher",
      "strength": 0.6
    },
    {
      "code": "CORPORATE_EMAIL_ON_COMPANY_DOMAIN",
      "dimension": "transparency",
      "polarity": "positive",
      "severity": "info",
      "message": "Contact email addresses on the website use the company's own domain.",
      "evidenceIds": [
        "ev_a92406ac6c061836"
      ],
      "sourceAuthority": "business_database_or_other_publisher",
      "strength": 0.4
    },
    {
      "code": "DOMAIN_CONSISTENT_WITH_NAME",
      "dimension": "identity",
      "polarity": "positive",
      "severity": "info",
      "message": "The domain example.com is consistent with the company name.",
      "evidenceIds": [],
      "sourceAuthority": "business_database_or_other_publisher",
      "strength": 0.3
    },
    {
      "code": "NO_SANCTIONS_MATCH_IN_CHECKED_LISTS",
      "dimension": "legalRegulatory",
      "polarity": "positive",
      "severity": "info",
      "message": "No sanctions-list name match above the 0.88 similarity threshold was found in: UN Security Council Consolidated List; US Consolidated Screening List (includes OFAC SDN). Lists not checked are not covered.",
      "evidenceIds": [],
      "sourceAuthority": "official_or_regulatory",
      "strength": 0
    }
  ],
  "redFlags": [
    {
      "code": "ADVERSE_REGULATORY_ESTABLISHED",
      "dimension": "legalRegulatory",
      "polarity": "negative",
      "severity": "high",
      "message": "regulatory — regulatory action reported: \"Example Technologies fined £40,000 by data regulator over unsolicited marketing emails - Business Wire Example\" (3 publisher(s), 3 item(s) grouped as one event).",
      "evidenceIds": [
        "ev_29a4dfbf8d81d7d6",
        "ev_9be03f39f4f07c34",
        "ev_ab70911ebcf36276"
      ],
      "sourceAuthority": "business_database_or_other_publisher",
      "strength": 0.6
    }
  ],
  "evidenceSummary": {
    "totalEvidence": 11,
    "independentSources": 11,
    "highConfidenceSources": 5,
    "freshestEvidenceAt": "2026-09-23T08:00:00.000Z",
    "oldestEvidenceAt": "2025-05-03T00:00:00.000Z",
    "duplicatesMerged": 2,
    "excludedPossibleOtherEntity": 1,
    "servedFromCache": 0,
    "staleEvidence": 0,
    "evidenceTruncated": false
  },
  "evidence": [
    {
      "id": "ev_8829a4e919301c87",
      "type": "domain",
      "sourceName": "RDAP domain registration data",
      "sourceUrl": "https://rdap.example/domain/example.com",
      "sourceRecordId": "example.com",
      "sourceAuthority": "official_or_regulatory",
      "title": "Domain registration record for example.com",
      "summary": "Registered: 2011-05-02T00:00:00.000Z; expires: 2027-05-02T00:00:00.000Z.",
      "publishedAt": "2025-05-03T00:00:00.000Z",
      "observedAt": "2026-09-23T08:00:00.000Z",
      "jurisdiction": null,
      "companyIdentifiers": {
        "name": null,
        "registrationNumber": null,
        "lei": null,
        "domain": "example.com",
        "country": null
      },
      "quality": 1,
      "relevance": 1,
      "fromCache": false
    },
    {
      "id": "ev_5affca7d022322a5",
      "type": "registry",
      "sourceName": "UK Companies House",
      "sourceUrl": "https://registry.example/record/01234567",
      "sourceRecordId": "01234567",
      "sourceAuthority": "official_or_regulatory",
      "title": "EXAMPLE TECHNOLOGIES LIMITED",
      "summary": "Status: active",
      "publishedAt": null,
      "observedAt": "2026-09-23T08:00:00.000Z",
      "jurisdiction": "GB",
      "companyIdentifiers": {
        "name": "EXAMPLE TECHNOLOGIES LIMITED",
        "registrationNumber": "01234567",
        "lei": null,
        "domain": null,
        "country": "GB"
      },
      "quality": 1,
      "relevance": 1,
      "fromCache": false
    },
    {
      "id": "ev_a11006affa832d28",
      "type": "registry",
      "sourceName": "GLEIF Global LEI Index",
      "sourceUrl": "https://registry.example/record/984500EXAMPLE0TECH47",
      "sourceRecordId": "984500EXAMPLE0TECH47",
      "sourceAuthority": "official_or_regulatory",
      "title": "EXAMPLE TECHNOLOGIES LIMITED",
      "summary": "Status: active",
      "publishedAt": null,
      "observedAt": "2026-09-23T08:00:00.000Z",
      "jurisdiction": "GB",
      "companyIdentifiers": {
        "name": "EXAMPLE TECHNOLOGIES LIMITED",
        "registrationNumber": "01234567",
        "lei": "984500EXAMPLE0TECH47",
        "domain": null,
        "country": "GB"
      },
      "quality": 1,
      "relevance": 1,
      "fromCache": false
    },
    {
      "id": "ev_9fac691518d8b6d4",
      "type": "review",
      "sourceName": "reviews.example",
      "sourceUrl": "https://reviews.example/review/example.com",
      "sourceRecordId": null,
      "sourceAuthority": "business_database_or_other_publisher",
      "title": "Example Technologies Reviews | Reviews Example",
      "summary": "Example Technologies Ltd is rated 4.2 out of 5 based on 312 reviews. Customers mention reliable service and responsive support.",
      "publishedAt": "2026-09-01T00:00:00.000Z",
      "observedAt": "2026-09-23T08:00:00.000Z",
      "jurisdiction": null,
      "companyIdentifiers": {
        "name": null,
        "registrationNumber": null,
        "lei": null,
        "domain": null,
        "country": null
      },
      "quality": 0.5,
      "relevance": 1,
      "fromCache": false
    },
    {
      "id": "ev_c4b7e5988ee08443",
      "type": "news",
      "sourceName": "daily-ledger.example",
      "sourceUrl": "https://daily-ledger.example/2026/05/example-technologies-manchester-office",
      "sourceRecordId": null,
      "sourceAuthority": "business_database_or_other_publisher",
      "title": "Example Technologies opens second Manchester office",
      "summary": "Manchester-based Example Technologies Ltd opened a second office and plans to hire 40 engineers.",
      "publishedAt": "2026-05-20T08:00:00.000Z",
      "observedAt": "2026-09-23T08:00:00.000Z",
      "jurisdiction": null,
      "companyIdentifiers": {
        "name": null,
        "registrationNumber": null,
        "lei": null,
        "domain": null,
        "country": null
      },
      "quality": 0.5,
      "relevance": 1,
      "fromCache": false
    },
    {
      "id": "ev_ab70911ebcf36276",
      "type": "news",
      "sourceName": "aggregator.example",
      "sourceUrl": "https://aggregator.example/story/88231?utm_source=feed",
      "sourceRecordId": null,
      "sourceAuthority": "business_database_or_other_publisher",
      "title": "Example Technologies fined £40,000 by data regulator over unsolicited marketing emails",
      "summary": "Example Technologies Ltd fined £40,000 by data regulator.",
      "publishedAt": "2026-03-11T07:00:00.000Z",
      "observedAt": "2026-09-23T08:00:00.000Z",
      "jurisdiction": null,
      "companyIdentifiers": {
        "name": null,
        "registrationNumber": null,
        "lei": null,
        "domain": null,
        "country": null
      },
      "quality": 0.5,
      "relevance": 1,
      "fromCache": false
    },
    {
      "id": "ev_9be03f39f4f07c34",
      "type": "news",
      "sourceName": "regional-news.example",
      "sourceUrl": "https://regional-news.example/tech/example-technologies-fined-data-regulator",
      "sourceRecordId": null,
      "sourceAuthority": "business_database_or_other_publisher",
      "title": "Example Technologies fined £40,000 by data regulator over unsolicited marketing emails | Regional News Example",
      "summary": "Example Technologies Ltd was fined £40,000 by the data regulator over unsolicited marketing emails.",
      "publishedAt": "2026-03-10T11:30:00.000Z",
      "observedAt": "2026-09-23T08:00:00.000Z",
      "jurisdiction": null,
      "companyIdentifiers": {
        "name": null,
        "registrationNumber": null,
        "lei": null,
        "domain": null,
        "country": null
      },
      "quality": 0.5,
      "relevance": 1,
      "fromCache": false
    },
    {
      "id": "ev_29a4dfbf8d81d7d6",
      "type": "news",
      "sourceName": "business-wire.example",
      "sourceUrl": "https://business-wire.example/2026/03/example-technologies-fined",
      "sourceRecordId": null,
      "sourceAuthority": "business_database_or_other_publisher",
      "title": "Example Technologies fined £40,000 by data regulator over unsolicited marketing emails - Business Wire Example",
      "summary": "The data protection regulator fined Example Technologies Ltd £40,000 after finding it sent unsolicited marketing emails. The company said it has updated its consent process.",
      "publishedAt": "2026-03-10T09:00:00.000Z",
      "observedAt": "2026-09-23T08:00:00.000Z",
      "jurisdiction": null,
      "companyIdentifiers": {
        "name": null,
        "registrationNumber": null,
        "lei": null,
        "domain": null,
        "country": null
      },
      "quality": 0.5,
      "relevance": 1,
      "fromCache": false
    },
    {
      "id": "ev_aa1252fcee5ef7a7",
      "type": "news",
      "sourceName": "tech-weekly.example",
      "sourceUrl": "https://tech-weekly.example/opinion/example-technologies-customers",
      "sourceRecordId": null,
      "sourceAuthority": "business_database_or_other_publisher",
      "title": "Former staff member alleges Example Technologies misled customers about uptime",
      "summary": "In a blog interview, a former employee alleged that Example Technologies Ltd made misleading claims about service uptime. The company disputes the claims.",
      "publishedAt": "2025-11-02T10:00:00.000Z",
      "observedAt": "2026-09-23T08:00:00.000Z",
      "jurisdiction": null,
      "companyIdentifiers": {
        "name": null,
        "registrationNumber": null,
        "lei": null,
        "domain": null,
        "country": null
      },
      "quality": 0.5,
      "relevance": 1,
      "fromCache": false
    },
    {
      "id": "ev_a92406ac6c061836",
      "type": "website",
      "sourceName": "Company website (example.com)",
      "sourceUrl": "https://example.com/",
      "sourceRecordId": null,
      "sourceAuthority": "business_database_or_other_publisher",
      "title": "Example Technologies Ltd — Cloud software for logistics",
      "summary": "Website responded with HTTP 200 over HTTPS.",
      "publishedAt": null,
      "observedAt": "2026-09-23T08:00:00.000Z",
      "jurisdiction": null,
      "companyIdentifiers": {
        "name": null,
        "registrationNumber": null,
        "lei": null,
        "domain": "example.com",
        "country": null
      },
      "quality": 0.5,
      "relevance": 1,
      "fromCache": false
    },
    {
      "id": "ev_501e75ec20a6d905",
      "type": "forum",
      "sourceName": "forum.example",
      "sourceUrl": "https://forum.example/t/example-technologies-refund",
      "sourceRecordId": null,
      "sourceAuthority": "forum_social_or_user_generated",
      "title": "Anyone used Example Technologies? Still waiting on a refund",
      "summary": "Posted by an anonymous user: I cancelled my Example Technologies Ltd subscription and never received my refund after three weeks.",
      "publishedAt": "2026-08-14T00:00:00.000Z",
      "observedAt": "2026-09-23T08:00:00.000Z",
      "jurisdiction": null,
      "companyIdentifiers": {
        "name": null,
        "registrationNumber": null,
        "lei": null,
        "domain": null,
        "country": null
      },
      "quality": 0.2,
      "relevance": 1,
      "fromCache": false
    }
  ],
  "coverage": {
    "providers": [
      {
        "provider": "UK Companies House",
        "category": "registry",
        "status": "ok",
        "fromCache": false,
        "fetchedAt": "2026-09-23T08:00:00.000Z",
        "evidenceCount": 1,
        "reason": null
      },
      {
        "provider": "GLEIF Global LEI Index",
        "category": "registry",
        "status": "ok",
        "fromCache": false,
        "fetchedAt": "2026-09-23T08:00:00.000Z",
        "evidenceCount": 1,
        "reason": null
      },
      {
        "provider": "UN Security Council Consolidated List",
        "category": "sanctions",
        "status": "ok",
        "fromCache": false,
        "fetchedAt": "2026-09-23T08:00:00.000Z",
        "evidenceCount": 1,
        "reason": null
      },
      {
        "provider": "US Consolidated Screening List (includes OFAC SDN)",
        "category": "sanctions",
        "status": "ok",
        "fromCache": false,
        "fetchedAt": "2026-09-23T08:00:00.000Z",
        "evidenceCount": 0,
        "reason": null
      },
      {
        "provider": "EU Financial Sanctions Files (consolidated list)",
        "category": "sanctions",
        "status": "not_configured",
        "fromCache": false,
        "fetchedAt": null,
        "evidenceCount": 0,
        "reason": "EU Financial Sanctions Files (consolidated list) is not configured (synthetic)."
      },
      {
        "provider": "News and public web search",
        "category": "news",
        "status": "ok",
        "fromCache": false,
        "fetchedAt": "2026-09-23T08:00:00.000Z",
        "evidenceCount": 6,
        "reason": null
      },
      {
        "provider": "Review platforms and forums (web search)",
        "category": "reviews",
        "status": "ok",
        "fromCache": false,
        "fetchedAt": "2026-09-23T08:00:00.000Z",
        "evidenceCount": 2,
        "reason": null
      },
      {
        "provider": "Company website",
        "category": "website",
        "status": "ok",
        "fromCache": false,
        "fetchedAt": "2026-09-23T08:00:00.000Z",
        "evidenceCount": 1,
        "reason": null
      },
      {
        "provider": "Domain registration (RDAP)",
        "category": "domain",
        "status": "ok",
        "fromCache": false,
        "fetchedAt": "2026-09-23T08:00:00.000Z",
        "evidenceCount": 1,
        "reason": null
      }
    ],
    "dimensionsWithEvidence": [
      "identity",
      "legalRegulatory",
      "adverseMedia",
      "customerReputation",
      "onlinePresence",
      "businessStability",
      "cyberDomain",
      "transparency"
    ],
    "jurisdictionRegistryChecked": true
  },
  "warnings": [
    {
      "code": "PROVIDER_NOT_CONFIGURED",
      "message": "Not enabled in this deployment: EU Financial Sanctions Files (consolidated list).",
      "provider": null
    }
  ],
  "limitations": [
    "SYNTHETIC DOCUMENTATION EXAMPLE: fictional company, fictional publishers (.example domains) and a made-up LEI. Not an assessment of any real entity.",
    "Evidence-based public-source screening only — not a legal, KYC/AML, credit or compliance determination, and not a guarantee of legitimacy or of misconduct.",
    "reputationScore summarizes publicly observable signals; confidenceScore states how much evidence supports it. Read them together.",
    "Absence of evidence is not evidence of absence: sources not checked, or companies with little public footprint, lower confidence rather than raising the score.",
    "Sanctions results are automated name matching. 'possible' matches are not listings; 'high' matches still require verification at the source list.",
    "Adverse media is reported at the legal stage the source states; allegations, investigations and lawsuits are not findings of wrongdoing.",
    "Customer reviews and forum posts are unverified, self-selected opinions and are weighted accordingly.",
    "External web content is treated strictly as data; instruction-like text found in it is removed and never acted upon.",
    "Sanctions lists checked: UN Security Council Consolidated List; US Consolidated Screening List (includes OFAC SDN). Other national lists were not checked."
  ],
  "summary": "Identity matched to registry record \"EXAMPLE TECHNOLOGIES LIMITED\" (UK Companies House; matched on registration_number, name, country). No sanctions-list name match was found in the checked sources (UN Security Council Consolidated List; US Consolidated Screening List (includes OFAC SDN)). 2 adverse-media event(s) identified (1 reporting an established outcome such as a judgment, settlement or regulatory action; 1 allegation/investigation/lawsuit-stage). Customer-reported signals were predominantly positive (unverified reviews/posts). Evidence: 11 independent source(s), 5 official/major. Reputation 64/100 at confidence 90/100 (some concerns).",
  "methodology": {
    "scoringModelVersion": "crc-1.0.0",
    "weights": {
      "identity": 0.2,
      "legalRegulatory": 0.2,
      "adverseMedia": 0.15,
      "customerReputation": 0.15,
      "onlinePresence": 0.1,
      "businessStability": 0.1,
      "cyberDomain": 0.05,
      "transparency": 0.05
    },
    "neutralPrior": 50,
    "note": "Each dimension score = neutralPrior + coverage × (evidence-derived score − neutralPrior); reputationScore = Σ weight × dimension score (then documented caps). Missing evidence pulls toward the neutral prior and lowers confidence; it never raises the score."
  }
};
