// GENERATED by scripts/generateDocumentFactsExample.ts from the real extraction pipeline over a
// synthetic agreement (fictional parties). Do not edit by hand — regenerate after extractor changes.
export { DOCUMENT_FACTS_EXAMPLE_INPUT } from "./documentFactsExtractExampleInput.js";

export const DOCUMENT_FACTS_EXAMPLE_OUTPUT = {
  "documentType": "contract",
  "documentSubtype": "service_agreement",
  "documentTypeConfidence": 0.97,
  "documentTypeSource": "detected",
  "language": "en",
  "title": "MAINTENANCE SERVICES AGREEMENT",
  "facts": [
    {
      "key": "parties",
      "label": "Parties",
      "value": [
        {
          "name": "Northwind Facilities LLC",
          "role": "supplier"
        },
        {
          "name": "Contoso Properties SAOG",
          "role": "customer"
        }
      ],
      "confidence": 0.9,
      "method": "definition",
      "sourceEvidence": {
        "page": 1,
        "section": "MAINTENANCE SERVICES AGREEMENT",
        "text": "This Maintenance Services Agreement is made on 15 January 2026 between Northwind Facilities LLC, a company registered in Oman (the \"Supplier\"), and Contoso Properties SAOG (the \"Customer\").",
        "startOffset": 130,
        "endOffset": 154
      }
    },
    {
      "key": "effective_date",
      "label": "Effective / start date",
      "value": "1 February 2026",
      "normalizedValue": "2026-02-01",
      "confidence": 0.97,
      "method": "pattern",
      "sourceEvidence": {
        "page": 1,
        "section": "1. TERM",
        "text": "This Agreement shall commence on 1 February 2026 and shall expire on 31 January 2027.",
        "startOffset": 291,
        "endOffset": 306
      }
    },
    {
      "key": "expiry_date",
      "label": "Expiry / end date",
      "value": "31 January 2027",
      "normalizedValue": "2027-01-31",
      "confidence": 0.97,
      "method": "pattern",
      "sourceEvidence": {
        "page": 1,
        "section": "1. TERM",
        "text": "This Agreement shall commence on 1 February 2026 and shall expire on 31 January 2027.",
        "startOffset": 327,
        "endOffset": 342
      }
    },
    {
      "key": "contract_value",
      "label": "Contract value",
      "value": "OMR 48,000",
      "normalizedValue": {
        "amount": 48000,
        "currency": "OMR",
        "frequency": "annual"
      },
      "confidence": 0.92,
      "method": "pattern",
      "sourceEvidence": {
        "page": 1,
        "section": "2. FEES AND PAYMENT",
        "text": "The total contract value is OMR 48,000 per annum, payable in equal monthly instalments.",
        "startOffset": 518,
        "endOffset": 528
      }
    },
    {
      "key": "renewal_terms",
      "label": "Renewal",
      "value": "The Agreement shall automatically renew for successive one (1) year periods unless either party gives notice of non-renewal.",
      "confidence": 0.8,
      "method": "clause",
      "sourceEvidence": {
        "page": 1,
        "section": "1. TERM",
        "text": "The Agreement shall automatically renew for successive one (1) year periods unless either party gives notice of non-renewal.",
        "startOffset": 344,
        "endOffset": 468
      }
    },
    {
      "key": "termination_clause",
      "label": "Termination",
      "value": "Either party may terminate this Agreement by giving sixty (60) days' written notice to the other party.",
      "confidence": 0.8,
      "method": "clause",
      "sourceEvidence": {
        "page": 2,
        "section": "5. TERMINATION",
        "text": "Either party may terminate this Agreement by giving sixty (60) days' written notice to the other party.",
        "startOffset": 1016,
        "endOffset": 1119
      }
    },
    {
      "key": "notice_period",
      "label": "Notice period",
      "value": "sixty (60) days",
      "normalizedValue": {
        "value": 60,
        "unit": "day",
        "iso8601": "P60D",
        "approxDays": 60
      },
      "confidence": 0.88,
      "method": "pattern",
      "sourceEvidence": {
        "page": 2,
        "section": "5. TERMINATION",
        "text": "Either party may terminate this Agreement by giving sixty (60) days' written notice to the other party.",
        "startOffset": 1068,
        "endOffset": 1083
      }
    },
    {
      "key": "penalty_clause",
      "label": "Penalty / liquidated damages",
      "value": "If the Supplier fails to meet the response time, liquidated damages of OMR 250 per incident shall apply.",
      "confidence": 0.8,
      "method": "clause",
      "sourceEvidence": {
        "page": 2,
        "section": "4. PENALTIES",
        "text": "If the Supplier fails to meet the response time, liquidated damages of OMR 250 per incident shall apply.",
        "startOffset": 895,
        "endOffset": 999
      }
    },
    {
      "key": "service_level",
      "label": "Service level (SLA)",
      "value": "The Supplier shall maintain 99.5% availability of critical building systems and shall respond to emergency call-outs within four (4) hours.",
      "confidence": 0.8,
      "method": "clause",
      "sourceEvidence": {
        "page": 2,
        "section": "3. SERVICE LEVELS",
        "text": "The Supplier shall maintain 99.5% availability of critical building systems and shall respond to emergency call-outs within four (4) hours.",
        "startOffset": 741,
        "endOffset": 880
      }
    },
    {
      "key": "governing_law",
      "label": "Governing law",
      "value": "Sultanate of Oman",
      "confidence": 0.9,
      "method": "clause",
      "sourceEvidence": {
        "page": 2,
        "section": "7. GOVERNING LAW",
        "text": "This Agreement shall be governed by the laws of the Sultanate of Oman.",
        "startOffset": 1416,
        "endOffset": 1433
      }
    },
    {
      "key": "limitation_of_liability",
      "label": "Limitation of liability",
      "value": "The Supplier's aggregate liability under this Agreement shall not exceed the total fees paid in the preceding twelve (12) months.",
      "confidence": 0.8,
      "method": "clause",
      "sourceEvidence": {
        "page": 2,
        "section": "6. LIABILITY",
        "text": "The Supplier's aggregate liability under this Agreement shall not exceed the total fees paid in the preceding twelve (12) months.",
        "startOffset": 1216,
        "endOffset": 1345
      }
    },
    {
      "key": "contract_number",
      "label": "Contract number",
      "value": "MSA-2026-014",
      "confidence": 0.93,
      "method": "labeled_field",
      "sourceEvidence": {
        "page": 1,
        "section": "MAINTENANCE SERVICES AGREEMENT",
        "text": "Agreement No: MSA-2026-014",
        "startOffset": 45,
        "endOffset": 57
      }
    },
    {
      "key": "agreement_date",
      "label": "Agreement date",
      "value": "15 January 2026",
      "normalizedValue": "2026-01-15",
      "confidence": 0.97,
      "method": "pattern",
      "sourceEvidence": {
        "page": 1,
        "section": "MAINTENANCE SERVICES AGREEMENT",
        "text": "This Maintenance Services Agreement is made on 15 January 2026 between Northwind Facilities LLC, a company registered in Oman (the \"Supplier\"), and Contoso Properties SAOG (the \"Customer\").",
        "startOffset": 106,
        "endOffset": 121
      }
    },
    {
      "key": "supplier",
      "label": "Supplier",
      "value": "Northwind Facilities LLC",
      "confidence": 0.88,
      "method": "definition",
      "sourceEvidence": {
        "page": 1,
        "section": "MAINTENANCE SERVICES AGREEMENT",
        "text": "This Maintenance Services Agreement is made on 15 January 2026 between Northwind Facilities LLC, a company registered in Oman (the \"Supplier\"), and Contoso Properties SAOG (the \"Customer\").",
        "startOffset": 130,
        "endOffset": 154
      }
    },
    {
      "key": "customer",
      "label": "Customer / buyer",
      "value": "Contoso Properties SAOG",
      "confidence": 0.88,
      "method": "definition",
      "sourceEvidence": {
        "page": 1,
        "section": "MAINTENANCE SERVICES AGREEMENT",
        "text": "This Maintenance Services Agreement is made on 15 January 2026 between Northwind Facilities LLC, a company registered in Oman (the \"Supplier\"), and Contoso Properties SAOG (the \"Customer\").",
        "startOffset": 207,
        "endOffset": 230
      }
    },
    {
      "key": "automatic_renewal",
      "label": "Automatic renewal",
      "value": true,
      "confidence": 0.9,
      "method": "clause",
      "sourceEvidence": {
        "page": 1,
        "section": "1. TERM",
        "text": "The Agreement shall automatically renew for successive one (1) year periods unless either party gives notice of non-renewal.",
        "startOffset": 344,
        "endOffset": 468
      }
    },
    {
      "key": "renewal_term",
      "label": "Renewal term",
      "value": "one (1) year",
      "normalizedValue": {
        "value": 1,
        "unit": "year",
        "iso8601": "P1Y",
        "approxDays": 365
      },
      "confidence": 0.88,
      "method": "pattern",
      "sourceEvidence": {
        "page": 1,
        "section": "1. TERM",
        "text": "The Agreement shall automatically renew for successive one (1) year periods unless either party gives notice of non-renewal.",
        "startOffset": 399,
        "endOffset": 411
      }
    },
    {
      "key": "currency",
      "label": "Currency",
      "value": "OMR",
      "normalizedValue": "OMR",
      "confidence": 0.88,
      "method": "pattern",
      "sourceEvidence": {
        "page": 1,
        "section": "2. FEES AND PAYMENT",
        "text": "The total contract value is OMR 48,000 per annum, payable in equal monthly instalments.",
        "startOffset": 518,
        "endOffset": 528
      }
    },
    {
      "key": "payment_period",
      "label": "Payment period",
      "value": "thirty (30) days",
      "normalizedValue": {
        "value": 30,
        "unit": "day",
        "iso8601": "P30D",
        "approxDays": 30
      },
      "confidence": 0.88,
      "method": "pattern",
      "sourceEvidence": {
        "page": 1,
        "section": "2. FEES AND PAYMENT",
        "text": "The Customer shall pay each invoice within thirty (30) days of receipt of a valid invoice.",
        "startOffset": 621,
        "endOffset": 637
      }
    },
    {
      "key": "late_payment_interest",
      "label": "Late-payment interest",
      "value": "1.5%",
      "normalizedValue": 0.015,
      "confidence": 0.9,
      "method": "pattern",
      "sourceEvidence": {
        "page": 1,
        "section": "2. FEES AND PAYMENT",
        "text": "Late payments shall bear interest at 1.5% per month.",
        "startOffset": 706,
        "endOffset": 710
      }
    },
    {
      "key": "uptime",
      "label": "Uptime / availability",
      "value": "99.5%",
      "normalizedValue": 0.995,
      "confidence": 0.9,
      "method": "pattern",
      "sourceEvidence": {
        "page": 2,
        "section": "3. SERVICE LEVELS",
        "text": "The Supplier shall maintain 99.5% availability of critical building systems and shall respond to emergency call-outs within four (4) hours.",
        "startOffset": 769,
        "endOffset": 774
      }
    }
  ],
  "requestedFacts": [
    {
      "request": "contract expiry date",
      "status": "found",
      "key": "expiry_date",
      "value": "31 January 2027",
      "confidence": 0.97,
      "method": "pattern",
      "normalizedValue": "2027-01-31",
      "sourceEvidence": {
        "page": 1,
        "section": "1. TERM",
        "text": "This Agreement shall commence on 1 February 2026 and shall expire on 31 January 2027.",
        "startOffset": 327,
        "endOffset": 342
      }
    },
    {
      "request": "termination notice period",
      "status": "found",
      "key": "notice_period",
      "value": "sixty (60) days",
      "confidence": 0.88,
      "method": "pattern",
      "normalizedValue": {
        "value": 60,
        "unit": "day",
        "iso8601": "P60D",
        "approxDays": 60
      },
      "sourceEvidence": {
        "page": 2,
        "section": "5. TERMINATION",
        "text": "Either party may terminate this Agreement by giving sixty (60) days' written notice to the other party.",
        "startOffset": 1068,
        "endOffset": 1083
      }
    },
    {
      "request": "annual contract value",
      "status": "found",
      "key": "contract_value",
      "value": "OMR 48,000",
      "confidence": 0.92,
      "method": "pattern",
      "normalizedValue": {
        "amount": 48000,
        "currency": "OMR",
        "frequency": "annual"
      },
      "sourceEvidence": {
        "page": 1,
        "section": "2. FEES AND PAYMENT",
        "text": "The total contract value is OMR 48,000 per annum, payable in equal monthly instalments.",
        "startOffset": 518,
        "endOffset": 528
      }
    }
  ],
  "entities": [
    {
      "type": "company",
      "name": "Northwind Facilities LLC",
      "confidence": 0.9,
      "sourceEvidence": {
        "page": 1,
        "section": "MAINTENANCE SERVICES AGREEMENT",
        "text": "This Maintenance Services Agreement is made on 15 January 2026 between Northwind Facilities LLC, a company registered in Oman (the \"Supplier\"), and Contoso Properties SAOG (the \"Customer\").",
        "startOffset": 130,
        "endOffset": 154
      },
      "role": "supplier"
    },
    {
      "type": "company",
      "name": "Contoso Properties SAOG",
      "confidence": 0.9,
      "sourceEvidence": {
        "page": 1,
        "section": "MAINTENANCE SERVICES AGREEMENT",
        "text": "This Maintenance Services Agreement is made on 15 January 2026 between Northwind Facilities LLC, a company registered in Oman (the \"Supplier\"), and Contoso Properties SAOG (the \"Customer\").",
        "startOffset": 207,
        "endOffset": 230
      },
      "role": "customer"
    },
    {
      "type": "location",
      "name": "Sultanate of Oman",
      "confidence": 0.85,
      "sourceEvidence": {
        "page": 2,
        "section": "7. GOVERNING LAW",
        "text": "This Agreement shall be governed by the laws of the Sultanate of Oman.",
        "startOffset": 1416,
        "endOffset": 1433
      },
      "role": "governing_law_jurisdiction"
    }
  ],
  "dates": [
    {
      "type": "agreement_date",
      "originalValue": "15 January 2026",
      "precision": "day",
      "confidence": 0.97,
      "sourceEvidence": {
        "page": 1,
        "section": "MAINTENANCE SERVICES AGREEMENT",
        "text": "This Maintenance Services Agreement is made on 15 January 2026 between Northwind Facilities LLC, a company registered in Oman (the \"Supplier\"), and Contoso Properties SAOG (the \"Customer\").",
        "startOffset": 106,
        "endOffset": 121
      },
      "normalizedDate": "2026-01-15"
    },
    {
      "type": "effective_date",
      "originalValue": "1 February 2026",
      "precision": "day",
      "confidence": 0.97,
      "sourceEvidence": {
        "page": 1,
        "section": "1. TERM",
        "text": "This Agreement shall commence on 1 February 2026 and shall expire on 31 January 2027.",
        "startOffset": 291,
        "endOffset": 306
      },
      "normalizedDate": "2026-02-01"
    },
    {
      "type": "expiry_date",
      "originalValue": "31 January 2027",
      "precision": "day",
      "confidence": 0.97,
      "sourceEvidence": {
        "page": 1,
        "section": "1. TERM",
        "text": "This Agreement shall commence on 1 February 2026 and shall expire on 31 January 2027.",
        "startOffset": 327,
        "endOffset": 342
      },
      "normalizedDate": "2027-01-31"
    }
  ],
  "amounts": [
    {
      "type": "contract_value",
      "amount": 48000,
      "originalValue": "OMR 48,000",
      "confidence": 0.92,
      "sourceEvidence": {
        "page": 1,
        "section": "2. FEES AND PAYMENT",
        "text": "The total contract value is OMR 48,000 per annum, payable in equal monthly instalments.",
        "startOffset": 518,
        "endOffset": 528
      },
      "currency": "OMR",
      "frequency": "annual"
    },
    {
      "type": "penalty",
      "amount": 250,
      "originalValue": "OMR 250",
      "confidence": 0.92,
      "sourceEvidence": {
        "page": 2,
        "section": "4. PENALTIES",
        "text": "If the Supplier fails to meet the response time, liquidated damages of OMR 250 per incident shall apply.",
        "startOffset": 966,
        "endOffset": 973
      },
      "currency": "OMR"
    }
  ],
  "percentages": [
    {
      "type": "late_payment_interest",
      "value": 1.5,
      "ratio": 0.015,
      "originalValue": "1.5%",
      "confidence": 0.9,
      "sourceEvidence": {
        "page": 1,
        "section": "2. FEES AND PAYMENT",
        "text": "Late payments shall bear interest at 1.5% per month.",
        "startOffset": 706,
        "endOffset": 710
      }
    },
    {
      "type": "uptime",
      "value": 99.5,
      "ratio": 0.995,
      "originalValue": "99.5%",
      "confidence": 0.9,
      "sourceEvidence": {
        "page": 2,
        "section": "3. SERVICE LEVELS",
        "text": "The Supplier shall maintain 99.5% availability of critical building systems and shall respond to emergency call-outs within four (4) hours.",
        "startOffset": 769,
        "endOffset": 774
      }
    }
  ],
  "obligations": [
    {
      "obligation": "The Customer shall pay each invoice within thirty (30) days of receipt of a valid invoice.",
      "modality": "must",
      "confidence": 0.85,
      "sourceEvidence": {
        "page": 1,
        "section": "2. FEES AND PAYMENT",
        "text": "The Customer shall pay each invoice within thirty (30) days of receipt of a valid invoice.",
        "startOffset": 578,
        "endOffset": 668
      },
      "party": "Customer",
      "deadline": "within thirty (30) days of receipt of a valid invoice"
    },
    {
      "obligation": "The Supplier shall maintain 99.5% availability of critical building systems and shall respond to emergency call-outs within four (4) hours.",
      "modality": "must",
      "confidence": 0.85,
      "sourceEvidence": {
        "page": 2,
        "section": "3. SERVICE LEVELS",
        "text": "The Supplier shall maintain 99.5% availability of critical building systems and shall respond to emergency call-outs within four (4) hours.",
        "startOffset": 741,
        "endOffset": 880
      },
      "party": "Supplier",
      "deadline": "within four (4) hours"
    }
  ],
  "requirements": [],
  "deadlines": [
    {
      "type": "expiry",
      "description": "This Agreement shall commence on 1 February 2026 and shall expire on 31 January 2027.",
      "confidence": 0.85,
      "sourceEvidence": {
        "page": 1,
        "section": "1. TERM",
        "text": "This Agreement shall commence on 1 February 2026 and shall expire on 31 January 2027.",
        "startOffset": 258,
        "endOffset": 343
      },
      "date": "2027-01-31"
    },
    {
      "type": "payment_deadline",
      "description": "The Customer shall pay each invoice within thirty (30) days of receipt of a valid invoice.",
      "confidence": 0.75,
      "sourceEvidence": {
        "page": 1,
        "section": "2. FEES AND PAYMENT",
        "text": "The Customer shall pay each invoice within thirty (30) days of receipt of a valid invoice.",
        "startOffset": 578,
        "endOffset": 668
      },
      "relative": "within thirty (30) days of receipt of a valid invoice"
    },
    {
      "type": "deadline",
      "description": "The Supplier shall maintain 99.5% availability of critical building systems and shall respond to emergency call-outs within four (4) hours.",
      "confidence": 0.75,
      "sourceEvidence": {
        "page": 2,
        "section": "3. SERVICE LEVELS",
        "text": "The Supplier shall maintain 99.5% availability of critical building systems and shall respond to emergency call-outs within four (4) hours.",
        "startOffset": 741,
        "endOffset": 880
      },
      "relative": "within four (4) hours"
    }
  ],
  "riskFlags": [
    {
      "type": "automatic_renewal",
      "severity": "medium",
      "reason": "The document states that the term renews automatically.",
      "sourceEvidence": {
        "page": 1,
        "section": "1. TERM",
        "text": "The Agreement shall automatically renew for successive one (1) year periods unless either party gives notice of non-renewal.",
        "startOffset": 344,
        "endOffset": 468
      }
    },
    {
      "type": "penalty_clause_detected",
      "severity": "medium",
      "reason": "The document contains a penalty, liquidated-damages or late-charge provision.",
      "sourceEvidence": {
        "page": 2,
        "section": "4. PENALTIES",
        "text": "If the Supplier fails to meet the response time, liquidated damages of OMR 250 per incident shall apply.",
        "startOffset": 895,
        "endOffset": 999
      }
    }
  ],
  "metadata": {
    "pageCount": 2,
    "characterCount": 1548,
    "wordCount": 217,
    "format": "text",
    "source": {
      "kind": "text",
      "url": null,
      "contentType": null,
      "byteLength": null
    },
    "pageProvenance": true,
    "extractionMode": "auto",
    "extractionMethod": "deterministic",
    "llmAssist": {
      "status": "disabled",
      "verifiedFacts": 0,
      "rejectedFacts": 0
    },
    "extractorVersion": "dfx-1.0.0"
  },
  "warnings": [],
  "overallConfidence": 0.78,
  "limitations": [
    "Extraction certainty is not business, legal or financial advice: facts are what the document states, risk flags describe observable conditions, and nothing is a legal conclusion.",
    "Scanned/image-only documents are not OCR'd; only an embedded text layer (or supplied text) is read.",
    "Page numbers appear only when the source has real page boundaries (PDF pages, \\f-separated text, DOCX rendered page breaks); otherwise evidence carries section and text only.",
    "Pattern extraction is tuned for English business documents; dates, amounts, percentages and currencies are recognized in several languages, but clause-level extraction in other languages is limited unless LLM assist is enabled.",
    "Values are returned as stated: nothing is computed, converted or annualized, and ambiguous dates/numbers/currency symbols are not normalized.",
    "Document content is treated as untrusted data: embedded instructions are never followed, and no link, macro or script inside the document is fetched or executed."
  ]
};
