// GENERATED by scripts/generateInvoiceAnomalyExample.ts from the real invoice_anomaly_check engine
// over a synthetic (fictional) invoice. Do not edit by hand — regenerate after engine/scoring changes.
export { INVOICE_ANOMALY_EXAMPLE_INPUT } from "./invoiceAnomalyCheckExampleInput.js";

export const INVOICE_ANOMALY_EXAMPLE_OUTPUT = {
  "riskScore": 100,
  "riskLevel": "critical",
  "decision": "hold",
  "anomalyCount": 4,
  "anomalies": [
    {
      "code": "POSSIBLE_DUPLICATE",
      "severity": "high",
      "confidence": 0.9,
      "field": "invoiceNumber",
      "explanation": "A same-supplier invoice with the same amount and a slightly altered invoice number (e.g. suffix or typo) was found nearby in time.",
      "evidence": {
        "reason": "invoice_number_variant_same_amount",
        "matchSignals": [
          "same_supplier",
          "same_amount",
          "date_gap_2_days",
          "invoice_number_variant"
        ],
        "matchedInvoice": {
          "historicalIndex": 3,
          "invoiceId": "AP-8117",
          "invoiceNumber": "INV-2026-1043",
          "supplierName": "ABC Trading LLC",
          "invoiceDate": "2026-09-18",
          "total": 9660,
          "currency": "USD",
          "status": "pending"
        },
        "matchedPayment": null,
        "invoiceNumberRelation": "variant",
        "amountDifferencePercent": 0,
        "dateDifferenceDays": 2,
        "lineItemSimilarity": null,
        "samePoNumber": false,
        "recurringAmountPattern": false,
        "previouslyPaid": false,
        "additionalMatches": 0
      }
    },
    {
      "code": "BANK_ACCOUNT_CHANGED",
      "severity": "high",
      "confidence": 0.9,
      "field": "bankAccount",
      "explanation": "The payment account on the invoice differs from the 1 account(s) previously recorded for this supplier; payment details should be verified with the supplier through a known contact before payment.",
      "evidence": {
        "reason": "account_differs_from_supplier_records",
        "invoiceAccountMasked": "****6789",
        "knownAccountsMasked": [
          "****4321"
        ],
        "knownAccountCount": 1,
        "lastUsedAccountMasked": "****4321",
        "lastUsedDate": "2026-09-18",
        "sources": {
          "supplierProfileAccounts": 0,
          "historicalInvoicesWithAccount": 4,
          "paymentsWithAccount": 0
        },
        "accountSeenForOtherSuppliers": false,
        "otherSuppliers": []
      }
    },
    {
      "code": "PO_MISMATCH",
      "severity": "high",
      "confidence": 0.9,
      "field": "poNumber",
      "explanation": "The invoice supplier differs from the purchase order supplier.",
      "evidence": {
        "issues": [
          {
            "reason": "supplier_differs_from_po",
            "severity": "high",
            "invoiceSupplier": "ABC Trading LLC",
            "poSupplier": "Delta Office Supplies Ltd"
          }
        ]
      }
    },
    {
      "code": "INVOICE_NUMBER_ANOMALY",
      "severity": "low",
      "confidence": 0.85,
      "field": "invoiceNumber",
      "explanation": "The invoice-number format AAA-9999-9999-A deviates from this supplier's established format AAA-9999-9999.",
      "evidence": {
        "issues": [
          {
            "reason": "format_deviates_from_supplier_pattern",
            "severity": "low",
            "invoiceNumber": "INV-2026-1043-A",
            "invoiceNumberFormat": "AAA-9999-9999-A",
            "establishedFormat": "AAA-9999-9999",
            "establishedFormatShare": 1,
            "sampleSize": 4
          }
        ]
      }
    }
  ],
  "financialChecks": {
    "subtotalValid": true,
    "taxValid": true,
    "totalValid": true,
    "lineTotalsValid": true,
    "computed": {
      "lineItemsSum": 9200,
      "expectedTax": 460,
      "expectedTotal": 9660,
      "tolerance": 0.01
    }
  },
  "recommendedAction": "Compare this invoice with the matched invoice and supporting documents to rule out a duplicate before payment. Verify the payment details directly with the supplier using contact details already on file (not those on the invoice) before paying. Resolve the purchase-order discrepancies (supplier, currency, reference, quantities or prices) before approval.",
  "summary": "4 anomalies detected (POSSIBLE_DUPLICATE, BANK_ACCOUNT_CHANGED, PO_MISMATCH, INVOICE_NUMBER_ANOMALY); risk critical (100/100). Advisory decision: hold — the invoice requires human review before payment.",
  "mode": "context_aware",
  "contextUsed": {
    "historicalInvoices": 4,
    "supplierHistoryMatched": 4,
    "paymentHistory": 0,
    "supplierProfile": false,
    "purchaseOrder": true,
    "contract": false,
    "approvalContext": false
  },
  "invoiceSummary": {
    "invoiceNumber": "INV-2026-1043-A",
    "supplierName": "ABC Trading LLC",
    "supplierId": "SUP-291",
    "invoiceDate": "2026-09-20",
    "dueDate": "2026-10-20",
    "currency": "USD",
    "total": 9660,
    "lineItemCount": 1,
    "bankAccountMasked": "****6789"
  },
  "dataCompleteness": {
    "missingRequiredFields": [],
    "missingRecommendedFields": []
  },
  "scoring": {
    "model": "iac-1.0.0",
    "components": [
      {
        "code": "POSSIBLE_DUPLICATE",
        "severity": "high",
        "confidence": 0.9,
        "basePoints": 40,
        "points": 36
      },
      {
        "code": "BANK_ACCOUNT_CHANGED",
        "severity": "high",
        "confidence": 0.9,
        "basePoints": 55,
        "points": 49.5
      },
      {
        "code": "PO_MISMATCH",
        "severity": "high",
        "confidence": 0.9,
        "basePoints": 35,
        "points": 31.5
      },
      {
        "code": "INVOICE_NUMBER_ANOMALY",
        "severity": "low",
        "confidence": 0.85,
        "basePoints": 5,
        "points": 4.3
      }
    ],
    "lowSeverityPoints": 4.3,
    "mediumSeverityPoints": 0,
    "highSeverityPoints": 117,
    "escalationBonus": 26,
    "escalationReasons": [
      "3 independent risk families with ≥ medium anomalies (duplicate, payment_details, po_contract): +16",
      "payment-detail anomaly combined with a duplicate, PO/contract or split anomaly: +10"
    ],
    "cappedBySeverity": true,
    "rawScore": 147.3,
    "levelBands": {
      "low": "0-14",
      "medium": "15-39",
      "high": "40-64",
      "critical": "65-100"
    }
  },
  "limitations": [
    "The capability identifies invoice anomalies and risk indicators. It does not independently establish fraud or replace accounting, audit, compliance, or payment-authorization controls.",
    "The decision field is advisory only; it is not an approval or rejection of the payment.",
    "Findings are limited to the data supplied in the request; no accounting system, bank or third-party source is consulted."
  ],
  "asOfDate": "2026-09-23",
  "checkedAt": "2026-09-23T00:00:00.000Z"
};
