/**
 * GENERATED by scripts/generateVehicleValueExample.ts — do not edit by hand.
 *
 * Documented example output for vehicle_value_estimate. EXPLICITLY SYNTHETIC: fictional fixture
 * listings (src/vehicle-value/examples/fixtures.ts) run through the real valuation engine. It
 * illustrates the response shape and reasoning; it is not a valuation of any real vehicle.
 */
export { VEHICLE_EXAMPLE_INPUT } from "./vehicleValueEstimateExampleInput.js";
export const VEHICLE_VALUE_EXAMPLE_OUTPUT = {
  "status": "estimated",
  "vehicle": {
    "make": "Toyota",
    "model": "Land Cruiser",
    "year": 2022,
    "trim": "GXR",
    "mileageKm": 68000,
    "condition": "good",
    "country": "Oman",
    "countryCode": "OM",
    "city": "Muscat",
    "fuelType": "petrol",
    "transmission": "automatic",
    "bodyType": "suv",
    "drivetrain": "4wd",
    "engine": "4.0L V6",
    "accidentHistory": "none",
    "serviceHistory": "full",
    "owners": 1,
    "color": "white",
    "options": [
      "360 camera",
      "leather seats",
      "sunroof"
    ],
    "ageYears": 5.1,
    "expectedMileageKm": 127500,
    "mileageVsExpectedPercent": -46.7
  },
  "valuationDate": "2026-09-23",
  "currency": "OMR",
  "estimatedValue": {
    "low": 22100,
    "mid": 23000,
    "high": 23900,
    "currency": "OMR"
  },
  "estimatedPrivateSalePrice": 23400,
  "estimatedDealerBuyPrice": 20600,
  "estimatedDealerRetailPrice": 25700,
  "askingPriceAnalysis": {
    "askingPrice": 22500,
    "differenceFromMid": -500,
    "differencePercent": -2.17,
    "marketPosition": "near_market",
    "withinEstimatedRange": true,
    "thresholdsPercent": {
      "wellBelow": -15,
      "below": -5,
      "above": 5,
      "wellAbove": 15
    }
  },
  "depreciation": {
    "estimatedOriginalPrice": null,
    "originalPriceSource": null,
    "totalDepreciationAmount": null,
    "totalDepreciationPercent": null,
    "estimatedAnnualDepreciationPercent": null,
    "marketImpliedAnnualDepreciationPercent": null
  },
  "adjustments": [
    {
      "factor": "mileage",
      "impactAmount": -20,
      "impactPercent": -0.1,
      "basis": "market_derived",
      "reason": "Mileage (68,000 km) is above the comparable-market median (66,000 km); the market-derived mileage effect is -0.53% per 10,000 km."
    },
    {
      "factor": "listing_to_transaction",
      "impactAmount": -680,
      "impactPercent": -3,
      "basis": "heuristic",
      "reason": "Comparable prices are listing asking prices; a 3.0% typical negotiation margin for Oman converts them to fair market value."
    },
    {
      "factor": "full_service_history",
      "impactAmount": 330,
      "impactPercent": 1.5,
      "basis": "heuristic",
      "reason": "Documented full service history supports stronger resale value."
    },
    {
      "factor": "owner_count",
      "impactAmount": 220,
      "impactPercent": 1,
      "basis": "heuristic",
      "reason": "Single owner over several years supports resale value."
    },
    {
      "factor": "major_options",
      "impactAmount": 330,
      "impactPercent": 1.5,
      "basis": "heuristic",
      "reason": "Premium equipment (360 camera, leather seats, sunroof) — small, capped uplift; comparables do not report equipment, so this is not market-derived."
    }
  ],
  "marketComparables": [
    {
      "make": "Toyota",
      "model": "Land Cruiser",
      "year": 2022,
      "trim": "GXR",
      "mileageKm": 71000,
      "askingPrice": 23300,
      "currency": "OMR",
      "originalAskingPrice": 23300,
      "originalCurrency": "OMR",
      "country": "OM",
      "city": "Muscat",
      "sourceName": "synthetic-dealer-feed",
      "sourceUrl": "https://dealer-feed.example/listing/lc-om-3",
      "observedAt": "2026-09-14T12:00:00.000Z",
      "priceType": "listing",
      "similarityScore": 0.99
    },
    {
      "make": "Toyota",
      "model": "Land Cruiser",
      "year": 2022,
      "trim": "GXR",
      "mileageKm": 59000,
      "askingPrice": 22400,
      "currency": "OMR",
      "originalAskingPrice": 22400,
      "originalCurrency": "OMR",
      "country": "OM",
      "city": "Muscat",
      "sourceName": "synthetic-listings-a",
      "sourceUrl": "https://listings-a.example/listing/lc-om-7",
      "observedAt": "2026-09-01T12:00:00.000Z",
      "priceType": "listing",
      "similarityScore": 0.97
    },
    {
      "make": "Toyota",
      "model": "Land Cruiser",
      "year": 2022,
      "trim": "GXR",
      "mileageKm": 62000,
      "askingPrice": 23250,
      "currency": "OMR",
      "originalAskingPrice": 23250,
      "originalCurrency": "OMR",
      "country": "OM",
      "city": "Muscat",
      "sourceName": "synthetic-listings-a",
      "sourceUrl": "https://listings-a.example/listing/lc-om-1",
      "observedAt": "2026-09-20T12:00:00.000Z",
      "priceType": "listing",
      "similarityScore": 0.97
    },
    {
      "make": "Toyota",
      "model": "Land Cruiser",
      "year": 2022,
      "trim": "GXR",
      "mileageKm": 80000,
      "askingPrice": 22550,
      "currency": "OMR",
      "originalAskingPrice": 22550,
      "originalCurrency": "OMR",
      "country": "OM",
      "city": "Muscat",
      "sourceName": "synthetic-listings-b",
      "sourceUrl": "https://listings-b.example/listing/lc-om-5",
      "observedAt": "2026-09-08T12:00:00.000Z",
      "priceType": "listing",
      "similarityScore": 0.96
    },
    {
      "make": "Toyota",
      "model": "Land Cruiser",
      "year": 2022,
      "trim": "GXR",
      "mileageKm": 55000,
      "askingPrice": 22700,
      "currency": "OMR",
      "originalAskingPrice": 22700,
      "originalCurrency": "OMR",
      "country": "OM",
      "city": "Muscat",
      "sourceName": "synthetic-listings-b",
      "sourceUrl": "https://listings-b.example/listing/lc-om-2",
      "observedAt": "2026-09-17T12:00:00.000Z",
      "priceType": "listing",
      "similarityScore": 0.96
    },
    {
      "make": "Toyota",
      "model": "Land Cruiser",
      "year": 2022,
      "trim": "GXR",
      "mileageKm": 52000,
      "askingPrice": 22900,
      "currency": "OMR",
      "originalAskingPrice": 22900,
      "originalCurrency": "OMR",
      "country": "OM",
      "city": "Muscat",
      "sourceName": "synthetic-dealer-feed",
      "sourceUrl": "https://dealer-feed.example/listing/lc-om-9",
      "observedAt": "2026-08-23T12:00:00.000Z",
      "priceType": "listing",
      "similarityScore": 0.95
    },
    {
      "make": "Toyota",
      "model": "Land Cruiser",
      "year": 2022,
      "trim": "GXR",
      "mileageKm": 90000,
      "askingPrice": 22800,
      "currency": "OMR",
      "originalAskingPrice": 22800,
      "originalCurrency": "OMR",
      "country": "OM",
      "city": "Muscat",
      "sourceName": "synthetic-listings-a",
      "sourceUrl": "https://listings-a.example/listing/lc-om-10",
      "observedAt": "2026-08-19T12:00:00.000Z",
      "priceType": "listing",
      "similarityScore": 0.94
    },
    {
      "make": "Toyota",
      "model": "Land Cruiser",
      "year": 2022,
      "trim": "GXR",
      "mileageKm": 74000,
      "askingPrice": 22850,
      "currency": "OMR",
      "originalAskingPrice": 22850,
      "originalCurrency": "OMR",
      "country": "OM",
      "city": "Nizwa",
      "sourceName": "synthetic-listings-b",
      "sourceUrl": "https://listings-b.example/listing/lc-om-8",
      "observedAt": "2026-08-28T12:00:00.000Z",
      "priceType": "listing",
      "similarityScore": 0.94
    },
    {
      "make": "Toyota",
      "model": "Land Cruiser",
      "year": 2022,
      "trim": "GXR",
      "mileageKm": 66000,
      "askingPrice": 23300,
      "currency": "OMR",
      "originalAskingPrice": 23300,
      "originalCurrency": "OMR",
      "country": "OM",
      "city": "Salalah",
      "sourceName": "synthetic-dealer-feed",
      "sourceUrl": "https://dealer-feed.example/listing/lc-om-6",
      "observedAt": "2026-09-05T12:00:00.000Z",
      "priceType": "listing",
      "similarityScore": 0.93
    },
    {
      "make": "Toyota",
      "model": "Land Cruiser",
      "year": 2022,
      "trim": "GXR",
      "mileageKm": 48000,
      "askingPrice": 23150,
      "currency": "OMR",
      "originalAskingPrice": 23150,
      "originalCurrency": "OMR",
      "country": "OM",
      "city": "Sohar",
      "sourceName": "synthetic-listings-a",
      "sourceUrl": "https://listings-a.example/listing/lc-om-4",
      "observedAt": "2026-09-11T12:00:00.000Z",
      "priceType": "listing",
      "similarityScore": 0.89
    }
  ],
  "marketStats": {
    "comparableCount": 10,
    "comparablesConsidered": 23,
    "outliersExcluded": 2,
    "medianPrice": 22875,
    "averagePrice": 22920,
    "medianMileageKm": 64000,
    "priceDispersionPercent": 1.6,
    "recentListingCount": 8,
    "pricePerKmAdjustment": -12.25,
    "currencyExcludedCount": 0
  },
  "methodology": {
    "fallbackLevel": "same_trim_same_year",
    "fallbackLevelDescription": "Same trim and model year in the local market.",
    "outlierMethod": "Tukey IQR fences (1.5×IQR) on log normalized price for n ≥ 5; modified z-score > 3.5 on MAD for n = 4",
    "yearEffect": {
      "basis": "not_needed",
      "annualPercent": null
    },
    "mileageEffect": {
      "basis": "market_derived",
      "percentPer10000Km": -0.53
    },
    "rangeHalfWidthPercent": 4,
    "dealerBuyDiscountPercent": 10.5,
    "privateSaleAdjustmentPercent": 1.8,
    "dealerRetailMarkupPercent": 11.6,
    "listingNegotiationDiscountPercent": 3
  },
  "confidence": {
    "score": 0.94,
    "level": "high",
    "reasons": [
      "10 comparable listing(s) used (12+ gives full weight to evidence volume).",
      "Mean comparable similarity is 0.95.",
      "100% of comparables share the exact trim.",
      "Mileage was provided.",
      "Median comparable age is 17 day(s).",
      "Evidence comes from 3 distinct source(s).",
      "Robust price dispersion across comparables is 1.6%."
    ],
    "factors": {
      "comparableVolume": 0.83,
      "similarity": 0.95,
      "trimMatch": 1,
      "mileageEvidence": 1,
      "locality": 0.94,
      "freshness": 1,
      "providerDiversity": 1,
      "priceConsistency": 0.96
    }
  },
  "riskFlags": [
    "HEURISTIC_ADJUSTMENTS_USED",
    "OUTLIERS_REMOVED"
  ],
  "assumptions": [
    "SYNTHETIC EXAMPLE: generated by the real valuation engine from fictional fixture listings (sources \"synthetic-…\", reserved .example URLs). It illustrates the response shape and method only; it is not a valuation of any real vehicle or market.",
    "Vehicle has clear legal ownership/title status with no outstanding finance, liens or registration restrictions.",
    "Estimate reflects available market evidence, not a physical inspection or a vehicle-history report.",
    "No undisclosed accident or structural damage; the stated accident history was not independently verified.",
    "Colour and engine description are recorded but not priced separately.",
    "No verified original (new) price reference was available, so total depreciation is not reported."
  ],
  "dataFreshness": {
    "latestComparableAt": "2026-09-20T12:00:00.000Z",
    "oldestComparableAt": "2026-08-19T12:00:00.000Z",
    "medianComparableAgeDays": 17,
    "recentListingCount": 8,
    "recentWindowDays": 30
  },
  "marketCoverage": {
    "countryCode": "OM",
    "country": "Oman",
    "region": "gcc",
    "valuationParametersConfigured": true,
    "marketDataProviders": [
      {
        "id": "synthetic-oman-listings",
        "status": "ok",
        "comparablesReturned": 23
      }
    ],
    "liveMarketDataAvailable": true,
    "regionalFallbackCountries": [
      "AE",
      "SA",
      "QA",
      "BH",
      "KW"
    ]
  },
  "disclaimer": "Estimate derived from available market evidence using deterministic methods. It is not a physical inspection, a vehicle-history check, a formal appraisal, or a guarantee of sale price, and it is not financial, lending or insurance advice."
};
