/**
 * Regenerates src/domain/examples/vehicleValueEstimateExample.ts — the registry's documented
 * exampleOutput for vehicle_value_estimate — by running the REAL engine over the explicitly synthetic
 * fixture listings in src/vehicle-value/examples/fixtures.ts (no network, fixed valuation date), then
 * prefixing a "synthetic example" notice to `assumptions`. Run after changing the engine or schemas:
 *   node --import tsx scripts/generateVehicleValueExample.ts
 * tests/vehicle-value.test.ts fails if the committed example drifts from the engine output.
 */
import { writeFileSync } from "node:fs";
import { runVehicleValueEstimate } from "../src/vehicle-value/service.js";
import { VEHICLE_EXAMPLE_INPUT } from "../src/domain/examples/vehicleValueEstimateExampleInput.js";
import { fixtureToday, syntheticOmanProviders } from "../src/vehicle-value/examples/fixtures.js";
import { VEHICLE_SYNTHETIC_EXAMPLE_NOTICE } from "../src/vehicle-value/examples/syntheticNotice.js";

const output = await runVehicleValueEstimate(VEHICLE_EXAMPLE_INPUT, { providers: syntheticOmanProviders(), today: fixtureToday, cache: null });
const example = { ...output, assumptions: [VEHICLE_SYNTHETIC_EXAMPLE_NOTICE, ...output.assumptions] };
const file = `/**
 * GENERATED by scripts/generateVehicleValueExample.ts — do not edit by hand.
 *
 * Documented example output for vehicle_value_estimate. EXPLICITLY SYNTHETIC: fictional fixture
 * listings (src/vehicle-value/examples/fixtures.ts) run through the real valuation engine. It
 * illustrates the response shape and reasoning; it is not a valuation of any real vehicle.
 */
export { VEHICLE_EXAMPLE_INPUT } from "./vehicleValueEstimateExampleInput.js";
export const VEHICLE_VALUE_EXAMPLE_OUTPUT = ${JSON.stringify(example, null, 2)};
`;
writeFileSync(new URL("../src/domain/examples/vehicleValueEstimateExample.ts", import.meta.url), file);
console.log("wrote src/domain/examples/vehicleValueEstimateExample.ts");
