/**
 * Regenerates src/domain/examples/businessRiskScoreExample.ts — the registry's documented
 * exampleOutput for business_risk_score — by running the REAL pipeline over the explicitly synthetic
 * scenario in src/business-risk/examples/syntheticScenario.ts (no network), then prefixing a
 * "synthetic example" notice to `limitations`. Run after changing scoring, detectors or schemas:
 *   node --import tsx scripts/generateBusinessRiskExample.ts
 * tests/business-risk.test.ts fails if the committed example drifts from the pipeline output.
 */
import { writeFileSync } from "node:fs";
import { runBusinessRiskScore } from "../src/business-risk/service.js";
import { BRS_SYNTHETIC_EXAMPLE_INPUT, brsSyntheticDependencies } from "../src/business-risk/examples/syntheticScenario.js";
import { BRS_SYNTHETIC_EXAMPLE_NOTICE } from "../src/domain/examples/businessRiskSyntheticNotice.js";

const output = await runBusinessRiskScore(BRS_SYNTHETIC_EXAMPLE_INPUT, brsSyntheticDependencies());
const example = { ...output, limitations: [BRS_SYNTHETIC_EXAMPLE_NOTICE, ...output.limitations] };
const file = `/**
 * GENERATED by scripts/generateBusinessRiskExample.ts — do not edit by hand.
 *
 * Documented example output for business_risk_score. EXPLICITLY SYNTHETIC: a fictional company
 * ("Example Trading Ltd"), made-up registry numbers and fictional publishers on reserved .example
 * domains, run through the real scoring pipeline. It illustrates the response shape and reasoning;
 * it is not an assessment of any real entity.
 */
export const BUSINESS_RISK_SCORE_EXAMPLE_OUTPUT = ${JSON.stringify(example, null, 2)};
`;
writeFileSync(new URL("../src/domain/examples/businessRiskScoreExample.ts", import.meta.url), file);
console.log("wrote src/domain/examples/businessRiskScoreExample.ts");
