import { writeFileSync } from "node:fs";
import { runInvoiceAnomalyCheck } from "../src/invoice-anomaly/service.js";
import { INVOICE_ANOMALY_EXAMPLE_INPUT } from "../src/domain/examples/invoiceAnomalyCheckExampleInput.js";

/**
 * Regenerates src/domain/examples/invoiceAnomalyCheckExample.ts — the static exampleOutput used by
 * OpenAPI, the x402 Bazaar declaration and discovery surfaces — by running the REAL engine over the
 * synthetic example input (deterministic: the input pins options.asOfDate). Run after any engine or
 * scoring change:  node --import tsx scripts/generateInvoiceAnomalyExample.ts
 */
const output = await runInvoiceAnomalyCheck(INVOICE_ANOMALY_EXAMPLE_INPUT);
const body = `// GENERATED by scripts/generateInvoiceAnomalyExample.ts from the real invoice_anomaly_check engine
// over a synthetic (fictional) invoice. Do not edit by hand — regenerate after engine/scoring changes.
export { INVOICE_ANOMALY_EXAMPLE_INPUT } from "./invoiceAnomalyCheckExampleInput.js";

export const INVOICE_ANOMALY_EXAMPLE_OUTPUT = ${JSON.stringify(output, null, 2)};
`;
writeFileSync(new URL("../src/domain/examples/invoiceAnomalyCheckExample.ts", import.meta.url), body);
console.log(`wrote example: riskScore ${output.riskScore} (${output.riskLevel}), ${output.anomalyCount} anomalies`);
