/**
 * Regenerates src/domain/examples/companyReputationCheckExample.ts — the registry's documented
 * exampleOutput for company_reputation_check — by running the REAL pipeline over the explicitly
 * synthetic scenario in src/company-reputation/examples/syntheticScenario.ts, then prefixing a
 * "synthetic example" notice to `limitations`. Run after changing scoring/analyzers:
 *   node --import tsx scripts/generateCompanyReputationExample.ts
 * tests/company-reputation.test.ts fails if the committed example drifts from the pipeline.
 */
import { writeFileSync } from "node:fs";
import { runCompanyReputationCheck } from "../src/company-reputation/service.js";
import { SYNTHETIC_EXAMPLE_INPUT, syntheticDependencies } from "../src/company-reputation/examples/syntheticScenario.js";
import { SYNTHETIC_EXAMPLE_NOTICE } from "../src/domain/examples/companyReputationSyntheticNotice.js";

const output = await runCompanyReputationCheck(SYNTHETIC_EXAMPLE_INPUT, syntheticDependencies());
const example = { ...output, limitations: [SYNTHETIC_EXAMPLE_NOTICE, ...output.limitations] };
const file = `/**
 * GENERATED by scripts/generateCompanyReputationExample.ts — do not edit by hand.
 *
 * Documented example output for company_reputation_check. EXPLICITLY SYNTHETIC: a fictional company
 * ("Example Technologies Ltd"), fictional publishers on reserved .example domains and a made-up LEI,
 * run through the real scoring pipeline. It illustrates the response shape and reasoning; it is not
 * an assessment of any real entity.
 */
export const COMPANY_REPUTATION_CHECK_EXAMPLE_OUTPUT = ${JSON.stringify(example, null, 2)};
`;
writeFileSync(new URL("../src/domain/examples/companyReputationCheckExample.ts", import.meta.url), file);
console.log("wrote src/domain/examples/companyReputationCheckExample.ts");
