import { writeFileSync } from "node:fs";
import { runDocumentFactsExtract } from "../src/document-facts/service.js";
import { DOCUMENT_FACTS_EXAMPLE_INPUT } from "../src/domain/examples/documentFactsExtractExampleInput.js";

/**
 * Regenerates src/domain/examples/documentFactsExtractExample.ts — the static exampleOutput used by
 * OpenAPI, the x402 Bazaar declaration and discovery surfaces — by running the REAL pipeline over
 * the synthetic sample agreement (deterministic; LLM assist disabled). Run after any extractor
 * change:  node --import tsx scripts/generateDocumentFactsExample.ts
 */
const output = await runDocumentFactsExtract(DOCUMENT_FACTS_EXAMPLE_INPUT, { llmEnabled: false });
const body = `// GENERATED by scripts/generateDocumentFactsExample.ts from the real extraction pipeline over a
// synthetic agreement (fictional parties). Do not edit by hand — regenerate after extractor changes.
export { DOCUMENT_FACTS_EXAMPLE_INPUT } from "./documentFactsExtractExampleInput.js";

export const DOCUMENT_FACTS_EXAMPLE_OUTPUT = ${JSON.stringify(output, null, 2)};
`;
writeFileSync(new URL("../src/domain/examples/documentFactsExtractExample.ts", import.meta.url), body);
console.log(`wrote example: ${output.facts.length} facts, ${output.riskFlags.length} risk flags, overallConfidence ${output.overallConfidence}`);
