import { createHash, randomUUID } from "node:crypto";
import { ApiError } from "../utils/errors.js";
import { transitionCall, type CallStatus } from "./state.js";
import { DisabledTelephonyProvider, TwilioTelephonyProvider, type TelephonyProvider, type CalendarProvider } from "./providers.js";
import type { z } from "zod";
import { aiCallAgentInput, appointmentCallAgentInput, voiceLeadQualifierInput } from "../schemas/voiceInputs.js";
import { callResult } from "../schemas/voiceOutputs.js";

type Input = z.infer<typeof aiCallAgentInput> | z.infer<typeof voiceLeadQualifierInput> | z.infer<typeof appointmentCallAgentInput>;
export interface VoiceCallRecord { callId: string; capability: string; phoneHash: string; status: CallStatus; answered: boolean; durationSeconds: number; input: Input; providerCallId: string | null; createdAt: string; completedAt: string | null; result: Record<string, unknown> | null; }
export interface VoiceServiceOptions { telephony?: TelephonyProvider; calendar?: CalendarProvider; callbackUrl?: string; doNotCall?: (phone: string) => boolean; now?: () => Date; }
export class VoiceService {
  private readonly calls = new Map<string, VoiceCallRecord>(); private readonly webhookEvents = new Set<string>(); private readonly now: () => Date; private readonly telephony: TelephonyProvider; private readonly calendar?: CalendarProvider; private readonly callbackUrl: string; private readonly doNotCall: (phone: string) => boolean;
  constructor(options: VoiceServiceOptions = {}) { this.now = options.now ?? (() => new Date()); this.telephony = options.telephony ?? new DisabledTelephonyProvider(); this.calendar = options.calendar; this.callbackUrl = options.callbackUrl ?? "/api/v1/voice/webhooks"; this.doNotCall = options.doNotCall ?? (() => false); }
  async start(capability: string, input: Input) { const phone = input.phoneNumber; if (this.doNotCall(phone)) throw new ApiError(403, "DO_NOT_CALL", "The destination is on the do-not-call list."); if ((input.safety?.recording || input.safety?.transcription) && !input.safety?.consentNotice) throw new ApiError(400, "CONSENT_NOTICE_REQUIRED", "A consent notice is required when recording or transcription is enabled."); const now = this.now().toISOString(); const callId = randomUUID(); const sanitizedInput = { ...input, phoneNumber: "[redacted]" } as Input; const record: VoiceCallRecord = { callId, capability, phoneHash: `sha256:${createHash("sha256").update(phone).digest("hex")}`, status: "created", answered: false, durationSeconds: 0, input: sanitizedInput, providerCallId: null, createdAt: now, completedAt: null, result: null }; this.calls.set(callId, record); record.status = transitionCall(record.status, "queued"); try { record.status = transitionCall(record.status, "dialing"); const provider = await this.telephony.initiate({ callId, to: phone, maxDurationSeconds: input.maxDurationSeconds, callbackUrl: this.callbackUrl }); record.providerCallId = provider.providerCallId; } catch (error) { record.status = "failed"; throw error; } return this.public(record); }
  get(callId: string) { const record = this.calls.get(callId); if (!record) throw new ApiError(404, "CALL_NOT_FOUND", "Call not found."); return this.public(record); }
  verifyWebhook(rawBody: string, signature: string | undefined) { const provider = this.telephony; return provider.verifyWebhook(rawBody, signature); }
  update(callId: string, status: CallStatus, durationSeconds = 0, result?: Record<string, unknown>) { const record = this.calls.get(callId); if (!record) throw new ApiError(404, "CALL_NOT_FOUND", "Call not found."); record.status = transitionCall(record.status, status); record.durationSeconds = Math.min(Math.max(0, Math.floor(durationSeconds)), record.input.maxDurationSeconds); record.answered = ["answered", "in_progress", "completed"].includes(status); if (result) record.result = result; if (["completed", "no_answer", "busy", "rejected", "failed", "cancelled"].includes(status)) record.completedAt = this.now().toISOString(); return this.public(record); }
  updateFromWebhook(eventId: string, callId: string, status: CallStatus, durationSeconds = 0, result?: Record<string, unknown>) { if (this.webhookEvents.has(eventId)) return this.get(callId); this.webhookEvents.add(eventId); return this.update(callId, status, durationSeconds, result); }
  qualify(input: z.infer<typeof voiceLeadQualifierInput>, call: Record<string, unknown>): Record<string, unknown> { const criteria = input.criteria; const facts = (call.structuredFacts ?? {}) as Record<string, unknown>; const evidence = Object.entries(facts).map(([field, value]) => ({ field, value, source: "customer_statement" as const })); let score = 0; if (facts.interest === "high") score += 25; if (facts.businessNeed) score += 20; if (facts.productRequested) score += 15; if (typeof facts.budgetAmount === "number" && (!criteria.minimumBudget || facts.budgetAmount >= criteria.minimumBudget)) score += 15; if (facts.timelineDays !== undefined && Number(facts.timelineDays) <= criteria.targetTimelineDays) score += 15; if (facts.decisionMaker === true) score += 10; const classification = score >= 70 && (!criteria.decisionMakerRequired || facts.decisionMaker === true) ? "qualified" : score >= 40 ? "needs_review" : "unqualified"; const qualification = { score, classification, intent: score >= 70 ? "high" : score >= 40 ? "medium" : "low", budget: typeof facts.budget === "string" ? facts.budget : null, timeline: typeof facts.timeline === "string" ? facts.timeline : null, decisionMaker: typeof facts.decisionMaker === "boolean" ? facts.decisionMaker : null, objections: Array.isArray(facts.objections) ? facts.objections : [], evidence }; return { ...call, qualification, recommendedNextAction: classification === "qualified" ? "schedule_sales_demo" : classification === "needs_review" ? "human_follow_up" : "nurture" }; }
  async appointment(input: z.infer<typeof appointmentCallAgentInput>) { const slot = input.availableSlots[0] ?? null; if ((input.action === "book" || input.action === "reschedule") && !slot) throw new ApiError(400, "SLOT_REQUIRED", "At least one available slot is required."); const call = await this.start("appointment_call_agent", input); if (input.action === "cancel") return { callId: call.callId, status: "cancelled", confirmedSlot: null, customerNotes: null, calendarEventId: null }; if (!slot) return { callId: call.callId, status: "proposed", confirmedSlot: null, customerNotes: null, calendarEventId: null }; const event = input.action === "book" || input.action === "reschedule" ? (this.calendar ? await this.calendar.create({ type: input.appointmentType, slot, timezone: input.timezone }) : null) : null; return { callId: call.callId, status: input.action === "reschedule" ? "rescheduled" : input.action === "book" ? "confirmed" : "proposed", confirmedSlot: slot, customerNotes: null, calendarEventId: event?.eventId ?? null }; }
  private public(record: VoiceCallRecord) { const parsed = { callId: record.callId, status: record.status, answered: record.answered, durationSeconds: record.durationSeconds, outcome: record.result?.outcome ?? null, summary: record.result?.summary ?? null, nextAction: record.result?.nextAction ?? null, structuredFacts: record.result?.structuredFacts ?? {}, transcript: record.result?.transcript ?? [], createdAt: record.createdAt, completedAt: record.completedAt }; return callResult.parse(parsed); }
}
function buildDefaultVoiceService() {
  const sid = process.env.TWILIO_ACCOUNT_SID?.trim(); const token = process.env.TWILIO_AUTH_TOKEN?.trim(); const from = process.env.TWILIO_FROM_NUMBER?.trim(); const secret = process.env.VOICE_WEBHOOK_SECRET?.trim();
  const telephony = sid && token && from && secret ? new TwilioTelephonyProvider(sid, token, from, secret) : new DisabledTelephonyProvider();
  return new VoiceService({ telephony, callbackUrl: process.env.VOICE_CALLBACK_URL?.trim() || "/api/v1/voice/webhooks" });
}
export const defaultVoiceService = buildDefaultVoiceService();
